/**
 * businessBooksExtra.ts — GENERADO por DATA/_scripts/extract_pulso_research.js desde el
 * workflow pulso-study-research (10 agentes, fuentes verificadas → DATA/BUSINESS/libros.md).
 * Frases-ancla fieles a cada libro + recursos con URL real. NO editar a mano.
 */
export interface LibroExtra {
  n: number;                 // n de ESTUDIO_LIBROS
  frase: string;             // frase-ancla fiel al libro (no inventada)
  recursos?: { titulo: string; url: string }[];
}

export const LIBROS_EXTRA: Record<number, LibroExtra> = {
  1: { n: 1, frase: "La obesidad es un desequilibrio hormonal, no calórico. No es lo que comes lo único que importa, sino lo que tu insulina hace con ello.", recursos: [{"titulo":"Jason Fung — canal oficial","url":"https://www.youtube.com/channel/UCLd-u54NoSym30ClzDr37DA"},{"titulo":"Dr. Jason Fung — 'The Aetiology of Obesity' (lecture completa, 6 partes)","url":"https://www.youtube.com/watch?v=ZKC3hiyLeRc"}] },
  2: { n: 2, frase: "No basta con vivir más tiempo; el objetivo es comprimir la 'década marginal' —esos últimos años de fragilidad y deterioro— hasta volverla casi inexistente. Entrena hoy para el cuerpo que quieres…", recursos: [{"titulo":"peterattiamd.com (incluye 'The Drive' podcast y artículos)","url":"https://peterattiamd.com/"},{"titulo":"Peter Attia MD — canal oficial","url":"https://www.youtube.com/@PeterAttiaMD"}] },
  3: { n: 3, frase: "Estos fármacos no son la salida fácil; son una herramienta médica para una enfermedad crónica. La pluma no sustituye al método: sin nutrición, músculo y seguimiento, el peso vuelve.", recursos: [{"titulo":"alexandrasowamd.com","url":"https://alexandrasowamd.com/"},{"titulo":"SoWell Health (getsowell.com) — página del libro","url":"https://getsowell.com/products/the-ozempic-revolution"}] },
  4: { n: 4, frase: "Come comida. No demasiada. Mayormente plantas. Si vino de una planta, cómelo; si fue hecho en una planta (industrial), no.", recursos: [{"titulo":"michaelpollan.com — In Defense of Food","url":"https://michaelpollan.com/books/in-defense-of-food/"},{"titulo":"In Defense of Food (documental PBS basado en el libro)","url":"https://www.pbs.org/food/features/in-defense-of-food/"}] },
  5: { n: 5, frase: "Tus hormonas no son tu destino, y tu cansancio no es tu carácter: la mayoría de estos síntomas son medibles y reversibles, y se empieza arreglando el estilo de vida antes que la receta.", recursos: [{"titulo":"saragottfriedmd.com","url":"https://www.saragottfriedmd.com/"},{"titulo":"Dr. Sara Gottfried: How to Optimize Female Hormone Health for Vitality & Longevity","url":"https://www.youtube.com/watch?v=GVRDGQhoEYQ"}] },
  6: { n: 6, frase: "El temor a la terapia hormonal le costó a una generación de mujeres beneficios reales para su corazón, sus huesos y su cerebro, por un riesgo de cáncer de mama que la propia evidencia nunca sostuvo.…", recursos: [{"titulo":"estrogenmatters.com","url":"https://estrogenmatters.com/"},{"titulo":"The Drive #42 (Peter Attia) — Bluming & Tavris sobre HRT y el mito del cáncer de mama","url":"https://peterattiamd.com/caroltavris-avrumbluming/"}] },
  8: { n: 8, frase: "El sueño es la cosa más efectiva que podemos hacer cada día para resetear la salud de nuestro cerebro y nuestro cuerpo — el mejor esfuerzo de la Madre Naturaleza contra la muerte.", recursos: [{"titulo":"Sleep is your superpower — Matt Walker | TED 2019","url":"https://www.ted.com/talks/matt_walker_sleep_is_your_superpower"},{"titulo":"Sleep Diplomat — Dr. Matthew Walker","url":"https://www.sleepdiplomat.com"}] },
  9: { n: 9, frase: "Cuándo comes importa tanto como qué comes — y corregir el cuándo es la intervención más simple y gratuita que existe.", recursos: [{"titulo":"myCircadianClock (app y blog del lab de Panda)","url":"https://www.mycircadianclock.org"},{"titulo":"Satchidananda Panda, PhD — Salk Institute","url":"https://www.salk.edu/scientist/satchidananda-panda/"}] },
  10: { n: 10, frase: "Sientes como piensas: tus estados de ánimo los crean tus pensamientos, no los eventos externos — y por eso puedes cambiarlos.", recursos: [{"titulo":"Feeling Good — David D. Burns, MD","url":"https://feelinggood.com"},{"titulo":"Feeling good | David Burns | TEDxReno","url":"https://www.youtube.com/watch?v=H1T5uMeYv9Q"}] },
  11: { n: 11, frase: "Si estás deprimido o ansioso, no eres una máquina con piezas rotas — eres un ser humano con necesidades no satisfechas.", recursos: [{"titulo":"This could be why you're depressed or anxious — Johann Hari | TED","url":"https://www.ted.com/talks/johann_hari_this_could_be_why_you_re_depressed_or_anxious"},{"titulo":"Lost Connections — sitio oficial","url":"https://thelostconnections.com"}] },
  12: { n: 12, frase: "No estás a merced de circuitos emocionales míticos: eres el arquitecto de tu propia experiencia.", recursos: [{"titulo":"You aren't at the mercy of your emotions — your brain creates them | Lisa Feldman Barrett ","url":"https://www.ted.com/talks/lisa_feldman_barrett_you_aren_t_at_the_mercy_of_your_emotions_your_brain_creates_them"},{"titulo":"Lisa Feldman Barrett — sitio oficial","url":"https://lisafeldmanbarrett.com/books/how-emotions-are-made/"}] },
  13: { n: 13, frase: "Tener TDAH es tener un cerebro con motor de Ferrari y frenos de bicicleta. Mi trabajo no es bajarte la potencia: es fortalecer los frenos — y entonces ganas carreras.", recursos: [{"titulo":"drhallowell.com — web oficial del Dr. Hallowell (recursos, Hallowell Centers)","url":"https://drhallowell.com/"},{"titulo":"Distraction Podcast — podcast oficial de Hallowell (canal de YouTube verificado)","url":"https://www.youtube.com/channel/UCnYKUlRjvi2TDSxzkw4eMyw"}] },
  14: { n: 14, frase: "No tenemos un déficit de atención; tenemos atención en abundancia. El reto no es prestar atención: es controlar a dónde se va.", recursos: [{"titulo":"'Driven, Distracted and Thriving with Dr. Ned Hallowell' — entrevista en video","url":"https://www.youtube.com/watch?v=2_oMiwW3SMY"},{"titulo":"Take Control ADHD #388 — 'Dr. Ned Hallowell on Self-Esteem, Human Connection, and Finding ","url":"https://takecontroladhd.com/podcast/388"}] },
  15: { n: 15, frase: "La vía más rápida para que un cerebro 'disperso' rinda no es arreglar a la persona: es rediseñar la tarea y el entorno para que encajen con su perfil ejecutivo.", recursos: [{"titulo":"smartbutscatteredkids.com — web oficial de Dawson & Guare (libros, recursos, artículos)","url":"https://www.smartbutscatteredkids.com/"},{"titulo":"'Best Practices in Assessing and Improving Executive Skills' — capítulo de Peg Dawson en l","url":"https://www.smartbutscatteredkids.com/wp-content/uploads/ExecutiveSkillsChapter.pdf"}] },
  16: { n: 16, frase: "Para mejorar tu vida sexual no necesitas pisar más el acelerador: necesitas quitarle presión a los frenos.", recursos: [{"titulo":"'The truth about unwanted arousal' — Emily Nagoski (TED 2018, sobre nonconcordance)","url":"https://www.ted.com/talks/emily_nagoski_the_truth_about_unwanted_arousal"},{"titulo":"El mismo TED talk en el canal de TED en YouTube","url":"https://www.youtube.com/watch?v=L-q-tSHo9Ho"}] },
  17: { n: 17, frase: "El amor busca cercanía, pero el deseo necesita distancia.", recursos: [{"titulo":"'The secret to desire in a long-term relationship' — Esther Perel (TED 2013, +20M vistas)","url":"https://www.ted.com/talks/esther_perel_the_secret_to_desire_in_a_long_term_relationship"},{"titulo":"El mismo TED talk en YouTube","url":"https://www.youtube.com/watch?v=zw9n6GkgHI4"}] },
  18: { n: 18, frase: "La paradoja de la dependencia: cuanto más eficazmente puedes depender de tu pareja, más independiente y atrevido te vuelves en el mundo.", recursos: [{"titulo":"attachedthebook.com — web oficial del libro (incluye test de estilo de apego)","url":"https://www.attachedthebook.com/wordpress/"},{"titulo":"'Can You Change Your Attachment Style? With Amir Levine' — podcast de Sabrina Zohar","url":"https://www.youtube.com/watch?v=Z5_kgxF-PQA"}] },
  19: { n: 19, frase: "Cuando la sexualidad va bien, es el 10% del matrimonio; cuando va mal, se convierte en el 90%.", recursos: [{"titulo":"'The sex-starved marriage | Michele Weiner-Davis | TEDxCU' (+5M vistas)","url":"https://www.youtube.com/watch?v=Ep2MAx95m20"},{"titulo":"divorcebusting.com — web oficial de Weiner-Davis (The Divorce Busting Center)","url":"https://www.divorcebusting.com"}] },
  20: { n: 20, frase: "Haz ofertas tan buenas que la gente se sienta estúpida diciendo que no.", recursos: [{"titulo":"Offers Course — Acquisition.com (curso gratis del libro, módulos: Picking Markets, Charge ","url":"https://www.acquisition.com/training/offers"},{"titulo":"Alex Hormozi — @AlexHormozi","url":"https://www.youtube.com/@AlexHormozi"}] },
  21: { n: 21, frase: "Regala los secretos, vende la implementación.", recursos: [{"titulo":"Leads Course — Acquisition.com (módulos: Lead Magnet Mastery, Cold Outreach Playbook, Paid","url":"https://www.acquisition.com/training/leads"},{"titulo":"Alex Hormozi — @AlexHormozi (el lanzamiento del libro en evento en vivo está subido al can","url":"https://www.youtube.com/@AlexHormozi"}] },
  22: { n: 22, frase: "El objetivo: que un cliente te deje suficiente dinero en treinta días para conseguir y atender al menos dos clientes más.", recursos: [{"titulo":"Money Models Course — Acquisition.com (curso gratis que acompaña el libro)","url":"https://www.acquisition.com/training/money"},{"titulo":"Alex Hormozi — @AlexHormozi (el evento de lanzamiento del libro, agosto 2025, está en el c","url":"https://www.youtube.com/@AlexHormozi"}] },
  23: { n: 23, frase: "La idea de una pérdida potencial juega un rol enorme en la decisión humana: la gente se motiva más por el pensamiento de perder algo que por el de ganar algo del mismo valor.", recursos: [{"titulo":"Science of Persuasion — animación oficial narrada por Cialdini y Steve Martin (canal influ","url":"https://www.youtube.com/watch?v=cFdCzN7RYbw"},{"titulo":"Influence at Work — sitio oficial de Cialdini (formación y keynotes)","url":"https://www.influenceatwork.com/"}] },
  24: { n: 24, frase: "Al final, el negocio que puede gastar más para adquirir un cliente, gana.", recursos: [{"titulo":"DotComSecrets.com — libro gratis + envío","url":"https://www.dotcomsecrets.com/"},{"titulo":"Russell Brunson — canal oficial","url":"https://www.youtube.com/@russellbrunson"}] },
  25: { n: 25, frase: "Si logro que la gente crea que (mi nueva oportunidad) es la clave para (lo que más desean) y que solo puede obtenerse a través de (mi vehículo específico), entonces todas las demás objeciones se…", recursos: [{"titulo":"ExpertSecrets.com — libro gratis + envío","url":"https://www.expertsecrets.com/"},{"titulo":"Russell Brunson — canal oficial (busca 'Perfect Webinar' dentro del canal)","url":"https://www.youtube.com/@russellbrunson"}] },
  26: { n: 26, frase: "El cliente es el héroe, no tu marca.", recursos: [{"titulo":"StoryBrand with Donald Miller — canal oficial","url":"https://www.youtube.com/@StoryBrand"},{"titulo":"How to clarify your message so people listen | Donald Miller | TEDxNashville","url":"https://www.youtube.com/watch?v=QRHCoU04Pe0"}] },
  27: { n: 27, frase: "El copy no puede crear el deseo por un producto. Solo puede tomar las esperanzas, los sueños, los miedos y los deseos que ya existen en los corazones de millones de personas, y enfocar esos deseos ya…", recursos: [{"titulo":"Breakthrough Advertising — publicado por Brian Kurtz (titanes del direct response, derecho","url":"https://breakthroughadvertisingbook.com/breakthrough-advertising/"},{"titulo":"Eugene Schwartz — Rare Speech on Advertising & Copywriting (seminario a Phillips Publishin","url":"https://www.hardtofindseminars.com/Eugene_Schwartz_Speech.htm"}] },
  28: { n: 28, frase: "La forma más sencilla de aprender con directness es simplemente invertir muchas horas en hacer aquello en lo que quieres llegar a ser bueno.", recursos: [{"titulo":"Can you get an MIT education for $2,000? | Scott Young | TEDxEastsidePrep","url":"https://www.youtube.com/watch?v=piSLobJfZ3c"},{"titulo":"Scott Young — canal oficial","url":"https://www.youtube.com/@ScottHYoungVid"}] },
};

/** frase del día (rota por fecha) — solo de libros con frase verificada */
export function fraseDelDia(iso: string): { frase: string; libro: number } | null {
  const all = Object.values(LIBROS_EXTRA).filter((x) => x.frase);
  if (!all.length) return null;
  const seed = parseInt(iso.replace(/-/g, ''), 10) % all.length;
  return { frase: all[seed].frase, libro: all[seed].n };
}
