/**
 * dermaCiclo2.ts — CICLO 2 de Dermatología · d74-d103 (30 sesiones · 2027-04-23 → 2027-07-14).
 * GENERADO por DATA/_scripts/gen_derma_ciclo2.js (2026-09-26) — NO editar a mano:
 *   `node DATA/_scripts/gen_derma_ciclo2.js [YYYY-MM-DD]` (sin fecha: primer día-Derma tras DERMA_DAILY_META.fin).
 *
 * Qué es: la continuación del PLAN ÉLITE tras el cierre del ciclo 1 (d73, 2027-04-21), en la MISMA franja
 * 13:30-14:15 interdiaria con Research (paridad researchData.ts#diaEstudioTipo; verificado 0 solapes con
 * researchDailyPlan.ts y researchDailyPlan2027.ts al generar) y con la MISMA clave de progreso 'derma' (numeración continua).
 *   · d74-d85: los 36 casos restantes de DERMA_CASO_ORDEN (posiciones 164-199) a 3/sesión → primera pasada de los 200 completa.
 *   · d86+: SEGUNDA PASADA FSRS — solo fallos del ledger (dermaCasosParaSegundaPasada), 0 casos nuevos.
 *   · review: Pictorial 3e (relevo) ⇄ Barnhill restante; QOTW/CORE restantes en los checkpoints; cursor "retoma en Q#" (dermaBancoCursor).
 *   · 1 módulo G+ (DERMA_GAP_MODULOS, dermaData.ts) por semana en el slot de lectura: G+1 d74 · G+2 d75 · G+3 d77 · G+4 d80 · G+5 d82 · G+6 d87 · G+7 d90 · G+8 d92 · G+9 d95.
 *   · 10Q ProMIR-Derma en d ≡ 0 mod 3 (10 slots = 10 capítulos por peso MIR, uno cada uno).
 *   · checkpoints: cp1 d85 (2027-05-25) · cp2 d94 (2027-06-18) · repaso2 d103 (2027-07-14).
 * Las filas usan la MISMA forma DiaDerma (+ ciclo/tipo/gplus) para que DermaTodayPlan las pinte sin cambios de tipo.
 */
import {
  DERMA_DIAS, DERMA_DAILY_META, DERMA_CASO_META, PROMIR_DERMA_CAPS, book, cases, qa, pm, LANGE_CASES_URL,
  type DiaDerma, type MatLink, type DermaCheckpointKey,
} from './dermaDailyPlan';
import { DERMA_GAP_MODULOS, type DermaGapModulo } from './dermaData';

export type DermaCiclo2Tipo = 'casos' | 'fsrs' | 'checkpoint';
export interface DiaDermaCiclo2 extends DiaDerma {
  ciclo: 2;
  tipo: DermaCiclo2Tipo;   // 'casos' = 3 casos nuevos · 'fsrs' = solo fallos del ledger · 'checkpoint'
  gplus?: string;          // id del módulo G+ (DERMA_GAP_MODULOS) que ocupa el slot de lectura esa semana
}

export const DERMA_CICLO2_META = {
  inicio: '2027-04-23', fin: '2027-07-14', totalDias: 30, // ciclo 2 · D74=Vie 2027-04-23 · alterna con Research · sáb+dom libres · generado 2026-09-26
  ciclo: 2 as const,
  dOffset: 73,
  casosRestantes: 36, sesionesConCasos: 12, casosPorSesion: 3,
  bloque: '13:30–14:15 (45 min · franja boards del Calendar, alterna con Research — interdiario)',
  nota: 'CICLO 2: 36 casos restantes a 3/sesión (d74-d85) → después solo segunda pasada FSRS de fallos; review Pictorial 3e ⇄ Barnhill retomando en el Q# del cursor; 1 módulo G+ por semana en el slot de lectura; 10Q ProMIR en d ≡ 0 mod 3.',
};

// ── links (mismos ids reales que dermaDailyPlan.ts) ──
const MH2 = 'https://dermatology.mhmedical.com';
const DN2 = 'https://dermnetnz.org';
const IMG_LIB2 = `${DN2}/image-library`;
const DN_QUIZ2 = `${DN2}/cme/dermoscopy-quizzes`;
const ABD_GUIDE2 = 'https://dlpgnf31z4a6s.cloudfront.net/media/252836/core-study-guide-012021.pdf';
const rPIC3b: MatLink = { t: 'Pictorial Review 3e · ~10Q (de 363) — retoma en el Q# del cursor', url: qa(2948) };
const rBARN2: MatLink = { t: "Barnhill's Challenge · ~10Q dermpath (de 403) — retoma en el Q# del cursor", url: qa(2865) };
const rCORE2: MatLink = { t: 'CORE Exam Bank · las ~10Q que quedan (de 104)', url: qa(3479) };
const rQOTW2: MatLink = { t: 'Question of the Week · las que quedan del archivo (50Q)', url: qa(3562) };
export const rLANGE2: MatLink = { t: 'LANGE Clinical Dermatology Cases · si sobra tiempo (48Q)', url: LANGE_CASES_URL };
const CASO2: MatLink = { t: 'Cases for Board Review · 3 casos CIEGOS (los restantes de la permutación fija)', url: cases(1546) };
const CASO_DD2: MatLink = { t: 'Differential Diagnosis Challenge · pares de diferencial (100 sets)', url: cases(1616) };
const CASO_FALLOS2: MatLink = { t: 'Board Review · SOLO casos fallados del ledger (segunda pasada FSRS)', url: cases(1546) };
const DSA2 = book(2929); // Dermoscopy: Illustrated Self-Assessment 2e (impares)
const DS2 = 'https://dermoscopedia.org';
const DSP2 = {
  red: `${DS2}/Pigment_network`, glob: `${DS2}/Globules`, streaks: `${DS2}/Streaks`, veil: `${DS2}/Blue-white_veil`,
  vasos: `${DS2}/Vascular_structures`, neg: `${DS2}/Negative_network`, dots: `${DS2}/Dots`, struct: `${DS2}/Structureless_areas`,
  chaos: `${DS2}/Chaos_and_clues`, twoStep: `${DS2}/Two-step_algorithm`, three: `${DS2}/Three_point_checklist`,
  seven: `${DS2}/Seven_Point_Checklist`, menzies: `${DS2}/Menzies_Method`, abcd: `${DS2}/ABCD_rule`, pattern: `${DS2}/Pattern_analysis`,
} as const;
const PMD2 = (n: number): MatLink => { const c = PROMIR_DERMA_CAPS[n - 1]; return { t: `ProMIR Derma · cap ${c.n} ${c.t} · TEST 10Q (peso MIR ${c.peso} %)`, url: pm(c.capId) }; };
/** URL del módulo G+ (dermaData.ts); si el id no existe, home de la biblioteca AccessDerma. */
const gplusUrl = (id: string): string => DERMA_GAP_MODULOS.find((g) => g.id === id)?.url || `${MH2}/books.aspx?view=library`;
void MH2;

export const DERMA_DIAS_CICLO2: DiaDermaCiclo2[] = [
  { d: 74, fecha: '2027-04-23', ciclo: 2, tipo: 'casos', bloque: 'Ciclo 2 · G+1 enriquecimiento', bKey: 'B', tier: 'ALTA', sub: 'CICLO 2 · Casos 1-3 de los 36 restantes (3 casos ciegos, primera pasada) + review + lectura G+: Dermatitis de contacto + patch testing', referente: null, access: CASO2, qbankly: rPIC3b, promir: null, extra: { t: 'G+1 · Dermatitis de contacto + patch testing', url: gplusUrl('G+1') }, casoIds: [93, 80, 140], ddx: ['3 casos ciegos: ① 8 ejes ② diferencial de 3 ③ viñeta ④ discusión → tarjetas de MECANISMO', 'Los ~10Q son la variable de ajuste (retoma en el Q# del cursor)', 'Cura pendiente del ledger (CCSN → DD Challenge) ANTES del primer caso si la hay'], atlasUrl: gplusUrl('G+1'), dermatoscopiaImg: DSP2.red, gplus: 'G+1' },
  { d: 75, fecha: '2027-04-27', ciclo: 2, tipo: 'casos', bloque: 'Ciclo 2 · G+2 enriquecimiento', bKey: 'B', tier: 'ALTA', sub: 'CICLO 2 · Casos 4-6 de los 36 restantes (3 casos ciegos, primera pasada) + review + lectura G+: Fototerapia: nbUVB / PUVA / excimer', referente: null, access: CASO2, qbankly: rBARN2, promir: PMD2(4), extra: { t: 'G+2 · Fototerapia: nbUVB / PUVA / excimer', url: gplusUrl('G+2') }, casoIds: [5, 52, 1], ddx: ['3 casos ciegos: ① 8 ejes ② diferencial de 3 ③ viñeta ④ discusión → tarjetas de MECANISMO', 'Los ~10Q son la variable de ajuste (retoma en el Q# del cursor)', 'Cura pendiente del ledger (CCSN → DD Challenge) ANTES del primer caso si la hay'], atlasUrl: gplusUrl('G+2'), dermatoscopiaImg: DSA2, gplus: 'G+2' },
  { d: 76, fecha: '2027-04-29', ciclo: 2, tipo: 'casos', bloque: 'Ciclo 2 · casos restantes (primera pasada)', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Casos 7-9 de los 36 restantes (3 casos ciegos, primera pasada) + review', referente: null, access: CASO2, qbankly: rPIC3b, promir: null, extra: { t: 'Si fallas el caso, lee aquí 10′: Fitzpatrick\'s Color Atlas 9e (sección del diagnóstico)', url: book(3309) }, casoIds: [152, 4, 161], morfologia: 'Interleaving', sitio: 'Difuso', ddx: ['3 casos ciegos: ① 8 ejes ② diferencial de 3 ③ viñeta ④ discusión → tarjetas de MECANISMO', 'Los ~10Q son la variable de ajuste (retoma en el Q# del cursor)', 'Cura pendiente del ledger (CCSN → DD Challenge) ANTES del primer caso si la hay'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSP2.glob },
  { d: 77, fecha: '2027-05-03', ciclo: 2, tipo: 'casos', bloque: 'Ciclo 2 · G+3 enriquecimiento', bKey: 'B', tier: 'ALTA', sub: 'CICLO 2 · Casos 10-12 de los 36 restantes (3 casos ciegos, primera pasada) + review + lectura G+: Granulomatosas y por depósito', referente: null, access: CASO2, qbankly: rBARN2, promir: null, extra: { t: 'G+3 · Granulomatosas y por depósito', url: gplusUrl('G+3') }, casoIds: [78, 10, 24], ddx: ['3 casos ciegos: ① 8 ejes ② diferencial de 3 ③ viñeta ④ discusión → tarjetas de MECANISMO', 'Los ~10Q son la variable de ajuste (retoma en el Q# del cursor)', 'Cura pendiente del ledger (CCSN → DD Challenge) ANTES del primer caso si la hay'], atlasUrl: gplusUrl('G+3'), dermatoscopiaImg: DSA2, gplus: 'G+3' },
  { d: 78, fecha: '2027-05-05', ciclo: 2, tipo: 'casos', bloque: 'Ciclo 2 · casos restantes (primera pasada)', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Casos 13-15 de los 36 restantes (3 casos ciegos, primera pasada) + review', referente: null, access: CASO2, qbankly: rPIC3b, promir: PMD2(2), extra: { t: 'Si fallas el caso, lee aquí 10′: Fitzpatrick\'s Color Atlas 9e (sección del diagnóstico)', url: book(3309) }, casoIds: [85, 193, 118], morfologia: 'Interleaving', sitio: 'Difuso', ddx: ['3 casos ciegos: ① 8 ejes ② diferencial de 3 ③ viñeta ④ discusión → tarjetas de MECANISMO', 'Los ~10Q son la variable de ajuste (retoma en el Q# del cursor)', 'Cura pendiente del ledger (CCSN → DD Challenge) ANTES del primer caso si la hay'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSP2.streaks },
  { d: 79, fecha: '2027-05-07', ciclo: 2, tipo: 'casos', bloque: 'Ciclo 2 · casos restantes (primera pasada)', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Casos 16-18 de los 36 restantes (3 casos ciegos, primera pasada) + review', referente: null, access: CASO2, qbankly: rBARN2, promir: null, extra: { t: 'Si fallas el caso, lee aquí 10′: Fitzpatrick\'s Color Atlas 9e (sección del diagnóstico)', url: book(3309) }, casoIds: [56, 26, 132], morfologia: 'Interleaving', sitio: 'Difuso', ddx: ['3 casos ciegos: ① 8 ejes ② diferencial de 3 ③ viñeta ④ discusión → tarjetas de MECANISMO', 'Los ~10Q son la variable de ajuste (retoma en el Q# del cursor)', 'Cura pendiente del ledger (CCSN → DD Challenge) ANTES del primer caso si la hay'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSA2 },
  { d: 80, fecha: '2027-05-11', ciclo: 2, tipo: 'casos', bloque: 'Ciclo 2 · G+4 enriquecimiento', bKey: 'B', tier: 'ALTA', sub: 'CICLO 2 · Casos 19-21 de los 36 restantes (3 casos ciegos, primera pasada) + review + lectura G+: Dermatosis del embarazo + inmunodeprimido / VIH / trasplante', referente: null, access: CASO2, qbankly: rPIC3b, promir: null, extra: { t: 'G+4 · Dermatosis del embarazo + inmunodeprimido / VIH / trasplante', url: gplusUrl('G+4') }, casoIds: [116, 160, 94], ddx: ['3 casos ciegos: ① 8 ejes ② diferencial de 3 ③ viñeta ④ discusión → tarjetas de MECANISMO', 'Los ~10Q son la variable de ajuste (retoma en el Q# del cursor)', 'Cura pendiente del ledger (CCSN → DD Challenge) ANTES del primer caso si la hay'], atlasUrl: gplusUrl('G+4'), dermatoscopiaImg: DSP2.veil, gplus: 'G+4' },
  { d: 81, fecha: '2027-05-13', ciclo: 2, tipo: 'casos', bloque: 'Ciclo 2 · casos restantes (primera pasada)', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Casos 22-24 de los 36 restantes (3 casos ciegos, primera pasada) + review', referente: null, access: CASO2, qbankly: rBARN2, promir: PMD2(3), extra: { t: 'Si fallas el caso, lee aquí 10′: Fitzpatrick\'s Color Atlas 9e (sección del diagnóstico)', url: book(3309) }, casoIds: [111, 117, 15], morfologia: 'Interleaving', sitio: 'Difuso', ddx: ['3 casos ciegos: ① 8 ejes ② diferencial de 3 ③ viñeta ④ discusión → tarjetas de MECANISMO', 'Los ~10Q son la variable de ajuste (retoma en el Q# del cursor)', 'Cura pendiente del ledger (CCSN → DD Challenge) ANTES del primer caso si la hay'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSA2 },
  { d: 82, fecha: '2027-05-17', ciclo: 2, tipo: 'casos', bloque: 'Ciclo 2 · G+5 enriquecimiento', bKey: 'B', tier: 'ALTA', sub: 'CICLO 2 · Casos 25-27 de los 36 restantes (3 casos ciegos, primera pasada) + review + lectura G+: Enfermedad mucosa oral y genital', referente: null, access: CASO2, qbankly: rPIC3b, promir: null, extra: { t: 'G+5 · Enfermedad mucosa oral y genital', url: gplusUrl('G+5') }, casoIds: [13, 75, 98], ddx: ['3 casos ciegos: ① 8 ejes ② diferencial de 3 ③ viñeta ④ discusión → tarjetas de MECANISMO', 'Los ~10Q son la variable de ajuste (retoma en el Q# del cursor)', 'Cura pendiente del ledger (CCSN → DD Challenge) ANTES del primer caso si la hay'], atlasUrl: gplusUrl('G+5'), dermatoscopiaImg: DSP2.vasos, gplus: 'G+5' },
  { d: 83, fecha: '2027-05-19', ciclo: 2, tipo: 'casos', bloque: 'Ciclo 2 · casos restantes (primera pasada)', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Casos 28-30 de los 36 restantes (3 casos ciegos, primera pasada) + review', referente: null, access: CASO2, qbankly: rBARN2, promir: null, extra: { t: 'Si fallas el caso, lee aquí 10′: Fitzpatrick\'s Color Atlas 9e (sección del diagnóstico)', url: book(3309) }, casoIds: [120, 137, 83], morfologia: 'Interleaving', sitio: 'Difuso', ddx: ['3 casos ciegos: ① 8 ejes ② diferencial de 3 ③ viñeta ④ discusión → tarjetas de MECANISMO', 'Los ~10Q son la variable de ajuste (retoma en el Q# del cursor)', 'Cura pendiente del ledger (CCSN → DD Challenge) ANTES del primer caso si la hay'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSA2 },
  { d: 84, fecha: '2027-05-21', ciclo: 2, tipo: 'casos', bloque: 'Ciclo 2 · casos restantes (primera pasada)', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Casos 31-33 de los 36 restantes (3 casos ciegos, primera pasada) + review', referente: null, access: CASO2, qbankly: rPIC3b, promir: PMD2(1), extra: { t: 'Si fallas el caso, lee aquí 10′: Fitzpatrick\'s Color Atlas 9e (sección del diagnóstico)', url: book(3309) }, casoIds: [100, 37, 22], morfologia: 'Interleaving', sitio: 'Difuso', ddx: ['3 casos ciegos: ① 8 ejes ② diferencial de 3 ③ viñeta ④ discusión → tarjetas de MECANISMO', 'Los ~10Q son la variable de ajuste (retoma en el Q# del cursor)', 'Cura pendiente del ledger (CCSN → DD Challenge) ANTES del primer caso si la hay'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSP2.neg },
  { d: 85, fecha: '2027-05-25', ciclo: 2, tipo: 'checkpoint', bloque: 'Ciclo 2 · checkpoint', bKey: 'H', tier: 'ALTA', sub: 'CICLO 2 · Checkpoint 1: fin de la PRIMERA PASADA de los 200 casos → mapa de fallos por módulo CORE (ledger) y por bloque A-X; qué re-drillear en la segunda pasada', referente: null, access: CASO_DD2, qbankly: rQOTW2, promir: null, extra: { t: 'ABD CORE Study Guide (PDF oficial)', url: ABD_GUIDE2 }, casoIds: [125, 153, 79], morfologia: 'Mapa de fallos', sitio: 'Difuso', ddx: ['% fallo por área del ledger tras 200 casos: Med (110) · Path (30) · Peds (30) · Surg (30)', 'Tipo de error dominante (CCSN/CONCEPTO/MORFOLOGIA/DDX) → cura de DERMA_CURA_LINK', 'Cursor de cada banco (dermaBancoCursores): qué queda de Pictorial 3e / Barnhill'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSA2, checkpoint: 'cp1' },
  { d: 86, fecha: '2027-05-27', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · segunda pasada FSRS', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos)', referente: null, access: CASO_FALLOS2, qbankly: rBARN2, promir: null, extra: null, casoIds: [], morfologia: 'Repaso', sitio: 'Difuso', ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSP2.dots },
  { d: 87, fecha: '2027-05-31', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · G+6 enriquecimiento', bKey: 'F', tier: 'ALTA', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos) + lectura G+: Anomalías vasculares pediátricas (ISSVA) + marcas de nacimiento', referente: null, access: CASO_FALLOS2, qbankly: rPIC3b, promir: PMD2(5), extra: { t: 'G+6 · Anomalías vasculares pediátricas (ISSVA) + marcas de nacimiento', url: gplusUrl('G+6') }, casoIds: [], ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: gplusUrl('G+6'), dermatoscopiaImg: DSA2, gplus: 'G+6' },
  { d: 88, fecha: '2027-06-02', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · segunda pasada FSRS', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos)', referente: null, access: CASO_FALLOS2, qbankly: rBARN2, promir: null, extra: null, casoIds: [], morfologia: 'Repaso', sitio: 'Difuso', ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSP2.struct },
  { d: 89, fecha: '2027-06-04', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · segunda pasada FSRS', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos)', referente: null, access: CASO_FALLOS2, qbankly: rPIC3b, promir: null, extra: null, casoIds: [], morfologia: 'Repaso', sitio: 'Difuso', ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSA2 },
  { d: 90, fecha: '2027-06-08', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · G+7 enriquecimiento', bKey: 'D', tier: 'ALTA', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos) + lectura G+: Dermatoscopia élite: algoritmos como unidad entrenable', referente: null, access: CASO_FALLOS2, qbankly: rBARN2, promir: PMD2(8), extra: { t: 'G+7 · Dermatoscopia élite: algoritmos como unidad entrenable', url: gplusUrl('G+7') }, casoIds: [], ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: gplusUrl('G+7'), dermatoscopiaImg: DSP2.chaos, gplus: 'G+7' },
  { d: 91, fecha: '2027-06-10', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · segunda pasada FSRS', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos)', referente: null, access: CASO_FALLOS2, qbankly: rPIC3b, promir: null, extra: null, casoIds: [], morfologia: 'Repaso', sitio: 'Difuso', ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSA2 },
  { d: 92, fecha: '2027-06-14', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · G+8 enriquecimiento', bKey: 'B', tier: 'ALTA', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos) + lectura G+: Terapéutica 2024-2025 sistematizada (JAK · IL-13/17/23 · black-box)', referente: null, access: CASO_FALLOS2, qbankly: rBARN2, promir: null, extra: { t: 'G+8 · Terapéutica 2024-2025 sistematizada (JAK · IL-13/17/23 · black-box)', url: gplusUrl('G+8') }, casoIds: [], ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: gplusUrl('G+8'), dermatoscopiaImg: DSP2.twoStep, gplus: 'G+8' },
  { d: 93, fecha: '2027-06-16', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · segunda pasada FSRS', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos)', referente: null, access: CASO_FALLOS2, qbankly: rPIC3b, promir: PMD2(6), extra: null, casoIds: [], morfologia: 'Repaso', sitio: 'Difuso', ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSA2 },
  { d: 94, fecha: '2027-06-18', ciclo: 2, tipo: 'checkpoint', bloque: 'Ciclo 2 · checkpoint', bKey: 'H', tier: 'ALTA', sub: 'CICLO 2 · Checkpoint 2: re-drill de fallos etiquetados + pares del DD Challenge de las 2 áreas flojas + drill oclusión vascular 90 s (cronometrado)', referente: null, access: CASO_DD2, qbankly: rCORE2, promir: null, extra: { t: 'Guidebook to Dermatologic Diagnosis (repaso)', url: book(2960) }, casoIds: [], morfologia: 'Mapa de fallos', sitio: 'Difuso', ddx: ['Pares del DD Challenge de las 2 áreas con mayor % fallo (dermaAreasFlojas)', 'Re-drill FSRS de los casos fallados (dermaCasosParaSegundaPasada)', 'Drill HDPH cronometrado: signos → dosis → intervalos → ceguera → oftalmología'], atlasUrl: DN_QUIZ2, dermatoscopiaImg: DSP2.three, checkpoint: 'cp2', drillHDPH: true },
  { d: 95, fecha: '2027-06-22', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · G+9 enriquecimiento', bKey: 'X', tier: 'ALTA', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos) + lectura G+: Cosmecéuticos basados en evidencia (retinoides · vit C · niacinamida)', referente: null, access: CASO_FALLOS2, qbankly: rBARN2, promir: null, extra: { t: 'G+9 · Cosmecéuticos basados en evidencia (retinoides · vit C · niacinamida)', url: gplusUrl('G+9') }, casoIds: [], ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: gplusUrl('G+9'), dermatoscopiaImg: DSA2, gplus: 'G+9' },
  { d: 96, fecha: '2027-06-24', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · segunda pasada FSRS', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos)', referente: null, access: CASO_FALLOS2, qbankly: rPIC3b, promir: PMD2(7), extra: null, casoIds: [], morfologia: 'Repaso', sitio: 'Difuso', ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSP2.seven },
  { d: 97, fecha: '2027-06-28', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · segunda pasada FSRS', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos)', referente: null, access: CASO_FALLOS2, qbankly: rBARN2, promir: null, extra: null, casoIds: [], morfologia: 'Repaso', sitio: 'Difuso', ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSA2 },
  { d: 98, fecha: '2027-06-30', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · segunda pasada FSRS', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos)', referente: null, access: CASO_FALLOS2, qbankly: rPIC3b, promir: null, extra: null, casoIds: [], morfologia: 'Repaso', sitio: 'Difuso', ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSP2.menzies },
  { d: 99, fecha: '2027-07-02', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · segunda pasada FSRS', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos)', referente: null, access: CASO_FALLOS2, qbankly: rBARN2, promir: PMD2(9), extra: null, casoIds: [], morfologia: 'Repaso', sitio: 'Difuso', ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSA2 },
  { d: 100, fecha: '2027-07-06', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · segunda pasada FSRS', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos)', referente: null, access: CASO_FALLOS2, qbankly: rPIC3b, promir: null, extra: null, casoIds: [], morfologia: 'Repaso', sitio: 'Difuso', ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSP2.abcd },
  { d: 101, fecha: '2027-07-08', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · segunda pasada FSRS', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos)', referente: null, access: CASO_FALLOS2, qbankly: rBARN2, promir: null, extra: null, casoIds: [], morfologia: 'Repaso', sitio: 'Difuso', ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSA2 },
  { d: 102, fecha: '2027-07-12', ciclo: 2, tipo: 'fsrs', bloque: 'Ciclo 2 · segunda pasada FSRS', bKey: 'Z', tier: 'MED', sub: 'CICLO 2 · Segunda pasada FSRS: SOLO casos y preguntas fallados del ledger, por módulo CORE más flojo (0 casos nuevos)', referente: null, access: CASO_FALLOS2, qbankly: rPIC3b, promir: PMD2(10), extra: null, casoIds: [], morfologia: 'Repaso', sitio: 'Difuso', ddx: ['SOLO fallos del ledger (dermaCasosParaSegundaPasada) — un caso resuelto con "Lo sabía" sale de la lista', 'Re-describir los 8 ejes antes de reabrir la discusión', 'Review del banco rotante retomando en su Q# (dermaBancoCursor)'], atlasUrl: IMG_LIB2, dermatoscopiaImg: DSP2.pattern },
  { d: 103, fecha: '2027-07-14', ciclo: 2, tipo: 'checkpoint', bloque: 'Ciclo 2 · checkpoint', bKey: 'H', tier: 'ALTA', sub: 'CICLO 2 · REPASO FINAL: mapa final de debilidades (export JSON → _registro_derma.json) + drill HDPH 90 s + plan de la fase práctica 2027 (dermatoscopio, Nítida, fellowship)', referente: null, access: CASO_DD2, qbankly: rQOTW2, promir: null, extra: { t: 'ABD CORE Study Guide (PDF oficial)', url: ABD_GUIDE2 }, casoIds: [], morfologia: 'Repaso', sitio: 'Difuso', ddx: ['Mapa final por módulo CORE y por bloque A-X (dermaLedgerExportJSON)', 'Drill HDPH 90 s final: recitar sin mirar', 'Siguiente: fase práctica (RUTA_FELLOWSHIP_ESTETICO.md · NITIDA_PROTOCOLOS.md)'], atlasUrl: DN_QUIZ2, dermatoscopiaImg: DSA2, checkpoint: 'repaso2', drillHDPH: true },
];

// ── helpers ──
/** Módulo G+ de la sesión (slot de lectura de la primera sesión Derma de cada semana). */
export function dermaGplusDe(dia: Pick<DiaDermaCiclo2, 'gplus'> | DiaDerma): DermaGapModulo | undefined {
  const id = (dia as DiaDermaCiclo2).gplus; return id ? DERMA_GAP_MODULOS.find((g) => g.id === id) : undefined;
}
/** G+ id → d del ciclo 2. */
export const DERMA_CICLO2_GPLUS_DIAS: Record<string, number> = { 'G+1': 74, 'G+2': 75, 'G+3': 77, 'G+4': 80, 'G+5': 82, 'G+6': 87, 'G+7': 90, 'G+8': 92, 'G+9': 95 };
/** Checkpoints del ciclo 2 por clave. */
export const DERMA_CICLO2_CHECKPOINTS: Partial<Record<DermaCheckpointKey, number>> = { cp1: 85, cp2: 94, repaso2: 103 };
export const DERMA_CICLO2_DRILL_DIAS: number[] = DERMA_DIAS_CICLO2.filter((x) => !!x.drillHDPH).map((x) => x.d);
export const DERMA_CICLO2_PROMIR_DIAS: number[] = DERMA_DIAS_CICLO2.filter((x) => !!x.promir).map((x) => x.d);
/** Los dos ciclos en una sola lista (numeración continua d1-d103; clave de progreso 'derma'). */
export const DERMA_DIAS_TODOS: DiaDerma[] = [...DERMA_DIAS, ...DERMA_DIAS_CICLO2];
export const DERMA_TOTAL_DIAS_TODOS = DERMA_DAILY_META.totalDias + DERMA_CICLO2_META.totalDias;
/** Ciclo al que pertenece un d (1 | 2 | undefined si fuera de rango). */
export function dermaCicloDe(d: number): 1 | 2 | undefined {
  if (d >= 1 && d <= DERMA_DAILY_META.totalDias) return 1;
  if (d > DERMA_CICLO2_META.dOffset && d <= DERMA_CICLO2_META.dOffset + DERMA_CICLO2_META.totalDias) return 2;
  return undefined;
}
/** Fila por d en cualquiera de los dos ciclos. */
export function dermaDiaPorD(d: number): DiaDerma | undefined {
  return DERMA_DIAS.find((x) => x.d === d) || DERMA_DIAS_CICLO2.find((x) => x.d === d);
}
/** dermaDiaDe con FALLBACK al ciclo 2: la fila cuya fecha es fechaISO, buscando primero en el ciclo 1. */
export function dermaDiaDeConCiclo2(fechaISO: string): DiaDerma | undefined {
  return DERMA_DIAS.find((x) => x.fecha === fechaISO) || DERMA_DIAS_CICLO2.find((x) => x.fecha === fechaISO);
}
/** Ventana de 7 sesiones a partir de fromD, cruzando ciclos. */
export function dermaVentana7Todos(fromD: number): DiaDerma[] { return DERMA_DIAS_TODOS.filter((x) => x.d >= fromD && x.d < fromD + 7); }
/** Nº de casos nuevos de una sesión del ciclo 2 (3 en d74-d85, 0 después). */
export const dermaCasosPorSesionCiclo2 = (d: number): number => d > DERMA_CICLO2_META.dOffset && d <= DERMA_CICLO2_META.dOffset + DERMA_CICLO2_META.sesionesConCasos ? DERMA_CICLO2_META.casosPorSesion : 0;
void DERMA_CASO_META;
