/**
 * researchDailyPlan2027.ts — Plan DÍA A DÍA de Research · CICLO 2 (SR-1 completa: PROSPERO → SUBMIT, con revisor humano #2).
 * GENERADO por DATA/_scripts/gen_research_plan.js (2026-09-05) — NO editar a mano: `node DATA/_scripts/gen_research_plan.js [YYYY-MM-DD]` (`--ciclo 2 YYYY-MM-DD` para re-fechar solo este ciclo)
 *
 * 67 átomos · d43-d109 (numeración continúa la del ciclo 1 → una sola clave de progreso 'research') ·
 * D1 = Vie 2027-02-05 → fin Mar 2027-08-10 · interdiario con Derma · sáb+dom libres.
 * Arranca tras el Step 1 (RUTA §6: M6-7 protocolo + PROSPERO · M8-10 ejecutar SR · M11-12 someter + balance).
 * R18 (cribado), R20 (κ) y R24 (extracción) EXIGEN revisor humano #2 con cuenta Rayyan y κ real; el equipo de
 * revisión (L4 §9) se copia a PROSPERO en R10. (CR-9 = submit del case report #1 y X-8 son d41-d42 del CICLO 1, los dos
 * primeros días-Research tras la pausa.) Incluye campaña K1-K2, case report #2,
 * bibliométrico B1-B5 y apertura de SR-2 (L5). Fuente única: DATA/_scripts/gen_research_plan.js.
 */
import type { DiaResearch } from './researchDailyPlan';

export const DAILY_META_2027 = {
  inicio: '2027-02-05', fin: '2027-08-10', totalDias: 67, // ciclo 2 · D1=Vie 2027-02-05 · alterna con Derma · sáb+dom libres
  ciclo: 2 as const,
  dOffset: 42,
  bloque: '13:30–14:15 (boards · alterna con Derma) · 1 átomo-research por día-Research',
  artefacto: 'SR-1 · Complicaciones vasculares de fillers + tiempo-a-tratamiento (Línea 4 · Mayo 38/40) registrada en PROSPERO y ENVIADA · case report #1 y #2 enviados · bibliométrico · SR-2 abierta',
};

export const DIAS_2027: DiaResearch[] = [
  // R1 · Pregunta & protocolo
  { d: 43, fecha: '2027-02-05', ciclo: 2, fase: 'R1', pista: 'R', code: 'R6b', prioridad: 'CRITICA', objetivo: 'PICO de SR-1 REVALIDADO tras Derma d19-20 (oclusión vascular / HDPH): ajustar desenlaces (recuperación cutánea o visual, tiempo-a-hialuronidasa, dosis) y criterios PICOS v2', entregable: 'PICO + PICOS v2 congelables', artefacto: 'L4 §2-3 v2 + vault 01_protocolo_PICO', tool: '—', recs: ['DELO', 'COCHB'], chips: ['requiere Derma d19-20 (oclusión vascular)'], apex: null },
  { d: 44, fecha: '2027-02-09', ciclo: 2, fase: 'R1', pista: 'R', code: 'R8b', prioridad: 'CRITICA', objetivo: 'Protocolo PRISMA-P COMPLETO (17 ítems): rellenar los [PROTOCOL GAP] del v0; selección con 2 revisores independientes, extracción doble, ROBINS-I / JBI, síntesis (proporciones o narrativa)', entregable: 'Protocolo v1 completo', artefacto: 'vault 01_protocolo_PICO/protocolo_PRISMA-P_v1.md', tool: '—', recs: ['PRISMA', 'COCHB', 'TOP'], apex: null },
  // R2 · Registro PROSPERO
  { d: 45, fecha: '2027-02-11', ciclo: 2, fase: 'R2', pista: 'R', code: 'X-9', prioridad: 'CRITICA', objetivo: 'EQUIPO DE REVISIÓN confirmado para PROSPERO: revisor #2 con cuenta Rayyan, ORCID de todos, afiliaciones, roles (garante, contacto, cribadores, extractores, estadístico), conflictos de interés, fechas previstas', entregable: 'L4 §9 completo — se copia tal cual a PROSPERO', artefacto: 'lines/L4-complicaciones.md §9 + MENTORES.md', tool: 'Rayyan · ORCID', recs: ['PROS', 'RAY', 'ORCID', 'CREDIT'], apex: null },
  // R1 · Pregunta & protocolo
  { d: 46, fecha: '2027-02-15', ciclo: 2, fase: 'R1', pista: 'R', code: 'R9b', prioridad: 'ALTA', objetivo: 'Duplicidad final: re-buscar en PROSPERO + PubMed registros y SR nuevos desde dic-2026; confirmar el ángulo diferencial (tiempo-a-tratamiento + LATAM)', entregable: 'Decisión final escrita en L4 §6', artefacto: 'lines/L4-complicaciones.md §6', tool: 'PROSPERO · PubMed', recs: ['PROS', 'PM'], apex: null },
  // R2 · Registro PROSPERO
  { d: 47, fecha: '2027-02-17', ciclo: 2, fase: 'R2', pista: 'R', code: 'R10', prioridad: 'CRITICA', objetivo: 'PROSPERO: rellenar el formulario completo (campos obligatorios, equipo de revisión de L4 §9, fechas previstas, conflictos, fuentes) y ENVIAR', entregable: 'Registro PROSPERO de SR-1 ENVIADO · estado PROSPERO-SR1 → enviado', artefacto: 'PDF del registro + Mesa editorial', tool: 'PROSPERO', recs: ['PROS'], apex: { id: 'prospero', t: 'SR-1 registrada (CRD)' } },
  // K · Campaña de colaboradores
  { d: 48, fecha: '2027-02-19', ciclo: 2, fase: 'K', pista: 'K', code: 'K1', prioridad: 'ALTA', objetivo: 'Campaña de cold emails 1/2: enviar 10 correos hiperpersonalizados de la lista de diciembre (oferta concreta: cribado PRISMA / extracción / draft) + registrar en MENTORES.md', entregable: '10 emails enviados + tabla de seguimiento', artefacto: 'MENTORES.md §Campaña', tool: 'Email', recs: ['PHRASE', 'ICMJE'], apex: null },
  // R2 · Registro PROSPERO
  { d: 49, fecha: '2027-02-23', ciclo: 2, fase: 'R2', pista: 'R', code: 'R11', prioridad: 'MEDIA', objetivo: 'Plan B si PROSPERO no encaja (scoping → OSF Registries) + esperar el CRD; protocolo congelado (v1 con fecha) en OSF', entregable: 'CRD recibido o registro OSF; protocolo congelado', artefacto: 'OSF + vault 01_protocolo_PICO', tool: 'OSF', recs: ['PROS', 'OSF', 'TOP'], apex: null },
  // K · Campaña de colaboradores
  { d: 50, fecha: '2027-02-25', ciclo: 2, fase: 'K', pista: 'K', code: 'K2', prioridad: 'MEDIA', objetivo: 'Campaña de cold emails 2/2: 10-20 correos restantes + seguimiento a los sin respuesta (1 recordatorio a los 10 días) + DIGA (comité IMG) y Skin of Color Society', entregable: 'Campaña completa (20-30) + respuestas registradas + ≥1 colaborador para SR-1', artefacto: 'MENTORES.md §Campaña', tool: 'Email', recs: ['PHRASE'], apex: null },
  // R3 · Búsqueda N bases
  { d: 51, fecha: '2027-03-01', ciclo: 2, fase: 'R3', pista: 'R', code: 'R12', prioridad: 'CRITICA', objetivo: 'Estrategia maestra: OpenAlex (troncal, booleana) + MeSH en MEDLINE/PubMed (líneas numeradas) — la query PRISMA-S final', entregable: 'Query OpenAlex + sintaxis PubMed numerada', artefacto: 'vault 02_busqueda/query_v1.md', tool: 'OpenAlex · PubMed', recs: ['OPENALEX', 'NLM1', 'PM'], apex: { id: 'mesh', t: 'Query OpenAlex + MeSH' } },
  { d: 52, fecha: '2027-03-03', ciclo: 2, fase: 'R3', pista: 'R', code: 'R13', prioridad: 'ALTA', objetivo: 'Trasladar la query a Europe PMC + CENTRAL + Semantic Scholar (5 fuentes)', entregable: 'Sintaxis + nº de resultados por fuente', artefacto: 'vault 02_busqueda/fuentes.md', tool: 'Europe PMC · S2', recs: ['EPMC', 'CENT', 'SEMSCH'], apex: null },
  { d: 53, fecha: '2027-03-05', ciclo: 2, fase: 'R3', pista: 'R', code: 'R14', prioridad: 'ALTA', objetivo: 'LILACS/BVS (DeCS · ventaja LATAM) + ClinicalTrials.gov + ICTRP', entregable: 'Búsquedas anotadas con nº de resultados', artefacto: 'vault 02_busqueda/fuentes.md', tool: 'LILACS · CT.gov', recs: ['LILACS', 'CT', 'ICTRP'], apex: null },
  { d: 54, fecha: '2027-03-09', ciclo: 2, fase: 'R3', pista: 'R', code: 'R15', prioridad: 'ALTA', objetivo: 'PRISMA-S (16 ítems): documentar cada componente (fecha, base, interfaz, sintaxis, límites, nº)', entregable: 'Tabla PRISMA-S de SR-1', artefacto: 'vault 02_busqueda/PRISMA-S.md', tool: '—', recs: ['PRISMAS'], apex: null },
  { d: 55, fecha: '2027-03-11', ciclo: 2, fase: 'R3', pista: 'R', code: 'R16', prioridad: 'ALTA', objetivo: 'Corpus: re-correr discovery con la query final + unir con los 200 registros de jun-2026 + dedup por DOI + resolver texto completo en lote (Unpaywall) + exportar CSV/RIS para Rayyan', entregable: 'Biblioteca dedup (n registros) + PDFs OA + CSV/RIS', artefacto: 'vault 02_busqueda/corpus_final.csv', tool: 'research-discovery · Unpaywall', recs: ['UNPAY', 'OPENALEX', 'RAY'], apex: null },
  // R4 · Screening dual
  { d: 56, fecha: '2027-03-15', ciclo: 2, fase: 'R4', pista: 'R', code: 'R17', prioridad: 'CRITICA', objetivo: 'Rayyan: crear la SR-1, subir el corpus, INVITAR al revisor #2 (cuenta creada en X-9), etiquetas de exclusión y modo CIEGO activado', entregable: 'Proyecto Rayyan con 2 revisores en ciego', artefacto: 'Rayyan (SR-1) + vault 03_screening/_README', tool: 'Rayyan', recs: ['RAY', 'RAYHC', 'RAYYT'], apex: { id: 'rayyan', t: 'Cribado dual en Rayyan' } },
  { d: 57, fecha: '2027-03-17', ciclo: 2, fase: 'R4', pista: 'R', code: 'R18 (1/3)', prioridad: 'CRITICA', objetivo: 'Cribado título/abstract (nivel 1) por DOS revisores humanos independientes en ciego (Joseph + revisor #2); ningún LLM cuenta como revisor — primer tercio', entregable: 'Primer tercio cribado por ambos revisores', artefacto: 'Rayyan: decisiones de ambos', tool: 'Rayyan', recs: ['RAY', 'COCHB'], apex: null },
  { d: 58, fecha: '2027-03-19', ciclo: 2, fase: 'R4', pista: 'R', code: 'R18 (2/3)', prioridad: 'CRITICA', objetivo: 'Cribado título/abstract (nivel 1) por DOS revisores humanos independientes en ciego (Joseph + revisor #2); ningún LLM cuenta como revisor — segundo tercio', entregable: 'Dos tercios cribados por ambos', artefacto: 'Rayyan: decisiones de ambos', tool: 'Rayyan', recs: ['RAY', 'COCHB'], apex: null },
  { d: 59, fecha: '2027-03-23', ciclo: 2, fase: 'R4', pista: 'R', code: 'R18 (3/3)', prioridad: 'CRITICA', objetivo: 'Cribado título/abstract (nivel 1) por DOS revisores humanos independientes en ciego (Joseph + revisor #2); ningún LLM cuenta como revisor — cierre', entregable: 'Nivel 1 completo por ambos; conflictos marcados', artefacto: 'Rayyan: decisiones de ambos + lista de conflictos', tool: 'Rayyan', recs: ['RAY', 'COCHB'], apex: null },
  { d: 60, fecha: '2027-03-25', ciclo: 2, fase: 'R4', pista: 'R', code: 'R20', prioridad: 'ALTA', objetivo: 'κ de Cohen del nivel 1 con las decisiones de los 2 humanos (Python/R) + reunión de resolución de conflictos (regla escrita: consenso o 3er revisor)', entregable: 'κ + IC95 % reportado + conflictos resueltos', artefacto: 'vault 03_screening/kappa_n1.md', tool: 'Python/R', recs: ['STEPSR', 'COCHB'], chips: ['κ con un solo humano no tiene sentido: exige 2 revisores'], apex: null },
  { d: 61, fecha: '2027-03-29', ciclo: 2, fase: 'R4', pista: 'R', code: 'R19 (1/2)', prioridad: 'ALTA', objetivo: 'Texto completo (nivel 2) por DOS revisores humanos independientes en ciego (Joseph + revisor #2); ningún LLM cuenta como revisor con razones de exclusión estandarizadas — primera mitad', entregable: 'Mitad de los textos completos revisada por ambos', artefacto: 'Rayyan + vault 03_screening/excluidos.md', tool: 'Rayyan', recs: ['RAY'], apex: null },
  { d: 62, fecha: '2027-03-31', ciclo: 2, fase: 'R4', pista: 'R', code: 'R19 (2/2)', prioridad: 'ALTA', objetivo: 'Texto completo (nivel 2) por DOS revisores humanos independientes en ciego (Joseph + revisor #2); ningún LLM cuenta como revisor — segunda mitad', entregable: 'Nivel 2 completo; excluidos con motivo', artefacto: 'Rayyan + vault 03_screening/excluidos.md', tool: 'Rayyan', recs: ['RAY'], apex: null },
  { d: 63, fecha: '2027-04-02', ciclo: 2, fase: 'R4', pista: 'R', code: 'R21', prioridad: 'ALTA', objetivo: 'κ del nivel 2 + diagrama de flujo PRISMA 2020 con números reales (identificados, cribados, excluidos por motivo, incluidos)', entregable: 'κ nivel 2 + PRISMA flow', artefacto: 'vault 03_screening/PRISMA_flow.png', tool: 'eshackathon Shiny', recs: ['PRISMAF', 'STEPSR'], apex: { id: 'prisma-flow', t: 'Diagrama PRISMA 2020' } },
  // R5 · Extracción doble
  { d: 64, fecha: '2027-04-06', ciclo: 2, fase: 'R5', pista: 'R', code: 'R22', prioridad: 'ALTA', objetivo: 'Formulario de extracción piloteado (diseño, n, producto, zona, tiempo-a-hialuronidasa, dosis, desenlace, secuelas, dominios de sesgo) — mecanismo de la oclusión aprendido en Derma', entregable: 'Plantilla de extracción v1', artefacto: 'vault 04_extraccion/formulario_v1.xlsx', tool: 'Sheets', recs: ['COCHB', 'DELO'], chips: ['requiere Derma d19-20 (oclusión vascular)'], apex: null },
  { d: 65, fecha: '2027-04-08', ciclo: 2, fase: 'R5', pista: 'R', code: 'R23', prioridad: 'ALTA', objetivo: 'Piloto de extracción en 2-3 estudios por AMBOS revisores + ajustar el formulario (v2)', entregable: 'Formulario v2 + 3 filas piloto ×2', artefacto: 'vault 04_extraccion/formulario_v2.xlsx', tool: 'Sheets', recs: ['COCHB'], apex: null },
  { d: 66, fecha: '2027-04-12', ciclo: 2, fase: 'R5', pista: 'R', code: 'R24 (1/3)', prioridad: 'ALTA', objetivo: 'Extracción DOBLE independiente (Joseph + revisor #2); Elicit solo como asistencia para localizar datos, nunca como segundo extractor — primer tercio', entregable: 'Primer tercio extraído ×2', artefacto: 'vault 04_extraccion/extraccion_A.xlsx + extraccion_B.xlsx', tool: 'Sheets · Elicit', recs: ['COCHB', 'ELI'], apex: null },
  { d: 67, fecha: '2027-04-14', ciclo: 2, fase: 'R5', pista: 'R', code: 'R24 (2/3)', prioridad: 'ALTA', objetivo: 'Extracción DOBLE independiente — segundo tercio', entregable: 'Dos tercios extraídos ×2', artefacto: 'vault 04_extraccion/extraccion_A.xlsx + extraccion_B.xlsx', tool: 'Sheets · Elicit', recs: ['COCHB', 'ELI'], apex: null },
  { d: 68, fecha: '2027-04-16', ciclo: 2, fase: 'R5', pista: 'R', code: 'R24 (3/3)', prioridad: 'ALTA', objetivo: 'Extracción DOBLE independiente — cierre + reconciliación de discrepancias registrada', entregable: 'Extracción completa + discrepancias reconciliadas y registradas', artefacto: 'vault 04_extraccion/discrepancias.md', tool: 'Sheets', recs: ['COCHB'], chips: ['la reconciliación se reporta en Methods (PRISMA 2020 ítem 9)'], apex: null },
  { d: 69, fecha: '2027-04-20', ciclo: 2, fase: 'R5', pista: 'R', code: 'R25', prioridad: 'MEDIA', objetivo: 'Cerrar la tabla de características de estudios (1 fila por estudio)', entregable: 'Tabla completa lista para Results', artefacto: 'vault 04_extraccion/tabla_caracteristicas.xlsx', tool: '—', recs: ['COCHB'], apex: { id: 'extraction', t: 'Tabla de extracción cerrada' } },
  // R6 · Sesgo & GRADE
  { d: 70, fecha: '2027-04-22', ciclo: 2, fase: 'R6', pista: 'R', code: 'R26 (1/2)', prioridad: 'ALTA', objetivo: 'Riesgo de sesgo por ambos revisores: ROBINS-I (no-aleatorizados) / JBI-Murad para series y reportes de caso — primera mitad', entregable: 'Mitad evaluada ×2', artefacto: 'vault 04_extraccion/RoB.xlsx', tool: 'riskofbias.info', recs: ['ROBINS', 'ROB2'], apex: null },
  { d: 71, fecha: '2027-04-26', ciclo: 2, fase: 'R6', pista: 'R', code: 'R26 (2/2)', prioridad: 'ALTA', objetivo: 'Riesgo de sesgo — segunda mitad + consenso', entregable: 'RoB completo ×2 + consenso', artefacto: 'vault 04_extraccion/RoB.xlsx', tool: 'riskofbias.info', recs: ['ROBINS', 'ROB2'], apex: { id: 'rob', t: 'Riesgo de sesgo evaluado' } },
  { d: 72, fecha: '2027-04-28', ciclo: 2, fase: 'R6', pista: 'R', code: 'R27', prioridad: 'ALTA', objetivo: 'GRADE (5 dominios) + Summary of Findings por desenlace', entregable: 'SoF table de SR-1', artefacto: 'GRADEpro + vault 04_extraccion/SoF.md', tool: 'GRADEpro', recs: ['GRADE'], apex: null },
  { d: 73, fecha: '2027-04-30', ciclo: 2, fase: 'R6', pista: 'R', code: 'R28', prioridad: 'MEDIA', objetivo: 'AMSTAR-2 sobre 2-3 SR vecinas para posicionar la nuestra en la Discussion', entregable: 'Nota AMSTAR-2', artefacto: 'vault 05_manuscrito/AMSTAR2_vecinas.md', tool: '—', recs: ['AMSTAR'], apex: null },
  // R7 · Meta-análisis en R
  { d: 74, fecha: '2027-05-04', ciclo: 2, fase: 'R7', pista: 'R', code: 'R29 (1/2)', prioridad: 'ALTA', objetivo: 'R + metafor: cargar la tabla de extracción real y preparar el dataset (1 fila por estudio y desenlace)', entregable: 'Script que lee la tabla', artefacto: 'vault 05_manuscrito/ma_01_setup.R', tool: 'R', recs: ['DMAR', 'METAFOR'], apex: null },
  { d: 75, fecha: '2027-05-06', ciclo: 2, fase: 'R7', pista: 'R', code: 'R29 (2/2)', prioridad: 'ALTA', objetivo: 'Calcular 1 tamaño de efecto sobre datos reales (proporción de recuperación / tiempo-a-tratamiento)', entregable: '1 effect size reproducido', artefacto: 'vault 05_manuscrito/ma_01_setup.R', tool: 'R', recs: ['DMAR', 'METAFOR'], apex: { id: 'r-setup', t: 'metafor sobre datos reales' } },
  { d: 76, fecha: '2027-05-10', ciclo: 2, fase: 'R7', pista: 'R', code: 'R30 (1/2)', prioridad: 'ALTA', objetivo: 'Tamaño de efecto correcto (proporciones transformadas / medias de tiempo) + modelo de efectos aleatorios vs fijo (justificar por escrito)', entregable: 'Elección justificada', artefacto: 'vault 05_manuscrito/ma_02_pooled.R', tool: 'R', recs: ['DMAR', 'COCHYT'], apex: null },
  { d: 77, fecha: '2027-05-12', ciclo: 2, fase: 'R7', pista: 'R', code: 'R30 (2/2)', prioridad: 'ALTA', objetivo: 'Pooled estimate con IC95 %', entregable: 'Pooled estimate + IC95 %', artefacto: 'vault 05_manuscrito/ma_02_pooled.R', tool: 'R', recs: ['DMAR'], apex: null },
  { d: 78, fecha: '2027-05-14', ciclo: 2, fase: 'R7', pista: 'R', code: 'R31 (1/2)', prioridad: 'ALTA', objetivo: 'Forest plot v1 + heterogeneidad (I², τ², intervalo de predicción)', entregable: 'Forest plot v1 + I²/τ²', artefacto: 'vault 05_manuscrito/fig_forest.tiff', tool: 'R', recs: ['DMAR', 'METAFOR'], apex: null },
  { d: 79, fecha: '2027-05-18', ciclo: 2, fase: 'R7', pista: 'R', code: 'R31 (2/2)', prioridad: 'ALTA', objetivo: 'Forest plot final TIFF 300 dpi + párrafo de heterogeneidad', entregable: 'Forest TIFF 300 dpi + I²/τ² reportados', artefacto: 'vault 05_manuscrito/fig_forest.tiff', tool: 'R', recs: ['DMAR', 'METAFOR'], apex: { id: 'forest', t: 'Forest plot + heterogeneidad' } },
  { d: 80, fecha: '2027-05-20', ciclo: 2, fase: 'R7', pista: 'R', code: 'R32', prioridad: 'MEDIA', objetivo: 'Sesgo de publicación: funnel plot + test de Egger (si ≥10 estudios; si no, declararlo)', entregable: 'Funnel + Egger o justificación', artefacto: 'vault 05_manuscrito/fig_funnel.tiff', tool: 'R', recs: ['DMAR'], apex: null },
  { d: 81, fecha: '2027-05-24', ciclo: 2, fase: 'R7', pista: 'R', code: 'R33 (1/2)', prioridad: 'MEDIA', objetivo: 'Subgrupos definidos a priori en el protocolo: tiempo-a-hialuronidasa (<24 h vs ≥24 h), zona (nasal / glabelar / labial), producto, formación del inyector, LATAM vs resto', entregable: 'Subgrupos calculados', artefacto: 'vault 05_manuscrito/ma_03_subgrupos.R', tool: 'R', recs: ['DMAR'], chips: ['requiere Derma d19-20 (oclusión vascular)'], apex: null },
  { d: 82, fecha: '2027-05-26', ciclo: 2, fase: 'R7', pista: 'R', code: 'R33 (2/2)', prioridad: 'MEDIA', objetivo: 'Análisis de sensibilidad + tabla de subgrupos', entregable: 'Sensibilidad + tabla de subgrupos', artefacto: 'vault 05_manuscrito/ma_03_subgrupos.R', tool: 'R', recs: ['DMAR'], chips: ['requiere Derma d19-20 (oclusión vascular)'], apex: null },
  // B · Bibliométrico & abstracts
  { d: 83, fecha: '2027-05-28', ciclo: 2, fase: 'B', pista: 'B', code: 'B1', prioridad: 'MEDIA', objetivo: 'Abstract (≈250 palabras) para el congreso elegido en X-4 (CILAD / RADLA / AAD) con los resultados preliminares de SR-1 o la tesis — respetar su deadline verificado', entregable: 'Abstract enviado o programado', artefacto: 'vault 05_manuscrito/abstract_congreso.md + Mesa editorial', tool: 'Web del congreso', recs: ['PHRASE', 'SCIWRITE'], apex: null },
  // R8 · Manuscrito & envío
  { d: 84, fecha: '2027-06-01', ciclo: 2, fase: 'R8', pista: 'R', code: 'R34', prioridad: 'ALTA', objetivo: 'Methods con PRISMA 2020 (registro, elegibilidad, fuentes, búsqueda, selección con 2 revisores, extracción doble, sesgo, síntesis) — MethodsAgent + CP-1/CP-2', entregable: 'Methods redactado y revisado', artefacto: 'vault 05_manuscrito/methods.md', tool: 'Sistema agéntico', recs: ['PRISMA', 'PRISMAC'], apex: { id: 'methods', t: 'Methods (PRISMA 2020)' } },
  { d: 85, fecha: '2027-06-03', ciclo: 2, fase: 'R8', pista: 'R', code: 'R35', prioridad: 'ALTA', objetivo: 'Results: flujo PRISMA + tabla de características + forest + SoF; cada número trazable a la tabla de extracción (ResultsAgent + CP-2)', entregable: 'Results + tablas y figuras', artefacto: 'vault 05_manuscrito/results.md', tool: 'Sistema agéntico', recs: ['PRISMAC', 'GRADE'], apex: null },
  { d: 86, fecha: '2027-06-07', ciclo: 2, fase: 'R8', pista: 'R', code: 'R36', prioridad: 'ALTA', objetivo: 'Introduction (gap + objetivo) con [CIT:id] desde el corpus (IntroAgent) + micro-drill Phrasebank', entregable: 'Intro redactada', artefacto: 'vault 05_manuscrito/intro.md', tool: 'Sistema agéntico', recs: ['PHRASE', 'EQ'], apex: null },
  { d: 87, fecha: '2027-06-09', ciclo: 2, fase: 'R8', pista: 'R', code: 'R37', prioridad: 'ALTA', objetivo: 'Discussion: hallazgo principal, comparación con SR vecinas (AMSTAR-2), certeza GRADE, limitaciones explícitas (sesgo de publicación, series de casos), implicación LATAM / PERÚ-SAFE', entregable: 'Discussion redactada', artefacto: 'vault 05_manuscrito/discussion.md', tool: 'Sistema agéntico', recs: ['PHRASE', 'PRISMAC'], apex: null },
  { d: 88, fecha: '2027-06-11', ciclo: 2, fase: 'R8', pista: 'R', code: 'R38', prioridad: 'ALTA', objetivo: 'Checklist PRISMA 2020 de 27 ítems + supplements (PRISMA-S, SoF, CRD, formulario de extracción, código R)', entregable: 'Checklist 27/27 + supplements', artefacto: 'vault 05_manuscrito/PRISMA_checklist.md + supplements/', tool: '—', recs: ['PRISMAC', 'TURING'], apex: null },
  { d: 89, fecha: '2027-06-15', ciclo: 2, fase: 'R8', pista: 'R', code: 'R39', prioridad: 'MEDIA', objetivo: 'Journal target + coste: Dermatologic Surgery / JAAD (suscripción $0) / JCD (OA 50 % Grupo B) / Anais-Actas (Diamond $0); verificar APC en la web y Research4Life', entregable: 'Journal decidido + plan de coste', artefacto: 'Mesa editorial: cascada SR-1 + coste', tool: '—', recs: ['EQ', 'JAADINT', 'ANAIS'], apex: null },
  // CR · Case report (CARE)
  { d: 90, fecha: '2027-06-17', ciclo: 2, fase: 'CR', pista: 'CR', code: 'CR2-1', prioridad: 'ALTA', objetivo: 'Case report #2: identificar caso + senior author (misma tabla de candidatos; priorizar complicación estética = L4) — reservar JAAD Case Reports solo si es el MEJOR caso', entregable: 'Caso #2 elegido + senior author', artefacto: 'DATA/RESEARCH/CASE_REPORT_2/caso_candidatos.md', tool: 'Senior author', recs: ['CARE', 'JAADCR'], apex: null },
  // R8 · Manuscrito & envío
  { d: 91, fecha: '2027-06-21', ciclo: 2, fase: 'R8', pista: 'R', code: 'R40', prioridad: 'MEDIA', objetivo: 'Cover letter + formateo al journal (Editorial Manager / ScholarOne) + página de autoría (ICMJE / CRediT / ORCID / conflictos de TODOS los autores)', entregable: 'Manuscrito formateado + cover + autoría', artefacto: 'vault 05_manuscrito/SR-1_formateado.docx + cover_letter.md', tool: 'Editorial Manager', recs: ['EM', 'ICMJE', 'CREDIT'], apex: null },
  { d: 92, fecha: '2027-06-23', ciclo: 2, fase: 'R8', pista: 'R', code: 'R41', prioridad: 'CRITICA', objetivo: 'CHECKPOINT HUMANO (CP-3/CP-4): citation_verifier.py sobre TODAS las refs (Crossref/PMID + CSL-JSON), paráfrasis, cadena estadística; el revisor #2 firma la lectura completa', entregable: '.docx aprobado por Joseph y por el revisor #2; 0 [NO VERIFICABLE]', artefacto: 'vault 05_manuscrito/refs_verified.json + SR-1_revision_v1.docx', tool: 'citation_verifier.py', recs: ['CROSSREF', 'PRISMAC'], apex: { id: 'hitl', t: 'Checkpoint humano CP-4' } },
  { d: 93, fecha: '2027-06-25', ciclo: 2, fase: 'R8', pista: 'R', code: 'R42', prioridad: 'ALTA', objetivo: 'Gate de integridad final: ICMJE 4 criterios por autor, roles CRediT, COPE (sin salami, sin doble envío), preprint sí/no, datos y código depositados (OSF / Zenodo)', entregable: 'Gate ICMJE / COPE / CRediT superado + DOI de datos', artefacto: 'vault 05_manuscrito/integridad.md + OSF', tool: 'OSF', recs: ['ICMJE', 'COPE', 'CREDIT', 'FAIR'], apex: null },
  { d: 94, fecha: '2027-06-29', ciclo: 2, fase: 'R8', pista: 'R', code: 'R43', prioridad: 'CRITICA', objetivo: 'SUBMIT SR-1 ✅ + registrar en la Mesa editorial y CTI Vitae + actualizar el estado en PROSPERO', entregable: 'SR-1 ENVIADA · estado SR-1 → enviado', artefacto: 'Mesa editorial + PROSPERO actualizado', tool: 'Editorial Manager', recs: ['PROS', 'ICMJE'], apex: { id: 'submit', t: 'SR-1 enviada' } },
  // X · Transversal · cierre
  { d: 95, fecha: '2027-07-01', ciclo: 2, fase: 'X', pista: 'X', code: 'X-10', prioridad: 'MEDIA', objetivo: 'Re-verificar el Grupo Research4Life de Perú (clasificación Banco Mundial · 1-jul) + presupuesto actualizado con los APC reales de los 4 entregables', entregable: 'Presupuesto research 2026-27 actualizado con fechas de verificación', artefacto: 'RUTA_PUBLICACION_2027.md §3 presupuesto', tool: 'Web Research4Life', recs: ['JAADINT'], apex: null },
  // B · Bibliométrico & abstracts
  { d: 96, fecha: '2027-07-05', ciclo: 2, fase: 'B', pista: 'B', code: 'B2', prioridad: 'MEDIA', objetivo: 'Estudio bibliométrico / base pública (sin IRB): fijar pregunta + fuente (NRMP Charting Outcomes, Texas STAR, GBD, Google Trends) alineada con derma IMG / fototipos', entregable: 'Pregunta + fuente + variables', artefacto: 'DATA/RESEARCH/BIBLIOMETRICO_1/protocolo.md', tool: '—', recs: ['NRMP', 'BBR'], apex: null },
  // CR · Case report (CARE)
  { d: 97, fecha: '2027-07-07', ciclo: 2, fase: 'CR', pista: 'CR', code: 'CR2-2', prioridad: 'ALTA', objetivo: 'Case report #2: consentimiento de publicación firmado + fotos estandarizadas (plantillas del case report #1)', entregable: 'Consentimiento + fotos', artefacto: 'CASE_REPORT_2/', tool: 'Plantillas CR-1', recs: ['CARE'], apex: null },
  // B · Bibliométrico & abstracts
  { d: 98, fecha: '2027-07-09', ciclo: 2, fase: 'B', pista: 'B', code: 'B3', prioridad: 'MEDIA', objetivo: 'Bibliométrico: extraer los datos + Table 1 con gtsummary + data dictionary y README (FAIR)', entregable: 'Dataset limpio + Table 1 + README', artefacto: 'BIBLIOMETRICO_1/data/ + tabla1.docx', tool: 'R · gtsummary', recs: ['GTS', 'FAIR', 'TURING'], apex: null },
  // CR · Case report (CARE)
  { d: 99, fecha: '2027-07-13', ciclo: 2, fase: 'CR', pista: 'CR', code: 'CR2-3', prioridad: 'ALTA', objetivo: 'Case report #2: CARE 13 ítems + borrador v1', entregable: 'CARE 13/13 + borrador', artefacto: 'CASE_REPORT_2/borrador_v1.md', tool: 'CARE', recs: ['CARE', 'PHRASE'], apex: null },
  // B · Bibliométrico & abstracts
  { d: 100, fecha: '2027-07-15', ciclo: 2, fase: 'B', pista: 'B', code: 'B4', prioridad: 'MEDIA', objetivo: 'Bibliométrico: figuras + borrador (≤1500 palabras) con [CIT:id]', entregable: 'Borrador v1 + 2 figuras', artefacto: 'BIBLIOMETRICO_1/borrador_v1.md', tool: 'R', recs: ['PHRASE', 'SCIWRITE'], apex: null },
  // CR · Case report (CARE)
  { d: 101, fecha: '2027-07-19', ciclo: 2, fase: 'CR', pista: 'CR', code: 'CR2-4', prioridad: 'CRITICA', objetivo: 'Case report #2: revisión del senior author + formateo (DOJ, o JAAD Case Reports si es el mejor caso) + citas verificadas + SUBMIT', entregable: 'Case report #2 ENVIADO', artefacto: 'Mesa editorial (nuevo ítem case-report-2)', tool: 'citation_verifier.py', recs: ['DOJ', 'JAADCR', 'CROSSREF'], apex: null },
  // X · Transversal · cierre
  { d: 102, fecha: '2027-07-21', ciclo: 2, fase: 'X', pista: 'X', code: 'X-11', prioridad: 'MEDIA', objetivo: 'Post-submit SR-1: plantilla de rebuttal preparada + hacer 1 peer review (curso Sainani) para entender al revisor', entregable: 'Rebuttal plantilla + 1 review practicada', artefacto: 'vault 05_manuscrito/rebuttal_plantilla.md', tool: '—', recs: ['REBUTTAL', 'SCIWRITE'], apex: null },
  // B · Bibliométrico & abstracts
  { d: 103, fecha: '2027-07-23', ciclo: 2, fase: 'B', pista: 'B', code: 'B5', prioridad: 'MEDIA', objetivo: 'Bibliométrico: citas verificadas + formateo + SUBMIT (journal por decidir; Cureus solo táctico, máximo 1-2 ítems del CV)', entregable: 'Bibliométrico ENVIADO', artefacto: 'Mesa editorial (nuevo ítem bibliometrico-1)', tool: 'citation_verifier.py', recs: ['CROSSREF', 'DOJ'], apex: null },
  // R1 · Pregunta & protocolo
  { d: 104, fecha: '2027-07-27', ciclo: 2, fase: 'R1', pista: 'R', code: 'R44', prioridad: 'ALTA', objetivo: 'SR-2 (Línea 5 · RF/CO₂ en fototipos IV-VI): PICO + duplicidad (el MA 2026 de Argobi en JCD acota el gap al subgrupo IV-VI) → abrir el ciclo 3', entregable: 'PICO de SR-2 + decisión', artefacto: 'lines/L5-energia-fototipos.md §2 + vault SR-2/_hoja_de_ruta', tool: 'PROSPERO · PubMed', recs: ['PROS', 'PM'], apex: null },
  { d: 105, fecha: '2027-07-29', ciclo: 2, fase: 'R1', pista: 'R', code: 'R45', prioridad: 'ALTA', objetivo: 'SR-2: protocolo PRISMA-P + equipo de revisión (revisor #2 desde el inicio, coautores de la campaña)', entregable: 'Protocolo SR-2 + equipo', artefacto: 'lines/L5-energia-fototipos.md §Equipo de revisión', tool: '—', recs: ['PRISMA', 'COCHB'], apex: null },
  // R2 · Registro PROSPERO
  { d: 106, fecha: '2027-08-02', ciclo: 2, fase: 'R2', pista: 'R', code: 'R46', prioridad: 'ALTA', objetivo: 'SR-2: registro PROSPERO ENVIADO', entregable: 'PROSPERO SR-2 enviado', artefacto: 'Mesa editorial (nuevo ítem PROSPERO-SR2)', tool: 'PROSPERO', recs: ['PROS'], apex: { id: 'prospero-sr2', t: 'SR-2 registrada' } },
  // X · Transversal · cierre
  { d: 107, fecha: '2027-08-04', ciclo: 2, fase: 'X', pista: 'X', code: 'X-12', prioridad: 'ALTA', objetivo: 'BALANCE 12 meses (RUTA §6): publicaciones enviadas / aceptadas, abstracts, mentores (Ciro · Rising Scholars · Finlay · campaña), decisión informada sobre research fellowship presencial 2028', entregable: 'Balance escrito + decisión fellowship 2028 (sí / no / cuándo)', artefacto: 'RUTA_PUBLICACION_2027.md §Balance + Mesa editorial', tool: 'Mesa editorial', recs: ['ICMJE'], apex: { id: 'balance', t: 'Balance ago-2027' } },
  { d: 108, fecha: '2027-08-06', ciclo: 2, fase: 'X', pista: 'X', code: 'X-13', prioridad: 'BAJA', objetivo: 'COLCHÓN 1: cerrar cualquier átomo a medias (rebuttals, revisiones mayores, case report #2)', entregable: 'Sin pendientes abiertos', artefacto: 'Mesa editorial', tool: '—', recs: ['REBUTTAL'], apex: null },
  { d: 109, fecha: '2027-08-10', ciclo: 2, fase: 'X', pista: 'X', code: 'X-14', prioridad: 'BAJA', objetivo: 'COLCHÓN 2: retro del método — qué automatizar para SR-2 en el sistema agéntico + arranque del plan del ciclo 3', entregable: 'Lista de mejoras + ciclo 3 esbozado', artefacto: 'Vault Dashboard_Research', tool: 'Obsidian', recs: ['TURING'], apex: null },
];
