/**
 * SYNAPSE — formación élite en IA (Mind · AI-engineered).
 * Médico → especialista en IA nivel Anthropic: Python, datos, deep learning,
 * agentes/workflows, ciberseguridad, post-training.
 *
 * TODOS los materiales fueron verificados con WebFetch/oEmbed (10-jun-2026) por un
 * workflow de 13 agentes (6 frentes + verificación adversarial + crítico de
 * completitud). Fuente completa: DATA/SYNAPSE/_raw_findings.json (85 materiales)
 * y DATA/SYNAPSE/materiales-verificados.md. Cero URLs inventadas.
 *
 * El motor día-a-día (misiones estilo ENCAPS/Business + Calendar 30 min) lo
 * construye el chat SYNAPSE: DATA/SYNAPSE/PROMPT_CHAT_SYNAPSE.md.
 */

export type SynapseNivel = 'base' | 'intermedio' | 'avanzado';

export type SynapseMaterial = {
  nombre: string;
  referente: string;
  credencial: string;
  tipo: 'curso' | 'libro' | 'video' | 'playlist' | 'podcast' | 'docs' | 'tutorial' | 'beca';
  url: string;
  gratis: string; // 'gratis' | precio | 'parcial'
  duracion?: string;
  nivel: SynapseNivel;
  porQue: string;
  audio?: boolean; // sirve para espacios muertos (audio / lectura / vídeo corto móvil)
};

export type SynapseFase = {
  id: string;
  fase: string;
  titulo: string;
  desc: string;
  duracion: string;
  entregable: string;
  estado: 'activa' | 'pendiente' | 'meta';
  materiales: SynapseMaterial[];
};

// ─── Materiales (definidos una vez, referenciados por fase y biblioteca) ───
const M = {
  // F0 — La Escuela de Anthropic
  academy: { nombre: 'Anthropic Academy (portal oficial)', referente: 'Anthropic', credencial: 'La "escuela de Anthropic" — cursos oficiales con certificado', tipo: 'docs', url: 'https://www.anthropic.com/learn', gratis: 'gratis', duracion: '21 cursos en Skilljar', nivel: 'base', porQue: 'Punto de entrada único a la licenciatura de Anthropic; emite certificados (incl. "Introduction to Claude Cowork" y "AI Capabilities and Limitations") + prep directa del examen CCA-F', audio: true },
  claude101: { nombre: 'Claude 101 (+ Claude Code 101 + Platform 101)', referente: 'Anthropic Academy', credencial: 'Cursos oficiales de Anthropic con certificado', tipo: 'curso', url: 'https://anthropic.skilljar.com/claude-101', gratis: 'gratis', duracion: '13 lecciones · 4 módulos', nivel: 'base', porQue: 'El arranque oficial: orientación a Claude, Claude Code y la plataforma', audio: true },
  aiFluency: { nombre: 'AI Fluency: Framework & Foundations', referente: 'Anthropic Academy', credencial: 'Marco oficial 4D (Delegation·Description·Discernment·Diligence)', tipo: 'curso', url: 'https://anthropic.skilljar.com/ai-fluency-framework-foundations', gratis: 'gratis', duracion: 'módulos cortos + examen', nivel: 'base', porQue: 'Cómo Anthropic piensa la colaboración humano-IA; vocabulario interno', audio: true },
  effectiveAgents: { nombre: 'Building Effective AI Agents (ensayo)', referente: 'Schluntz & Zhang · Anthropic', credencial: 'El ensayo fundacional de agentes citado en toda la industria', tipo: 'docs', url: 'https://www.anthropic.com/engineering/building-effective-agents', gratis: 'gratis', duracion: '~25 min lectura', nivel: 'intermedio', porQue: 'Los 5 patrones de workflows vs agents — vocabulario obligatorio en entrevistas', audio: true },
  karpathyIntro: { nombre: '[1hr Talk] Intro to Large Language Models', referente: 'Andrej Karpathy', credencial: 'Stanford PhD · fundador de OpenAI · ex-director IA Tesla', tipo: 'video', url: 'https://www.youtube.com/watch?v=zjkBMFhNj_g', gratis: 'gratis', duracion: '1 h', nivel: 'base', porQue: 'La mejor panorámica de qué es un LLM, sin código ni matemática', audio: true },
  karpathyDeep: { nombre: 'Deep Dive into LLMs like ChatGPT', referente: 'Andrej Karpathy', credencial: 'Stanford PhD · fundador de OpenAI · ex-Tesla', tipo: 'video', url: 'https://www.youtube.com/watch?v=7xTGNNLPyMI', gratis: 'gratis', duracion: '3.5 h (≈14 huecos)', nivel: 'base', porQue: 'Pretraining, fine-tuning, RLHF y alucinaciones — cómo se construye un Claude', audio: true },
  nn3b1b: { nombre: 'Neural networks (incluye transformers/GPT)', referente: '3Blue1Brown · Grant Sanderson', credencial: 'Matemático de Stanford, el divulgador más respetado', tipo: 'playlist', url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi', gratis: 'gratis', duracion: '8 vídeos · ~2.5 h', nivel: 'base', porQue: 'La mejor intuición VISUAL de redes, backprop y transformers', audio: true },

  // F1 — Código
  cs50p: { nombre: 'CS50P: Introduction to Programming with Python', referente: 'David J. Malan · Harvard', credencial: 'El curso introductorio más famoso del mundo', tipo: 'curso', url: 'https://cs50.harvard.edu/python/', gratis: 'gratis', duracion: '10 semanas + proyecto', nivel: 'base', porQue: 'Python con rigor Harvard — prerrequisito directo de todo lo demás', audio: true },
  automate: { nombre: 'Automate the Boring Stuff with Python (3ª ed.)', referente: 'Al Sweigart', credencial: 'Fellow de la Python Software Foundation · +500k copias', tipo: 'libro', url: 'https://automatetheboringstuff.com/', gratis: 'gratis online', duracion: '25 capítulos', nivel: 'base', porQue: 'Automatización real desde el capítulo 1 — Python práctico desde cero', audio: true },
  pyTutorial: { nombre: 'The Python Tutorial (docs oficiales)', referente: 'Python Software Foundation', credencial: 'La referencia canónica del lenguaje', tipo: 'docs', url: 'https://docs.python.org/3/tutorial/', gratis: 'gratis', duracion: '16 secciones', nivel: 'base', porQue: 'La misma fuente que usa cualquier ingeniero serio', audio: true },
  proGit: { nombre: 'Pro Git (2ª ed.)', referente: 'Scott Chacon', credencial: 'Cofundador de GitHub', tipo: 'libro', url: 'https://git-scm.com/book/en/v2', gratis: 'gratis (CC)', duracion: '10 capítulos', nivel: 'base', porQue: 'Git/GitHub es lo primero que delata a un no-ingeniero — hueco crítico detectado', audio: true },
  missingSemester: { nombre: 'The Missing Semester of Your CS Education', referente: 'MIT CSAIL', credencial: 'Curso oficial del MIT (shell, Git, debugging)', tipo: 'curso', url: 'https://missing.csail.mit.edu/', gratis: 'gratis', duracion: '11 lecciones', nivel: 'base', porQue: 'Vivir en la terminal: el pegamento de Claude Code, agentes y todo el tooling', audio: true },
  cs50x: { nombre: 'CS50x: Introduction to Computer Science', referente: 'David J. Malan · Harvard', credencial: 'El curso más tomado de la historia de Harvard', tipo: 'curso', url: 'https://cs50.harvard.edu/x/', gratis: 'gratis', duracion: '11 semanas', nivel: 'base', porQue: 'Pensamiento computacional desde cero absoluto (opcional si haces CS50P)', audio: true },

  // F2 — Datos
  kaggle: { nombre: 'Kaggle Learn (Python, pandas, Intro ML)', referente: 'Kaggle · Google', credencial: 'La plataforma de data science de Google', tipo: 'tutorial', url: 'https://www.kaggle.com/learn', gratis: 'gratis', duracion: '~4 h por micro-curso', nivel: 'base', porQue: 'Lecciones de 15-20 min — encaje exacto con tus 30 min/día', audio: true },
  mckinney: { nombre: 'Python for Data Analysis (3ª ed., Open Access)', referente: 'Wes McKinney', credencial: 'CREADOR de pandas', tipo: 'libro', url: 'https://wesmckinney.com/book/', gratis: 'gratis online', duracion: '13 capítulos', nivel: 'intermedio', porQue: 'Aprender pandas del creador de pandas', audio: true },
  vanderplas: { nombre: 'Python Data Science Handbook', referente: 'Jake VanderPlas', credencial: 'Google Research · contribuidor scikit-learn', tipo: 'libro', url: 'https://jakevdp.github.io/PythonDataScienceHandbook/', gratis: 'gratis online', duracion: 'NumPy→pandas→Matplotlib→sklearn', nivel: 'intermedio', porQue: 'El stack científico completo en un solo sitio gratis', audio: true },
  sqlbolt: { nombre: 'SQLBolt — SQL interactivo', referente: 'SQLBolt', credencial: 'El tutorial interactivo canónico de SQL', tipo: 'tutorial', url: 'https://sqlbolt.com/', gratis: 'gratis', duracion: '18 lecciones · 5-8 h', nivel: 'base', porQue: 'Micro-lecciones de 5-10 min que corren en el navegador del móvil', audio: true },
  widom: { nombre: 'Databases: Relational Databases and SQL', referente: 'Jennifer Widom · Stanford', credencial: 'Decana de ingeniería de Stanford, autoridad mundial en BD', tipo: 'curso', url: 'https://www.edx.org/learn/relational-databases/stanford-university-databases-relational-databases-and-sql', gratis: 'audit gratis', duracion: '8-10 h', nivel: 'intermedio', porQue: 'SQL con pedigrí Stanford para consolidar SQLBolt', audio: true },
  stat110: { nombre: 'Introduction to Probability (Stat 110)', referente: 'Joe Blitzstein · Harvard', credencial: 'Professor of the Practice in Statistics, Harvard', tipo: 'libro', url: 'https://probabilitybook.net', gratis: 'gratis (PDF oficial + YouTube)', duracion: '~35 lecciones', nivel: 'intermedio', porQue: 'Todo el ML es probabilidad — hueco crítico detectado por el auditor', audio: true },

  // F3 — Deep learning
  algebra3b1b: { nombre: 'Essence of linear algebra', referente: '3Blue1Brown', credencial: 'Matemático de Stanford', tipo: 'playlist', url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab', gratis: 'gratis', duracion: '16 vídeos · ~3 h', nivel: 'base', porQue: 'La matemática mínima para entender redes — intuición geométrica', audio: true },
  calculo3b1b: { nombre: 'Essence of calculus', referente: '3Blue1Brown', credencial: 'Matemático de Stanford', tipo: 'playlist', url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr', gratis: 'gratis', duracion: '12 vídeos · ~3 h', nivel: 'base', porQue: 'Derivadas y gradientes — el corazón de backpropagation', audio: true },
  mit6s191: { nombre: 'MIT 6.S191: Introduction to Deep Learning', referente: 'Alexander Amini · MIT', credencial: 'Curso oficial del MIT, edición 2026 en curso', tipo: 'curso', url: 'https://introtodeeplearning.com/', gratis: 'gratis (open source)', duracion: '9 lectures + 3 labs', nivel: 'intermedio', porQue: 'El bootcamp de DL más condensado y actualizado con sello MIT' },
  fastai: { nombre: 'Practical Deep Learning for Coders', referente: 'Jeremy Howard · fast.ai', credencial: 'Fundador fast.ai/Answer.AI · ex-presidente de Kaggle', tipo: 'curso', url: 'https://course.fast.ai/', gratis: 'gratis', duracion: '9 lecciones · ~90 min', nivel: 'intermedio', porQue: 'Top-down: entrenas modelos reales desde la lección 1' },
  zeroToHero: { nombre: 'Neural Networks: Zero to Hero', referente: 'Andrej Karpathy', credencial: 'Fundador de OpenAI · ex-Tesla', tipo: 'playlist', url: 'https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ', gratis: 'gratis', duracion: '~10 lecciones · 18-20 h', nivel: 'intermedio', porQue: 'EL curso canónico: construyes un GPT desde cero en código (requiere teclado)' },
  cs50ai: { nombre: 'CS50 AI: Artificial Intelligence with Python', referente: 'Brian Yu & Malan · Harvard', credencial: 'Profesores de Harvard', tipo: 'curso', url: 'https://cs50.harvard.edu/ai/', gratis: 'gratis', duracion: '7 semanas', nivel: 'intermedio', porQue: 'Puente perfecto entre CS50P y deep learning, con proyectos guiados', audio: true },
  nanochat: { nombre: 'nanochat (capstone de Eureka Labs)', referente: 'Andrej Karpathy', credencial: 'Sucesor de nanoGPT (~55k stars)', tipo: 'tutorial', url: 'https://github.com/karpathy/nanochat', gratis: 'gratis (entrenar ~$48 opcional)', duracion: 'pipeline completo', nivel: 'avanzado', porQue: 'Un clon de ChatGPT full-stack mínimo y hackeable — proyecto final de fase' },
  // ★ TOP 2026 — construir un LLM de verdad (el diferenciador élite vs "pegar APIs")
  cs336: { nombre: 'Stanford CS336: Language Modeling from Scratch (ed. 2026)', referente: 'Tatsunori Hashimoto & Percy Liang · Stanford', credencial: 'El curso universitario CUMBRE 2026 para construir un LLM completo', tipo: 'curso', url: 'https://cs336.stanford.edu/', gratis: 'gratis (vídeos+slides+5 assignments)', duracion: 'tokenización→Transformer→FlashAttention→scaling→post-training', nivel: 'avanzado', porQue: 'El recurso CUMBRE para construir un LLM de verdad (FlashAttention2/Triton, paralelismo, scaling laws, SFT/RLHF). El salto a élite real (F3→F6)' },
  raschkaScratch: { nombre: 'rasbt/LLMs-from-scratch — código línea-a-línea (Raschka)', referente: 'Sebastian Raschka', credencial: 'Estándar de oro para CODIFICAR un GPT en PyTorch paso a paso', tipo: 'tutorial', url: 'https://github.com/rasbt/LLMs-from-scratch', gratis: 'gratis (código MIT; libro aparte)', duracion: 'base model → clasificador → chatbot (corre en laptop)', nivel: 'avanzado', porQue: 'Si nanochat es "entrenar", esto es "entender cada línea": GPT en PyTorch sin librerías externas. Su reasoning-from-scratch (2025) extiende a modelos de razonamiento' },
  transformerCircuits: { nombre: 'Transformer Circuits Thread (interpretabilidad de frontera)', referente: 'Anthropic Interpretability', credencial: 'Circuit tracing, attribution graphs — Breakthrough Tech 2026', tipo: 'docs', url: 'https://transformer-circuits.pub/', gratis: 'gratis', duracion: 'serie de papers/ensayos', nivel: 'avanzado', porQue: 'La frontera 2026 de interpretabilidad mecanicista (cross-layer transcoders, attribution graphs) — refuerza F6 junto a ARENA/RLHF Book', audio: true },
  // ★ TOP 2026 — Anthropic: certificación + context engineering (dominio #5 del CCA-F)
  ccaF: { nombre: 'Claude Certified Architect — Foundations (CCA-F)', referente: 'Anthropic Academy', credencial: 'Primera certificación técnica oficial (12-mar-2026)', tipo: 'curso', url: 'https://www.anthropic.com/learn', gratis: '99 USD (gratis partners)', duracion: '60 preguntas · 120 min · aprobar 720/1000', nivel: 'intermedio', porQue: 'GAP CLAVE: la credencial VERIFICABLE "nivel Anthropic". 5 dominios (Agentic 27%, Claude Code 20%, Tool/MCP 18%, Prompt Eng 20%, Context Mgmt 15%). La Academy completa es la prep gratuita — hito de F0→F4', audio: true },
  contextEng: { nombre: 'Effective context engineering for AI agents (ensayo)', referente: 'Anthropic Engineering', credencial: 'Define context engineering como sucesor del prompt engineering', tipo: 'docs', url: 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents', gratis: 'gratis', duracion: '~25 min lectura', nivel: 'intermedio', porQue: 'GAP CLAVE de F4 y dominio #5 del CCA-F: context rot, compaction, structured note-taking, just-in-time retrieval. Apto para huecos/audio', audio: true },
  harnesses: { nombre: 'Effective harnesses for long-running agents (ensayo)', referente: 'Anthropic Engineering', credencial: 'Ensayo oficial (26-nov-2025) sobre agentes de larga duración', tipo: 'docs', url: 'https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents', gratis: 'gratis', duracion: '~20 min lectura', nivel: 'avanzado', porQue: 'Cómo diseñar el "harness" de agentes que corren mucho tiempo — al mismo nivel que "Building Effective Agents"', audio: true },
  agentSkillsEssay: { nombre: 'Equipping agents for the real world with Agent Skills (ensayo)', referente: 'Anthropic Engineering', credencial: 'Ensayo oficial (18-dic-2025) sobre Agent Skills', tipo: 'docs', url: 'https://www.anthropic.com/engineering/equipping-agents-for-the-real-world-with-agent-skills', gratis: 'gratis', duracion: '~20 min lectura', nivel: 'avanzado', porQue: 'El tercer ensayo fundacional 2025 de context engineering: cómo las Skills equipan agentes para el mundo real', audio: true },
  claudeCookbooks: { nombre: 'anthropics/claude-cookbooks — patterns/agents', referente: 'Anthropic (GitHub oficial)', credencial: 'Implementaciones oficiales de los 5 patrones de agentes', tipo: 'tutorial', url: 'https://github.com/anthropics/claude-cookbooks/tree/main/patterns/agents', gratis: 'gratis (tokens aparte)', duracion: 'notebooks (chaining, routing, parallelization, orchestrator-workers, evaluator-optimizer)', nivel: 'avanzado', porQue: 'La fuente con más autoridad para agentes de producción + orquestación multi-agente async (acompaña "Building Effective Agents") — incluye tool-use/context engineering y memory tools/compaction de Sonnet 4.5' },
  // ★ TOP 2026 — la capa de evals y producción (el tema más subestimado)
  hamelEvals: { nombre: 'LLM Evals — guía FAQ + masterclass (Hamel Husain)', referente: 'Hamel Husain (+ Shreya Shankar)', credencial: 'Los referentes de evals/LLM evaluation 2026', tipo: 'docs', url: 'https://hamel.dev/blog/posts/evals-faq/', gratis: 'gratis (guía + masterclass 50 min)', duracion: 'guía exhaustiva + vídeo', nivel: 'avanzado', porQue: 'Los evals son el tema MÁS subestimado y diferenciador 2026. El curso de Maven es pago, pero esta guía + masterclass son gratis y de altísimo nivel — cierra la capa de evaluación/observabilidad', audio: true },
  aieBook: { nombre: 'chiphuyen/aie-book — recursos del libro AI Engineering', referente: 'Chip Huyen', credencial: 'Repo de soporte del libro más leído en O\'Reilly 2025', tipo: 'docs', url: 'https://github.com/chiphuyen/aie-book', gratis: 'gratis', duracion: 'blogs, papers y resources.md curados', nivel: 'intermedio', porQue: 'Cubre la capa de producción que falta entre "construir" y "desplegar" (complemento gratis al libro AI Engineering de F4)' },
  llmZoomcamp: { nombre: 'LLM Zoomcamp — 10 semanas (RAG, agents, eval, monitoring)', referente: 'DataTalksClub', credencial: 'Curso gratis con proyecto final desplegable', tipo: 'curso', url: 'https://github.com/DataTalksClub/llm-zoomcamp', gratis: 'gratis', duracion: '10 semanas + proyecto', nivel: 'intermedio', porQue: 'Hilo conductor y fuente de proyectos de portafolio: RAG, vector search, embeddings, agentes, function calling, evaluación y monitoring → un sistema público en GitHub' },

  // F4 — Agentes & LLM engineering (el corazón)
  claudeApi: { nombre: 'Building with the Claude API', referente: 'Anthropic Academy', credencial: 'El curso TRONCAL de la academia para developers', tipo: 'curso', url: 'https://anthropic.skilljar.com/claude-with-the-anthropic-api', gratis: 'gratis', duracion: '8 secciones (API, evals, tools, RAG, MCP)', nivel: 'intermedio', porQue: 'Cubre exactamente los skills que los puestos de Anthropic listan', audio: true },
  promptTutorial: { nombre: 'Prompt Engineering Interactive Tutorial', referente: 'Anthropic (GitHub oficial)', credencial: 'Repo oficial · 36.3k estrellas', tipo: 'tutorial', url: 'https://github.com/anthropics/prompt-eng-interactive-tutorial', gratis: 'gratis (tokens aparte)', duracion: '9 capítulos', nivel: 'base', porQue: 'El estándar de oro de prompting según la propia Anthropic', audio: true },
  anthropicCourses: { nombre: 'anthropics/courses (API, Prompt Eng, Evals, Tool Use)', referente: 'Anthropic (GitHub oficial)', credencial: 'Repo educativo oficial · 21.8k estrellas', tipo: 'tutorial', url: 'https://github.com/anthropics/courses', gratis: 'gratis (tokens aparte)', duracion: '5 cursos en notebooks', nivel: 'intermedio', porQue: '"Prompt Evaluations" es ORO: evals aparece en casi todos los puestos de Anthropic' },
  mcpIntro: { nombre: 'Introduction to Model Context Protocol', referente: 'Anthropic Academy', credencial: 'Curso oficial de la creadora del estándar MCP', tipo: 'curso', url: 'https://anthropic.skilljar.com/introduction-to-model-context-protocol', gratis: 'gratis', duracion: '13 lecciones', nivel: 'intermedio', porQue: 'MCP aparece textualmente en los requisitos de los puestos Applied AI', audio: true },
  mcpAdvanced: { nombre: 'MCP: Advanced Topics', referente: 'Anthropic Academy', credencial: 'Curso oficial de Anthropic', tipo: 'curso', url: 'https://anthropic.skilljar.com/model-context-protocol-advanced-topics', gratis: 'gratis', duracion: '14 lecciones', nivel: 'avanzado', porQue: 'Sampling, transports, producción — diferencia a un candidato técnico' },
  claudeCodeAction: { nombre: 'Claude Code in Action', referente: 'Anthropic Academy', credencial: 'Curso oficial destacado en anthropic.com/learn', tipo: 'curso', url: 'https://anthropic.skilljar.com/claude-code-in-action', gratis: 'gratis', duracion: '~20 lecciones', nivel: 'intermedio', porQue: 'Cómo está construido un agente de código real (el de Anthropic)', audio: true },
  agentSkills: { nombre: 'Intro to agent skills + Intro to subagents', referente: 'Anthropic Academy', credencial: 'Cursos oficiales de las primitivas más nuevas', tipo: 'curso', url: 'https://anthropic.skilljar.com/introduction-to-agent-skills', gratis: 'gratis', duracion: '6 + 4 módulos', nivel: 'avanzado', porQue: 'Skills y subagentes: las piezas más recientes del stack de agentes' },
  agentSdk: { nombre: 'Claude Agent SDK (documentación oficial)', referente: 'Anthropic', credencial: 'Claude Code como librería (Python/TS)', tipo: 'docs', url: 'https://code.claude.com/docs/en/agent-sdk/overview', gratis: 'gratis (uso consume API)', duracion: 'overview + hooks, subagents, MCP', nivel: 'avanzado', porQue: 'El proyecto-portfolio nivel-Anthropic se construye con esto', audio: true },
  evalsDocs: { nombre: 'Define success criteria & build evals (Claude Docs)', referente: 'Anthropic (docs oficiales)', credencial: 'La guía de referencia de evaluaciones', tipo: 'docs', url: 'https://platform.claude.com/docs/en/docs/test-and-evaluate/develop-tests', gratis: 'gratis', duracion: '~30 min + código', nivel: 'intermedio', porQue: 'La habilidad que separa amateur de ingeniero LLM', audio: true },
  hfAgents: { nombre: 'Hugging Face Agents Course', referente: 'Hugging Face', credencial: 'La plataforma central del open-source en IA', tipo: 'curso', url: 'https://huggingface.co/learn/agents-course/unit0/introduction', gratis: 'gratis (2 certificados)', duracion: '5 unidades + 3 bonus', nivel: 'base', porQue: 'El curso gratuito de agentes más completo: smolagents, LlamaIndex, LangGraph, evals' },
  hfLlm: { nombre: 'Hugging Face LLM Course', referente: 'Hugging Face', credencial: 'Creadores de la librería Transformers', tipo: 'curso', url: 'https://huggingface.co/learn/llm-course/chapter1/1', gratis: 'gratis', duracion: '12 capítulos', nivel: 'base', porQue: 'El "por qué" detrás de los agentes: transformers, tokenizers, fine-tuning' },
  dlaiMcp: { nombre: 'MCP: Build Rich-Context AI Apps with Anthropic', referente: 'Elie Schoppik (Anthropic) × DeepLearning.AI', credencial: 'Head of Technical Education de Anthropic en la plataforma de Andrew Ng', tipo: 'curso', url: 'https://www.deeplearning.ai/short-courses/mcp-build-rich-context-ai-apps-with-anthropic/', gratis: 'gratis (beta)', duracion: '1 h 38 min', nivel: 'intermedio', porQue: 'MCP enseñado por Anthropic en vídeos de ~10 min — perfecto para huecos', audio: true },
  dlaiComputerUse: { nombre: 'Building toward Computer Use with Anthropic', referente: 'Colt Steele (Anthropic) × DeepLearning.AI', credencial: 'Head of Curriculum de Anthropic', tipo: 'curso', url: 'https://www.deeplearning.ai/short-courses/building-toward-computer-use-with-anthropic/', gratis: 'gratis (beta)', duracion: '1 h 37 min', nivel: 'base', porQue: 'La rampa oficial: prompting → tool use → caching → computer use', audio: true },
  dlaiClaudeCode: { nombre: 'Claude Code: A Highly Agentic Coding Assistant', referente: 'Anthropic × DeepLearning.AI', credencial: 'Curso oficial conjunto', tipo: 'curso', url: 'https://www.deeplearning.ai/short-courses/claude-code-a-highly-agentic-coding-assistant/', gratis: 'gratis (beta)', duracion: '1 h 50 min', nivel: 'intermedio', porQue: 'Contexto, MCP servers, git worktrees, sesiones paralelas en producción', audio: true },
  dlaiLanggraph: { nombre: 'AI Agents in LangGraph', referente: 'Harrison Chase (CEO LangChain) × DeepLearning.AI', credencial: 'El creador de la herramienta', tipo: 'curso', url: 'https://www.deeplearning.ai/short-courses/ai-agents-in-langgraph/', gratis: 'gratis (beta)', duracion: '1 h 32 min', nivel: 'intermedio', porQue: 'Agente desde cero en Python y luego con LangGraph, por su creador', audio: true },
  langchainAcademy: { nombre: 'LangChain Academy: Intro to LangGraph', referente: 'LangChain', credencial: 'Academia oficial', tipo: 'curso', url: 'https://academy.langchain.com/courses/intro-to-langgraph', gratis: 'gratis', duracion: '55 lecciones · ~6 h', nivel: 'intermedio', porQue: 'Estado, memoria, human-in-the-loop, sub-grafos y despliegue de agentes' },
  n8nLevelOne: { nombre: 'n8n Course: Level One', referente: 'n8n (docs oficiales)', credencial: 'Curso oficial del equipo de n8n', tipo: 'tutorial', url: 'https://docs.n8n.io/courses/level-one/', gratis: 'gratis', duracion: '7 capítulos', nivel: 'base', porQue: 'Sistematiza lo que YA haces con el motor APEX', audio: true },
  n8nAdvancedAi: { nombre: 'n8n Advanced AI (agents + LangChain en n8n)', referente: 'n8n (docs oficiales)', credencial: 'Docs oficiales sección Advanced AI', tipo: 'docs', url: 'https://docs.n8n.io/advanced-ai/', gratis: 'gratis', duracion: 'referencia + tutoriales', nivel: 'intermedio', porQue: 'Conecta el motor APEX con agentes, vector stores, memoria y RAG' },
  openaiCookbook: { nombre: 'OpenAI Cookbook', referente: 'OpenAI (oficial)', credencial: 'Repo oficial · ~74k estrellas', tipo: 'docs', url: 'https://github.com/openai/openai-cookbook', gratis: 'gratis (tokens aparte)', duracion: 'cientos de notebooks', nivel: 'intermedio', porQue: 'Recetas de producción: agentes, evals, guardrails, tool use' },
  openaiAgentsGuide: { nombre: 'A Practical Guide to Building Agents (PDF)', referente: 'OpenAI (oficial)', credencial: 'Guía corporativa oficial', tipo: 'docs', url: 'https://cdn.openai.com/business-guides-and-resources/a-practical-guide-to-building-agents.pdf', gratis: 'gratis', duracion: '34 páginas', nivel: 'base', porQue: 'Orquestación single/multi-agente y guardrails — el complemento al ensayo de Anthropic', audio: true },
  aiEngineering: { nombre: 'AI Engineering (libro)', referente: 'Chip Huyen', credencial: 'Stanford (CS329S) · ex-NVIDIA/Snorkel/Netflix', tipo: 'libro', url: 'https://huyenchip.com/books/', gratis: '~$40-55 (audiolibro Audible)', duracion: '~500 págs · 10 caps', nivel: 'intermedio', porQue: 'EL libro de referencia de apps con LLMs: evals, RAG, agentes, inferencia', audio: true },
  raschkaLlm: { nombre: 'Build a Large Language Model (From Scratch)', referente: 'Sebastian Raschka', credencial: 'Ex-profesor UW-Madison · Lightning AI', tipo: 'libro', url: 'https://www.manning.com/books/build-a-large-language-model-from-scratch', gratis: '~$35 (código gratis en GitHub)', duracion: '7 capítulos + notebooks', nivel: 'avanzado', porQue: 'Construyes un GPT completo: entiendes el LLM por dentro, no solo lo consumes' },
  aheadOfAi: { nombre: 'Ahead of AI (Substack)', referente: 'Sebastian Raschka', credencial: '194k+ suscriptores investigadores', tipo: 'podcast', url: 'https://magazine.sebastianraschka.com/', gratis: 'parcial', duracion: '1-2 artículos/mes', nivel: 'intermedio', porQue: 'Investigación LLM al día, explicada por un educador de élite', audio: true },

  // F5 — Ciberseguridad
  owaspTop10: { nombre: 'OWASP Top 10 (Web Application Security)', referente: 'OWASP Foundation', credencial: 'El consenso estándar de la industria', tipo: 'docs', url: 'https://owasp.org/www-project-top-ten/', gratis: 'gratis', duracion: '2-4 h lectura', nivel: 'base', porQue: 'El vocabulario común de toda la ciberseguridad de aplicaciones', audio: true },
  owaspLlm: { nombre: 'OWASP Top 10 for LLM Applications', referente: 'OWASP Gen AI Security Project', credencial: 'El marco canónico de riesgos de LLMs', tipo: 'docs', url: 'https://genai.owasp.org/llm-top-10/', gratis: 'gratis (también en español)', duracion: '2-3 h lectura', nivel: 'intermedio', porQue: 'LA pieza clave del perfil ciberseguridad+IA: prompt injection, excessive agency…', audio: true },
  portswigger: { nombre: 'Web Security Academy', referente: 'PortSwigger', credencial: 'Creadores de Burp Suite', tipo: 'tutorial', url: 'https://portswigger.net/web-security', gratis: 'gratis 100%', duracion: '30+ temas · 100-200 h', nivel: 'base', porQue: 'El estándar de facto de seguridad web práctica desde cero' },
  webLlmAttacks: { nombre: 'Web LLM attacks (Web Security Academy)', referente: 'PortSwigger', credencial: 'Tema oficial de la Academy', tipo: 'tutorial', url: 'https://portswigger.net/web-security/llm-attacks', gratis: 'gratis', duracion: 'teoría + labs', nivel: 'intermedio', porQue: 'Puente directo: atacar LLMs integrados en aplicaciones reales', audio: true },
  willisonPi: { nombre: 'Serie "Prompt injection" (2022-2025)', referente: 'Simon Willison', credencial: 'Co-creador de Django; quien acuñó el término', tipo: 'playlist', url: 'https://simonwillison.net/series/prompt-injection/', gratis: 'gratis', duracion: '~20 artículos de 10-20 min', nivel: 'intermedio', porQue: 'La crónica de referencia de la vulnerabilidad #1 de los LLMs', audio: true },
  lethalTrifecta: { nombre: 'The lethal trifecta for AI agents', referente: 'Simon Willison', credencial: 'El artículo más citado sobre seguridad de agentes', tipo: 'docs', url: 'https://simonwillison.net/2025/Jun/16/the-lethal-trifecta/', gratis: 'gratis', duracion: '15 min', nivel: 'intermedio', porQue: 'El marco mental: datos privados + contenido no confiable + comunicación externa', audio: true },
  cs253: { nombre: 'Stanford CS253: Web Security (curso completo)', referente: 'Feross Aboukhadijeh · Stanford', credencial: 'Instructor de Stanford, fundador de Socket', tipo: 'playlist', url: 'https://www.youtube.com/playlist?list=PLMF2PpA06Sb26oYT-dfNOt3Y4wwoLAho0', gratis: 'gratis', duracion: '~20 lecciones · ~80 min', nivel: 'intermedio', porQue: 'El curso universitario de referencia en seguridad web — funciona casi como podcast', audio: true },
  tryhackme: { nombre: 'TryHackMe: Pre Security + Jr Penetration Tester', referente: 'TryHackMe', credencial: 'Plataforma líder (3M+ usuarios)', tipo: 'tutorial', url: 'https://tryhackme.com/paths', gratis: 'parcial ($16.99/mes premium)', duracion: '~40 h + ~50-60 h', nivel: 'base', porQue: 'La rampa de entrada más guiada: redes, Linux, primeros ataques' },
  htbAiRedTeam: { nombre: 'HTB Academy: AI Red Teamer (con Google)', referente: 'Hack The Box + Google', credencial: 'Alineado con el Secure AI Framework de Google', tipo: 'curso', url: 'https://academy.hackthebox.com/path/preview/ai-red-teamer', gratis: 'parcial', duracion: '12 módulos · 230 secciones', nivel: 'avanzado', porQue: 'La única ruta estructurada de red teaming de IA hecha con un gigante' },
  manyShotJb: { nombre: 'Many-shot jailbreaking (research)', referente: 'Anthropic', credencial: 'Investigación oficial del equipo de seguridad', tipo: 'docs', url: 'https://www.anthropic.com/research/many-shot-jailbreaking', gratis: 'gratis', duracion: '15-20 min', nivel: 'intermedio', porQue: 'Cómo se rompe un LLM con contexto largo, por quien construye los modelos', audio: true },
  constClassifiers: { nombre: 'Constitutional Classifiers (research)', referente: 'Anthropic', credencial: 'Investigación oficial (feb-2025)', tipo: 'docs', url: 'https://www.anthropic.com/research/constitutional-classifiers', gratis: 'gratis', duracion: '15-20 min', nivel: 'avanzado', porQue: 'El estado del arte en DEFENSA de LLMs — la otra mitad del perfil', audio: true },
  rsp: { nombre: 'Responsible Scaling Policy (ASL levels)', referente: 'Anthropic', credencial: 'El marco de gobernanza de riesgos más citado', tipo: 'docs', url: 'https://www.anthropic.com/news/anthropics-responsible-scaling-policy', gratis: 'gratis', duracion: '15 min', nivel: 'intermedio', porQue: 'Los AI Safety Levels son lenguaje obligatorio a nivel estratégico', audio: true },

  // F6 — Nivel Fellows
  rlhfBook: { nombre: 'RLHF Book (post-training de LLMs)', referente: 'Nathan Lambert · Allen Institute for AI', credencial: 'Referencia mundial en post-training (ex-HuggingFace)', tipo: 'libro', url: 'https://rlhfbook.com/', gratis: 'gratis online', duracion: 'instruction tuning, reward models, DPO/PPO', nivel: 'avanzado', porQue: 'Anthropic existe gracias al post-training — el vocabulario diario del Fellows', audio: true },
  arena: { nombre: 'ARENA 3.0 (Alignment Research Engineer Accelerator)', referente: 'Callum McDougall → Google DeepMind', credencial: 'EL material con el que la comunidad se prepara para MATS/Fellows', tipo: 'tutorial', url: 'https://github.com/callummcdougall/ARENA_3.0', gratis: 'gratis (open source)', duracion: '4 capítulos: PyTorch, mech interp, RL, evals', nivel: 'avanzado', porQue: 'Prep directa del Fellows Program: transformers desde cero + interpretabilidad' },
  fsdl: { nombre: 'Full Stack Deep Learning (Course 2022)', referente: 'Frye, Karayev, Tobin · UC Berkeley', credencial: 'El curso de MLOps nacido en Berkeley', tipo: 'curso', url: 'https://fullstackdeeplearning.com/course/2022/', gratis: 'gratis', duracion: '9 lectures + labs', nivel: 'avanzado', porQue: 'Desplegar y mantener en producción, no solo entrenar en un notebook' },
  mit6006: { nombre: 'MIT 6.006: Introduction to Algorithms', referente: 'Demaine, Ku, Solomon · MIT', credencial: 'MIT OpenCourseWare oficial', tipo: 'curso', url: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/', gratis: 'gratis', duracion: 'vídeos + psets con soluciones', nivel: 'avanzado', porQue: 'Las entrevistas de los labs incluyen coding screens con DSA' },
  cs50w: { nombre: 'CS50W: Web Programming with Python & JavaScript', referente: 'Brian Yu & Malan · Harvard', credencial: 'Continuación oficial de CS50x', tipo: 'curso', url: 'https://cs50.harvard.edu/web/', gratis: 'gratis', duracion: 'Django, React, SQL, escalabilidad', nivel: 'intermedio', porQue: 'Todo producto de IA real es una app web alrededor de un modelo' },
  cs229: { nombre: 'Stanford CS229: Machine Learning (Andrew Ng)', referente: 'Andrew Ng · Stanford', credencial: 'EL curso canónico de ML', tipo: 'playlist', url: 'https://www.youtube.com/playlist?list=PLoROMvodv4rMiGQp3WXShtMGgzqpfVfbU', gratis: 'gratis', duracion: '20 lectures · ~26 h', nivel: 'avanzado', porQue: 'La teoría matemática que Anthropic da por sentada en entrevistas' },
  cs224n: { nombre: 'Stanford CS224N: NLP with Deep Learning', referente: 'Christopher Manning · Stanford', credencial: 'Director del Stanford AI Lab', tipo: 'playlist', url: 'https://www.youtube.com/playlist?list=PLoROMvodv4rOSH4v6133s9LFPRHjEmbmJ', gratis: 'gratis', duracion: '~20 lectures · ~25 h', nivel: 'avanzado', porQue: 'La base teórica directa de los LLMs: transformers y attention' },
  cs25: { nombre: 'Stanford CS25: Transformers United', referente: 'Stanford Online', credencial: 'Seminario con ponentes de los grandes labs', tipo: 'playlist', url: 'https://www.youtube.com/playlist?list=PLoROMvodv4rNiJRchCzutFw5ItR_Z27CM', gratis: 'gratis', duracion: 'charlas de ~60 min', nivel: 'avanzado', porQue: 'Estado del arte contado por quienes lo construyen — funciona como audio', audio: true },
  mlSpec: { nombre: 'Machine Learning Specialization', referente: 'Andrew Ng · DeepLearning.AI', credencial: 'El curso de ML más influyente de la historia', tipo: 'curso', url: 'https://www.coursera.org/specializations/machine-learning-introduction', gratis: '$49/mes (ayuda financiera disponible)', duracion: '3 cursos · ~95 h', nivel: 'avanzado', porQue: 'ML completo por el referente nº1 en educación de IA', audio: true },
  fellows: { nombre: 'Anthropic Fellows Program (LA BECA)', referente: 'Anthropic Alignment Science', credencial: 'Programa oficial con mentores de Anthropic', tipo: 'beca', url: 'https://alignment.anthropic.com/2025/anthropic-fellows-program-2026/', gratis: 'PAGAN: $3,850/semana + ~$15k/mes cómputo', duracion: '4 meses full-time', nivel: 'avanzado', porQue: 'NO pide PhD ni papers ni ML previo: pide Python fluido + ejecución + motivación por AI safety' },
  // ★ 2026 — DPO: el estándar de alineación en producción (desplazó a RLHF/PPO)
  dpoPaper: { nombre: 'Direct Preference Optimization (Rafailov et al., 2023)', referente: 'Stanford (Rafailov, Ermon, Manning, Finn)', credencial: 'El paper que reemplazó RLHF por DPO en producción', tipo: 'docs', url: 'https://arxiv.org/abs/2305.18290', gratis: 'gratis', duracion: '~20 páginas', nivel: 'avanzado', porQue: 'GAP 2026: DPO desplazó a RLHF/PPO como estándar de alineación (CS336-2026 enseña SFT+RL+DPO). Cierra el salto de "entiendo RLHF" a "lo que se usa hoy" — leer de la fuente + el capítulo DPO del RLHF Book', audio: true },
  // ★ 2026 — Ruta JAX mínima (Anthropic entrena en JAX; RE valora JAX/PyTorch)
  jaxQuickstart: { nombre: 'JAX — Quickstart + Flax (para LLMs)', referente: 'Google DeepMind (JAX/Flax)', credencial: 'El stack en el que Anthropic entrena Claude', tipo: 'docs', url: 'https://docs.jax.dev/en/latest/quickstart.html', gratis: 'gratis', duracion: 'quickstart + tutoriales', nivel: 'avanzado', porQue: 'GAP hard de Anthropic RE: hoy la ruta es 100% PyTorch. Un ancla JAX (jit/grad/vmap + Flax) diferencia para el objetivo Fellows/RE — Anthropic entrena en JAX' },

  // Audio para huecos
  lexDario: { nombre: 'Lex Fridman #452 — Dario Amodei (CEO Anthropic)', referente: 'Lex Fridman (MIT) + Dario Amodei', credencial: 'La entrevista más profunda al CEO de Anthropic (+ Olah y Askell)', tipo: 'podcast', url: 'https://lexfridman.com/dario-amodei', gratis: 'gratis', duracion: '~5 h (trocear con timestamps)', nivel: 'intermedio', porQue: 'Visión interna directa: scaling, seguridad, interpretabilidad, carácter de Claude', audio: true },
  dwarkeshDario: { nombre: 'Dwarkesh — Dario Amodei', referente: 'Dwarkesh Patel + Dario Amodei', credencial: 'El entrevistador técnico de referencia de los labs', tipo: 'podcast', url: 'https://www.dwarkesh.com/p/dario-amodei', gratis: 'gratis', duracion: '1 h 58 min', nivel: 'intermedio', porQue: 'Más denso y técnico que la versión de Lex', audio: true },
  lexKarpathy: { nombre: 'Lex Fridman #333 — Andrej Karpathy', referente: 'Lex Fridman + Karpathy', credencial: 'Fundador de OpenAI · ex-Tesla', tipo: 'podcast', url: 'https://lexfridman.com/andrej-karpathy', gratis: 'gratis', duracion: '~3.5 h', nivel: 'intermedio', porQue: 'El mejor traductor de deep learning a intuición', audio: true },
  dwarkeshInterp: { nombre: 'Dwarkesh — Sholto & Trenton: How LLMs actually think', referente: 'Dwarkesh + Bricken (Anthropic) & Douglas', credencial: 'Interpretabilidad mecanicista desde dentro de los labs', tipo: 'podcast', url: 'https://www.dwarkesh.com/p/sholto-douglas-trenton-bricken', gratis: 'gratis', duracion: '3 h 12 min (denso)', nivel: 'avanzado', porQue: 'Superposición e in-context learning — el nivel mental al que apuntas', audio: true },
  dwarkeshDemis: { nombre: 'Dwarkesh — Demis Hassabis (DeepMind)', referente: 'Dwarkesh + Hassabis', credencial: 'Premio Nobel de Química 2024 (AlphaFold)', tipo: 'podcast', url: 'https://www.dwarkesh.com/p/demis-hassabis', gratis: 'gratis', duracion: '1 h', nivel: 'intermedio', porQue: 'IA × ciencia (AlphaFold) — directo a tu perfil médico-investigador', audio: true },
  latentSpace: { nombre: 'Latent Space — The AI Engineer Podcast', referente: 'swyx + Alessio Fanelli', credencial: 'swyx acuñó el término "AI Engineer"', tipo: 'podcast', url: 'https://www.latent.space/', gratis: 'gratis', duracion: '60-90 min, semanal', nivel: 'avanzado', porQue: 'El único podcast 100% de AI engineering aplicado: el rol al que aspiras', audio: true },
  noPriors: { nombre: 'No Priors (Sarah Guo + Elad Gil)', referente: 'Sarah Guo (Conviction) + Elad Gil', credencial: 'Inversores top de IA', tipo: 'podcast', url: 'https://podcasts.apple.com/us/podcast/no-priors-artificial-intelligence-technology-startups/id1668002688', gratis: 'gratis', duracion: '22-56 min, semanal', nivel: 'base', porQue: 'El mejor ratio insight/minuto para huecos + ángulo de negocio (Pulso)', audio: true },
  anthropicYt: { nombre: 'Canal oficial de Anthropic (YouTube)', referente: 'Anthropic', credencial: 'Canal corporativo oficial', tipo: 'video', url: 'https://www.youtube.com/@anthropic-ai', gratis: 'gratis', duracion: 'vídeos 5-60 min', nivel: 'intermedio', porQue: 'Empieza por "AI prompt engineering: A deep dive" — vocabulario y cultura de la empresa meta', audio: true },
  dlaiYt: { nombre: 'Canal DeepLearning.AI (charlas de Ng)', referente: 'Andrew Ng · DeepLearning.AI', credencial: 'Organización educativa de Ng', tipo: 'video', url: 'https://www.youtube.com/@Deeplearningai', gratis: 'gratis', duracion: '5-60 min', nivel: 'base', porQue: 'Píldoras de Ng — puente entre podcasts y cursos formales', audio: true },
  theBatch: { nombre: 'The Batch (newsletter semanal)', referente: 'Andrew Ng · DeepLearning.AI', credencial: 'Con "Andrew’s Letters" del propio Ng', tipo: 'docs', url: 'https://www.deeplearning.ai/the-batch/', gratis: 'gratis', duracion: '~10 min/semana', nivel: 'base', porQue: 'El filtro de noticias de IA con más criterio — sustituye doomscrolling', audio: true },
  realPython: { nombre: 'Real Python (tutoriales + podcast)', referente: 'Real Python', credencial: 'Referencia editorial seria del ecosistema', tipo: 'podcast', url: 'https://realpython.com/', gratis: 'parcial', duracion: 'semanal', nivel: 'intermedio', porQue: 'El único recurso 100% audio para mantener inmersión Python sin pantalla', audio: true },
  // ── Ruta élite 2026: CS-core (teachyourselfcs) — base sólida de ingeniero (verificado 18-jun) ──
  teachYourselfCs: { nombre: 'Teach Yourself CS — la guía canónica del autodidacta', referente: 'Bradfield CS', credencial: 'El estándar de los ingenieros self-taught que llegan a FAANG/labs', tipo: 'docs', url: 'https://teachyourselfcs.com/', gratis: 'gratis', duracion: '9 materias, libro+curso c/u', nivel: 'base', porQue: 'Mapa de los 9 pilares CS-core: muestra qué ya cubres vs qué falta para nivel ingeniero, no solo "AI-app builder"', audio: true },
  composingPrograms: { nombre: 'Composing Programs (SICP en Python · base de Berkeley CS61A)', referente: 'John DeNero · UC Berkeley', credencial: 'El pilar #1 de teachyourselfcs adaptado a Python', tipo: 'libro', url: 'https://www.composingprograms.com/', gratis: 'gratis', duracion: 'texto leíble en móvil', nivel: 'intermedio', porQue: 'El salto de "sé escribir Python" a "pienso como ingeniero": abstracción, paradigmas y complejidad', audio: true },
  ostep: { nombre: 'Operating Systems: Three Easy Pieces (OSTEP)', referente: 'Arpaci-Dusseau · Wisconsin', credencial: 'El libro de SO recomendado por teachyourselfcs', tipo: 'libro', url: 'https://pages.cs.wisc.edu/~remzi/OSTEP/', gratis: 'gratis', duracion: 'PDF por capítulos', nivel: 'intermedio', porQue: 'El pilar hoy ausente: virtualización, concurrencia (threads/locks), persistencia — qué pasa cuando un agente corre procesos o un modelo entrena en paralelo', audio: true },
  nand2tetris: { nombre: 'Nand2Tetris — The Elements of Computing Systems', referente: 'Nisan & Schocken', credencial: 'Usado en 400+ universidades', tipo: 'curso', url: 'https://www.nand2tetris.org/', gratis: 'gratis', duracion: 'proyecto largo (bloque PC)', nivel: 'intermedio', porQue: 'Construyes un computador de compuertas a SO+compilador: llena el hueco entre "Python" y "redes neuronales" (qué ES una máquina)' },
  csapp: { nombre: "Computer Systems: A Programmer's Perspective (CSAPP) + labs", referente: "Bryant & O'Hallaron · CMU", credencial: 'El texto de arquitectura/sistemas primario de teachyourselfcs', tipo: 'libro', url: 'https://csapp.cs.cmu.edu/', gratis: 'gratis', duracion: 'labs (bomb lab, etc.)', nivel: 'avanzado', porQue: 'Representación de datos, jerarquía de memoria, linking, memoria virtual — nivel systems engineer real' },
  kuroseRoss: { nombre: 'Computer Networking: A Top-Down Approach (companion gratis)', referente: 'Kurose & Ross', credencial: 'El libro de redes canónico (9ª ed. 2025)', tipo: 'libro', url: 'https://gaia.cs.umass.edu/kurose_ross/index.php', gratis: 'gratis', duracion: 'lecturas + Wireshark labs', nivel: 'intermedio', porQue: 'El pilar "redes" (TCP/IP, congestión, routing) — base de "distributed systems" que piden las vacantes de Anthropic', audio: true },
  cs144: { nombre: 'Stanford CS144: Introduction to Computer Networking', referente: 'Levis & McKeown · Stanford', credencial: 'Curso de redes recomendado por teachyourselfcs', tipo: 'curso', url: 'https://cs144.github.io/', gratis: 'gratis', duracion: 'labs: implementar TCP + un router (PC)', nivel: 'avanzado', porQue: 'Complemento práctico a Kurose-Ross; los labs son un proyecto de portfolio brutal' },
  mit6042: { nombre: 'MIT 6.042J Mathematics for Computer Science (OCW)', referente: 'Tom Leighton · MIT', credencial: 'La "Math for CS" canónica de teachyourselfcs', tipo: 'curso', url: 'https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/', gratis: 'gratis', duracion: 'vídeos + textbook', nivel: 'intermedio', porQue: 'Lógica, demostraciones, grafos, conteo y probabilidad discreta — la base formal que sostiene los algoritmos', audio: true },
  skiena: { nombre: 'The Algorithm Design Manual (Skiena) + CSE373', referente: 'Steven Skiena · Stony Brook', credencial: 'El libro de algoritmos #1 de teachyourselfcs para self-learners', tipo: 'libro', url: 'https://www.algorist.com/', gratis: 'gratis', duracion: 'lecture videos + solution wiki', nivel: 'avanzado', porQue: 'Más práctico que CLRS; complemento de MIT 6.006 para la prep de coding screens de los labs' },
  // ── Frontier-lab avanzado: RL · papers seminales · interpretabilidad (F3-F7) ──
  spinningUp: { nombre: 'Spinning Up in Deep RL (OpenAI)', referente: 'OpenAI', credencial: 'El onboarding de RL que OpenAI escribió para sus propios research engineers', tipo: 'curso', url: 'https://spinningup.openai.com/en/latest/', gratis: 'gratis', duracion: 'intro + 6 algoritmos con código', nivel: 'avanzado', porQue: 'Cierra el hueco de RL (PPO/reward models) que el RLHF Book asume ya sabido — corazón del post-training de Anthropic' },
  attentionPaper: { nombre: 'Attention Is All You Need (Vaswani et al., 2017)', referente: 'Google Brain', credencial: 'El paper seminal del Transformer', tipo: 'docs', url: 'https://arxiv.org/abs/1706.03762', gratis: 'gratis', duracion: '~15 páginas', nivel: 'avanzado', porQue: 'Vocabulario obligatorio en cualquier entrevista de frontier-lab: leerlo de la fuente, no de un resumen', audio: true },
  annotatedTransformer: { nombre: 'The Annotated Transformer (Harvard NLP)', referente: 'Harvard NLP', credencial: 'Implementación PyTorch línea-a-línea del paper', tipo: 'tutorial', url: 'https://github.com/harvardnlp/annotated-transformer', gratis: 'gratis', duracion: 'notebook ejecutable', nivel: 'avanzado', porQue: 'El puente entre el paper y construir-desde-cero (Karpathy/CS336): cada ecuación convertida en código' },
  lilLog: { nombre: "Lil'Log — blog de Lilian Weng", referente: 'Lilian Weng (ex-VP Research OpenAI)', credencial: 'La referencia que leen los ingenieros de los labs', tipo: 'docs', url: 'https://lilianweng.github.io/', gratis: 'gratis', duracion: 'deep-dives', nivel: 'avanzado', porQue: 'Canónicos sobre RL, reward hacking, hallucination y agentes — fuente primaria de frontier', audio: true },
  mlEngineering: { nombre: 'ML Engineering Open Book (Stas Bekman)', referente: 'Stas Bekman (entrenó BLOOM-176B)', credencial: 'Quien entrenó modelos de 176B parámetros', tipo: 'libro', url: 'https://github.com/stas00/ml-engineering', gratis: 'gratis', duracion: 'PDF/EPUB', nivel: 'avanzado', porQue: 'Distributed systems / data pipelines reales: paralelismo, multi-GPU, SLURM, debugging de training a escala — sustituto moderno de FSDL-2022' },
  neelNanda: { nombre: 'How to become a mechanistic interpretability researcher', referente: 'Neel Nanda · lead interp DeepMind', credencial: 'Guía-mapa del lead de interpretabilidad de Google DeepMind (2025)', tipo: 'docs', url: 'https://www.alignmentforum.org/posts/jP9KDyMkchuv6tHwm/how-to-become-a-mechanistic-interpretability-researcher', gratis: 'gratis', duracion: 'lectura larga', nivel: 'avanzado', porQue: 'El manual de ruta para el Fellows: básicos → mini-proyectos → research + cómo encontrar mentores', audio: true },
  biologyLlm: { nombre: 'On the Biology of a Large Language Model (Anthropic)', referente: 'Anthropic Interpretability', credencial: 'Paper navegable de transformer-circuits.pub (2025)', tipo: 'docs', url: 'https://transformer-circuits.pub/2025/attribution-graphs/biology.html', gratis: 'gratis', duracion: 'interactivo', nivel: 'avanzado', porQue: 'Attribution graphs sobre Claude 3.5 Haiku con un caso de DIAGNÓSTICO MÉDICO — encaja con tu perfil; artefacto-ancla de interpretabilidad' },
  bluedotAlignment: { nombre: 'AI Alignment Course (BlueDot Impact)', referente: 'BlueDot Impact', credencial: 'El currículo conceptual de alignment de referencia', tipo: 'curso', url: 'https://bluedot.org/courses/alignment', gratis: 'parcial', duracion: '12 unidades', nivel: 'avanzado', porQue: 'RLHF, scalable oversight, mech interp, governance — el marco conceptual que complementa ARENA (ingeniería) para el Fellows' },
  hfDeepRl: { nombre: 'Hugging Face Deep RL Course', referente: 'Hugging Face', credencial: 'Curso práctico con notebooks + certificado', tipo: 'curso', url: 'https://huggingface.co/learn/deep-rl-course/unit0/introduction', gratis: 'gratis', duracion: 'lecciones cortas (Colab)', nivel: 'intermedio', porQue: 'La rampa práctica de RL que precede a Spinning Up — encaja en 30 min/día (nota: algunas units en low-maintenance)' },
  // ── Backend de producción: el "software de verdad" (verificado 18-jun, roadmap multi-año en DATA/SYNAPSE/ROADMAP_SENIOR_MULTIANIO.md) ──
  roadmapBackend: { nombre: 'roadmap.sh — Backend Developer Roadmap', referente: 'roadmap.sh', credencial: 'El mapa-brújula canónico (2.8M usuarios)', tipo: 'docs', url: 'https://roadmap.sh/backend', gratis: 'gratis', duracion: 'mapa visual', nivel: 'base', porQue: 'QUÉ aprender y en qué orden para backend moderno (lenguaje→DB→APIs→auth→caching→escalabilidad). El índice maestro del carril backend.', audio: true },
  fastapiTut: { nombre: 'FastAPI — Tutorial oficial', referente: 'Sebastián Ramírez (tiangolo)', credencial: 'Del creador de FastAPI, estándar de APIs Python', tipo: 'docs', url: 'https://fastapi.tiangolo.com/tutorial/', gratis: 'gratis', duracion: 'secciones autocontenidas', nivel: 'intermedio', porQue: 'APIs Python modernas: params, Pydantic, dependencias, OAuth2/JWT, SQL, testing. El pilar APIs que faltaba; perfecto para 15\' de pantalla/día.' },
  djangoRest: { nombre: 'Django REST Framework — tutorial oficial', referente: 'Encode / DRF', credencial: 'El estándar "batteries-included" de APIs Python', tipo: 'docs', url: 'https://www.django-rest-framework.org/', gratis: 'gratis', duracion: 'tutorial 6 partes', nivel: 'intermedio', porQue: 'El otro camino de APIs (serializers, viewsets, auth, permisos). Da criterio para elegir framework. Opcional si priorizas FastAPI.' },
  postgresqlTut: { nombre: 'PostgreSQL — Tutorial oficial', referente: 'PostgreSQL Global Dev Group', credencial: 'La DB por defecto del backend serio (la de Supabase)', tipo: 'docs', url: 'https://www.postgresql.org/docs/current/tutorial.html', gratis: 'gratis', duracion: 'tutorial', nivel: 'intermedio', porQue: 'Tablas, joins, vistas, FKs, transacciones, window functions — eleva "datos" de intro a motor de producción.' },
  cs50sql: { nombre: 'CS50 Introduction to Databases with SQL (Harvard)', referente: 'Harvard CS50', credencial: 'Curso oficial de Harvard, gratis', tipo: 'curso', url: 'https://cs50.harvard.edu/sql/', gratis: 'gratis', duracion: '~7 semanas', nivel: 'intermedio', porQue: 'Modelado E-R, normalización, índices, transacciones, escalado SQLite→Postgres. El "pensar el esquema" que ningún framework enseña.', audio: true },
  pytest: { nombre: 'pytest — documentación oficial', referente: 'pytest', credencial: 'El framework de testing Python estándar', tipo: 'docs', url: 'https://docs.pytest.org/en/stable/', gratis: 'gratis', duracion: 'get started ~20 min', nivel: 'intermedio', porQue: 'Testing profesional: fixtures, parametrize, plugins. La habilidad #1 que separa código de juguete de código senior.', audio: true },
  testdriven: { nombre: 'TestDriven.io — backends de producción con TDD', referente: 'Michael Herman', credencial: 'Referente en backends Python de producción', tipo: 'tutorial', url: 'https://testdriven.io/', gratis: 'parcial', duracion: 'blog gratis + cursos $25-40', nivel: 'intermedio', porQue: 'FastAPI/Django + PostgreSQL + Docker + pytest + CI. El salto exacto de "tutorial" a "app desplegada".' },
  arjancodes: { nombre: 'ArjanCodes — diseño de software en Python', referente: 'Arjan Egges', credencial: 'El referente de diseño de software en Python', tipo: 'video', url: 'https://arjancodes.com/', gratis: 'parcial', duracion: 'vídeos 15-25 min', nivel: 'intermedio', porQue: 'Arquitectura, patrones, dependency injection, código limpio. El paso de "sé Python" a "diseño sistemas en Python". Apto como audio en viaje.', audio: true },
  mit6031: { nombre: 'MIT 6.031 Software Construction', referente: 'MIT', credencial: 'Curso del MIT (Spring 2022, público)', tipo: 'curso', url: 'https://web.mit.edu/6.031/', gratis: 'gratis', duracion: 'lecturas', nivel: 'avanzado', porQue: 'Cómo escribir código CORRECTO y mantenible: specs, ADTs, rep invariants, inmutabilidad, concurrencia. Ideal lectura 5\' + sábado de teclado.', audio: true },
  dockerGetStarted: { nombre: 'Docker — Get Started (oficial)', referente: 'Docker', credencial: 'El estándar de contenedores', tipo: 'docs', url: 'https://docs.docker.com/get-started/', gratis: 'gratis', duracion: 'guía', nivel: 'intermedio', porQue: 'DevOps básico: contenedores, imágenes, Dockerfile, Compose. De "corre en mi máquina" a "desplegable". Bloque PC del sábado.' },
  twelveFactor: { nombre: 'The Twelve-Factor App', referente: 'Adam Wiggins (Heroku)', credencial: 'El canon de apps desplegables', tipo: 'docs', url: 'https://12factor.net/', gratis: 'gratis', duracion: 'lectura corta', nivel: 'intermedio', porQue: 'Las 12 reglas (config por entorno, procesos stateless, logs…) de todo backend desplegable. El checklist mental de deployment. Lectura 5\'.', audio: true },
  sysDesignPrimer: { nombre: 'The System Design Primer (Donne Martin)', referente: 'Donne Martin (ex-Google/Amazon)', credencial: 'El recurso abierto #1 de system design (~354k★)', tipo: 'docs', url: 'https://github.com/donnemartin/system-design-primer', gratis: 'gratis', duracion: 'repo + flashcards Anki', nivel: 'avanzado', porQue: 'System design gratis: escalabilidad, caching, replicación/sharding, CAP + 8 problemas resueltos. La rampa antes de pagar nada (tiene README-es.md).', audio: true },
  bytebytego: { nombre: 'ByteByteGo (Alex Xu) — system design ilustrado', referente: 'Alex Xu', credencial: 'Autor de System Design Interview vol.1/2', tipo: 'curso', url: 'https://bytebytego.com/', gratis: 'parcial', duracion: 'newsletter/YouTube gratis + curso', nivel: 'avanzado', porQue: 'Diseño de sistemas escalables con diagramas memorables. Newsletter y canal (1M+) gratis. El estándar visual del sector.', audio: true },
  ddia: { nombre: 'Designing Data-Intensive Applications (Kleppmann)', referente: 'Martin Kleppmann (Cambridge)', credencial: 'EL canon de backend/datos senior', tipo: 'libro', url: 'https://dataintensive.net/', gratis: '~$45', duracion: 'libro (1-2 caps/mes)', nivel: 'avanzado', porQue: 'Modelos de datos, replicación, particionado, transacciones, consistencia, distribuidos. Citado en toda entrevista senior. Lectura de fondo Año 2-3.' },
  grokkingSD: { nombre: 'Grokking the Modern System Design Interview', referente: 'Educative', credencial: 'El curso de referencia de system-design interviews', tipo: 'curso', url: 'https://www.educative.io/courses/grokking-the-system-design-interview', gratis: 'pago', duracion: '204 lecciones', nivel: 'avanzado', porQue: 'Método RESHADED, casos YouTube/Uber/ChatGPT. SOLO al ir por entrevistas; gratis primero con System Design Primer + ByteByteGo.' },
  // ── Frontend & diseño web: el otro pilar full-stack (sirve también a las landings de AURUM) ──
  roadmapFrontend: { nombre: 'roadmap.sh — Frontend Developer Roadmap', referente: 'roadmap.sh', credencial: 'El mapa visual de referencia frontend', tipo: 'docs', url: 'https://roadmap.sh/frontend', gratis: 'gratis', duracion: 'mapa visual', nivel: 'base', porQue: 'Qué aprender y en qué orden para frontend pro. Brújula para marcar avance sin perderte.', audio: true },
  odinProject: { nombre: 'The Odin Project — Full Stack JavaScript', referente: 'The Odin Project', credencial: 'El currículo open-source canónico full-stack', tipo: 'curso', url: 'https://www.theodinproject.com/paths/full-stack-javascript', gratis: 'gratis', duracion: 'ruta completa project-based', nivel: 'base', porQue: 'Espina dorsal del frontend: HTML/CSS→JS→React→Node→hired. Cada proyecto = repo público para el portfolio que SYNAPSE exige.' },
  learnCssWebdev: { nombre: 'Google — Learn CSS (web.dev)', referente: 'Equipo de Chrome', credencial: 'El recurso definitivo de CSS moderno', tipo: 'curso', url: 'https://web.dev/learn/css', gratis: 'gratis', duracion: '40+ módulos cortos', nivel: 'base', porQue: 'Box model, flexbox, grid, tipografía, animaciones. Módulos cortos, ideales para 5\'/15\'.', audio: true },
  kevinPowell: { nombre: 'Kevin Powell — canal de CSS', referente: 'Kevin Powell', credencial: 'El "CSS evangelist" (+1000 vídeos)', tipo: 'video', url: 'https://www.kevinpowell.co/', gratis: 'gratis', duracion: 'vídeos cortos', nivel: 'base', porQue: 'Dominar layout moderno (flex/grid) en audio/vídeo de huecos. Subtítulos auto-traducibles al español.', audio: true },
  joshComeau: { nombre: 'Josh Comeau — Interactive Guide to Flexbox + blog', referente: 'Josh Comeau', credencial: 'La autoridad de CSS para devs', tipo: 'tutorial', url: 'https://www.joshwcomeau.com/', gratis: 'parcial', duracion: 'guías interactivas', nivel: 'intermedio', porQue: 'Las mejores explicaciones interactivas de CSS/React para programadores. Blog gratis; curso CSS-for-JS de pago opcional.' },
  mdnLearn: { nombre: 'MDN — Learn web development', referente: 'Mozilla', credencial: 'La referencia canónica de la plataforma web', tipo: 'docs', url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development', gratis: 'gratis', duracion: 'referencia', nivel: 'base', porQue: 'HTML/CSS/JS + React + accesibilidad + Git. Consulta rápida "qué hace esta propiedad", actualizada 2025.', audio: true },
  freecodecamp: { nombre: 'freeCodeCamp — Responsive Web Design / JS', referente: 'freeCodeCamp', credencial: '501(c)(3), 100% gratis', tipo: 'curso', url: 'https://www.freecodecamp.org/learn/', gratis: 'gratis', duracion: 'cursos + certificaciones', nivel: 'base', porQue: 'Ejercicios en navegador (Responsive Web Design, JS, front-end). Encaja en huecos de 15-20 min.' },
  fullStackOpen: { nombre: 'Full Stack Open (Universidad de Helsinki)', referente: 'U. Helsinki (Matti Luukkainen)', credencial: 'El curso full-stack JS universitario de referencia mundial', tipo: 'curso', url: 'https://fullstackopen.com/en/', gratis: 'gratis', duracion: '13 partes', nivel: 'intermedio', porQue: 'React→Redux→Node→GraphQL→TS→testing→CI/CD. De "sé React" a "construyo SPA+API de verdad". Bloque PC del sábado.' },
  nextjsLearn: { nombre: 'Next.js Learn (curso oficial de Vercel)', referente: 'Vercel', credencial: 'Los creadores de Next.js', tipo: 'curso', url: 'https://nextjs.org/learn', gratis: 'gratis', duracion: '16 capítulos', nivel: 'intermedio', porQue: 'Construir un dashboard full-stack real (App Router, data fetching, auth, deploy). Next.js es el React de referencia 2026 y el camino a desplegar en Vercel.' },
  refactoringUi: { nombre: 'Refactoring UI (Wathan & Schoger)', referente: 'Adam Wathan & Steve Schoger', credencial: 'Creadores de Tailwind; el estándar de diseño para devs', tipo: 'libro', url: 'https://www.refactoringui.com/', gratis: '$99-149', duracion: 'libro + vídeos', nivel: 'intermedio', porQue: 'Diseñar UI "con tácticas, no talento". Para que tu UI no parezca de programador; sirve también a las landings de AURUM.' },
  lawsOfUx: { nombre: 'Laws of UX (Jon Yablonski)', referente: 'Jon Yablonski', credencial: '30+ principios de UX', tipo: 'docs', url: 'https://lawsofux.com/', gratis: 'gratis', duracion: 'lectura corta', nivel: 'intermedio', porQue: 'Hick, Fitts, Doherty, Miller… el "por qué" detrás de buenas interfaces (y de conversión, útil en AURUM). Lectura de huecos.', audio: true },
  learnA11y: { nombre: 'Google — Learn Accessibility (web.dev)', referente: 'Equipo de Chrome', credencial: '20 módulos oficiales de accesibilidad', tipo: 'curso', url: 'https://web.dev/learn/accessibility', gratis: 'gratis', duracion: '20 módulos', nivel: 'intermedio', porQue: 'ARIA, foco de teclado, contraste, formularios, lectores de pantalla. La accesibilidad que distingue a un frontend pro.' },
  googleUx: { nombre: 'Google UX Design — Professional Certificate', referente: 'Google (Coursera)', credencial: 'Certificado profesional de Google', tipo: 'curso', url: 'https://www.coursera.org/professional-certificates/google-ux-design', gratis: 'parcial', duracion: 'trial 7d + $49/mes', nivel: 'base', porQue: 'Proceso UX completo con Figma (empatía→wireframe→prototipo→test). Tómalo concentrado o con ayuda financiera de Coursera.' },
  vercelDeploy: { nombre: 'Vercel — Getting started / Deploy', referente: 'Vercel', credencial: 'La plataforma de deploy que ya usas (VITALS)', tipo: 'docs', url: 'https://vercel.com/docs/getting-started-with-vercel', gratis: 'gratis', duracion: 'guía', nivel: 'base', porQue: 'De cero a producción: CLI, conectar GitHub, deploy y dominio. Formaliza el cómo-se-publica-una-web.' },
  // ── Construir CON IA — AI-first 2026 (dirigir y verificar, no teclear de memoria) ──
  claudeCodeDocs: { nombre: 'Claude Code — Documentación oficial (Overview)', referente: 'Anthropic', credencial: 'El agente de código que YA usas', tipo: 'docs', url: 'https://code.claude.com/docs/en/overview', gratis: 'gratis', duracion: 'referencia', nivel: 'intermedio', porQue: 'AI-first puro: CLI/IDE/web, MCP, skills, hooks, subagentes. El "cómo se ejecuta CON IA". Referencia canónica del flujo de construcción.', audio: true },
  claudeCodeBest: { nombre: 'Claude Code — Best practices (explore→plan→code→commit)', referente: 'Anthropic', credencial: 'El criterio humano que dirige a la IA', tipo: 'docs', url: 'https://code.claude.com/docs/en/best-practices', gratis: 'gratis', duracion: 'guía', nivel: 'intermedio', porQue: 'Gestión de contexto, CLAUDE.md, plan mode, dar a la IA forma de VERIFICAR (tests/screenshots), revisión adversarial, los 5 patrones de fallo. Aplica 1 patrón/día.', audio: true },
  claudeCodeWorkflows: { nombre: 'Claude Code — Common workflows', referente: 'Anthropic', credencial: 'Recetas oficiales de uso real', tipo: 'docs', url: 'https://code.claude.com/docs/en/common-workflows', gratis: 'gratis', duracion: 'recetas', nivel: 'base', porQue: 'Entender un codebase, arreglar bugs, mockup→CSS, trazar del front-end a la DB. Prompts concretos para ALLPA/Qori.' },
  claudeCodeChrome: { nombre: 'Claude Code with Chrome (verificar en el navegador)', referente: 'Anthropic', credencial: 'Pedido por ti, ya lo tienes instalado', tipo: 'docs', url: 'https://code.claude.com/docs/en/chrome', gratis: 'gratis', duracion: 'guía', nivel: 'intermedio', porQue: 'Verificar en vivo (consola, formularios, comparar UI con el diseño y arreglar). El puente de agentes a seguridad del navegador.' },
  promptOverview: { nombre: 'Anthropic — Prompt Engineering Overview', referente: 'Anthropic', credencial: 'Entrada oficial al prompting', tipo: 'docs', url: 'https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/overview', gratis: 'gratis', duracion: 'lectura', nivel: 'base', porQue: 'Define criterios de éxito y cómo verificar ANTES de promptear. El skill núcleo de la era IA: tu output vale lo que vale tu prompt.', audio: true },
  claudePromptBest: { nombre: 'Anthropic — Claude prompting best practices', referente: 'Anthropic', credencial: 'Referencia maestra de prompting', tipo: 'docs', url: 'https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices', gratis: 'gratis', duracion: 'referencia', nivel: 'intermedio', porQue: 'Claro y directo, contexto, ejemplos, XML, decir qué hacer + snippet anti-AI-slop. La técnica que separa un prompt de 1 que el de 5.', audio: true },
  v0: { nombre: 'v0 by Vercel — generar y publicar apps/landings con IA', referente: 'Vercel', credencial: 'El generador AI de UI de referencia', tipo: 'tutorial', url: 'https://v0.app/', gratis: 'parcial', duracion: 'genera en segundos', nivel: 'base', porQue: 'Describes una landing/app y la IA la genera funcional, editable y publicable, conectable a GitHub+Vercel. Construir-con-IA real para ALLPA/Qori.' },
  cursor: { nombre: 'Cursor — Documentación oficial (el IDE con IA)', referente: 'Anysphere', credencial: 'El editor AI-first más usado', tipo: 'docs', url: 'https://docs.cursor.com/', gratis: 'parcial', duracion: 'referencia', nivel: 'intermedio', porQue: 'Editor donde la IA escribe/edita con contexto del repo. Alternativa/compañero de Claude Code para construir dirigiendo a la IA.' },
  anthropicQuickstarts: { nombre: 'anthropic-quickstarts (Computer/Browser Use, Agent SDK)', referente: 'Anthropic', credencial: 'Apps oficiales arrancables', tipo: 'tutorial', url: 'https://github.com/anthropics/anthropic-quickstarts', gratis: 'gratis', duracion: 'repos clonables', nivel: 'avanzado', porQue: 'customer-support, computer-use, browser-use (Playwright), autonomous-coding-agent. Clonas, corres, modificas: construir CON IA desde el día 1.' },
  writingToolsAgents: { nombre: 'Writing effective tools for AI agents (Anthropic)', referente: 'Anthropic', credencial: 'Ensayo fundacional 2025', tipo: 'docs', url: 'https://www.anthropic.com/engineering/writing-tools-for-agents', gratis: 'gratis', duracion: 'ensayo', nivel: 'avanzado', porQue: 'Diseñar tools/MCP que el agente usa bien (namespacing, tokens, evals de tools). Núcleo del dominio Tool/MCP — junto a Building Effective Agents + Context Engineering.', audio: true },
  githubHello: { nombre: 'GitHub — Hello World', referente: 'GitHub', credencial: 'El onboarding oficial de Git/GitHub', tipo: 'tutorial', url: 'https://docs.github.com/en/get-started/start-your-journey/hello-world', gratis: 'gratis', duracion: '~15 min', nivel: 'base', porQue: 'Vocabulario sin escribir código: repo, branch, commit, PR, merge. Semana 1 de la mini-fase agosto.' },
  mdnInternet: { nombre: 'MDN — How does the Internet work', referente: 'Mozilla', credencial: 'Referencia canónica de la web', tipo: 'docs', url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Howto/Web_mechanics/How_does_the_Internet_work', gratis: 'gratis', duracion: 'lectura corta', nivel: 'base', porQue: 'Vocabulario de infraestructura (cliente, servidor, IP, dominio, ISP) para entender deploy, frontend, backend. Semana 1.', audio: true },
  // ── Dirigir a la IA: vibe coding + sistemas de agentes (ser el DIRECTOR, no teclear) — verificado 19-jun ──
  karpathySoftware3: { nombre: 'Software Is Changing (Again) — Software 3.0 (Karpathy)', referente: 'Andrej Karpathy', credencial: 'Acuñó "vibe coding" + el marco Software 1.0/2.0/3.0', tipo: 'video', url: 'https://www.youtube.com/watch?v=LCEmiRjPEtQ', gratis: 'gratis', duracion: '~40 min', nivel: 'intermedio', porQue: 'LA charla-ancla del director de la IA: los LLM como computadora que "programas en inglés". El marco mental del vibe coding serio.', audio: true },
  latentS3: { nombre: "Latent Space — Karpathy 'Software 3.0' (transcript + slides)", referente: 'Latent Space (swyx)', credencial: 'Companion en texto de la charla', tipo: 'docs', url: 'https://www.latent.space/p/s3', gratis: 'gratis', duracion: 'lectura', nivel: 'intermedio', porQue: 'Secciones anotadas + transcript + slides para citar los conceptos exactos sin re-ver el vídeo. Bloque C lectura.', audio: true },
  willisonVibe: { nombre: 'Not all AI-assisted programming is vibe coding', referente: 'Simon Willison', credencial: 'Co-creador de Django; voz equilibrada sobre LLMs', tipo: 'docs', url: 'https://simonwillison.net/2025/Mar/19/vibe-coding/', gratis: 'gratis', duracion: '10 min', nivel: 'intermedio', porQue: 'La frontera señal/hype: "no comiteo nada que no pueda explicar". Es tu KPI %-de-código-que-entiendo, fundamentado por la fuente.', audio: true },
  pragmaticHardTruths: { nombre: 'How AI-assisted coding will change SWE: hard truths', referente: 'Gergely Orosz (Pragmatic Engineer)', credencial: 'El newsletter técnico #1 (1M+ lectores)', tipo: 'docs', url: 'https://newsletter.pragmaticengineer.com/p/how-ai-will-change-software-engineering', gratis: 'parcial', duracion: 'lectura', nivel: 'intermedio', porQue: 'El "problema del 70%": la IA acelera pero el 30% production-ready sigue siendo ingeniería real — y los expertos sacan más ventaja. Por qué entender arquitectura para dirigir.', audio: true },
  specKit: { nombre: 'GitHub Spec Kit — Spec-Driven Development', referente: 'GitHub (Den Delimarsky)', credencial: 'Toolkit oficial de GitHub para SDD (30+ agentes)', tipo: 'tutorial', url: 'https://github.com/github/spec-kit', gratis: 'gratis', duracion: 'toolkit', nivel: 'avanzado', porQue: 'La disciplina madura del director: spec→plan→tasks→implement (cada fase un artefacto que da contexto al agente). Convierte tu SPEC.md en proceso repetible; integra con Claude Code.' },
  specKitBlog: { nombre: 'Spec-driven development with AI (GitHub Blog)', referente: 'GitHub', credencial: 'Anuncio oficial de Spec Kit', tipo: 'docs', url: 'https://github.blog/ai-and-ml/generative-ai/spec-driven-development-with-ai-get-started-with-a-new-open-source-toolkit/', gratis: 'gratis', duracion: '15 min', nivel: 'intermedio', porQue: 'El "por qué" de la spec: el LLM no lee mentes; especificar primero elimina la ambigüedad. El skill núcleo del director. Bloque C.', audio: true },
  claudeCodeExpertise: { nombre: 'Agentic coding and persistent returns to expertise', referente: 'Anthropic Research', credencial: 'Estudio sobre ~400k sesiones de Claude Code', tipo: 'docs', url: 'https://www.anthropic.com/research/claude-code-expertise', gratis: 'gratis', duracion: 'paper', nivel: 'avanzado', porQue: 'LA prueba de "sé director, no tecleo": el humano toma ~70% de las decisiones de planificación y ~20% de ejecución; los expertos logran ~2× éxito. Tu filosofía, medida.', audio: true },
  swyxAiEngineer: { nombre: 'The Rise of the AI Engineer (ensayo de swyx)', referente: 'swyx (Shawn Wang)', credencial: 'Acuñó el rol "AI Engineer" (aprobado por Karpathy)', tipo: 'docs', url: 'https://www.latent.space/p/ai-engineer', gratis: 'gratis', duracion: 'ensayo', nivel: 'intermedio', porQue: 'Define el perfil exacto al que Synapse apunta: dirigir la IA con software, no solo promptear. El ensayo fundacional del rol.', audio: true },
  aiEngineerYt: { nombre: "AI Engineer — canal de charlas (Summit/World's Fair)", referente: 'AI Engineer', credencial: 'La conferencia técnica de IA más grande', tipo: 'video', url: 'https://www.youtube.com/@aiDotEngineer', gratis: 'gratis', duracion: 'charlas', nivel: 'avanzado', porQue: 'Charlas de los que construyen productos de IA en producción. El estado del arte del rol, en vídeo para huecos.', audio: true },
  anthropicMultiAgent: { nombre: 'How we built our multi-agent research system', referente: 'Anthropic Engineering', credencial: 'Sistema multi-agente en producción (Claude Research)', tipo: 'docs', url: 'https://www.anthropic.com/engineering/multi-agent-research-system', gratis: 'gratis', duracion: 'lectura', nivel: 'avanzado', porQue: 'Orquestación multi-agente REAL (+90% vs single-agent en su eval): orchestrator-workers, cómo dividir el trabajo. Dirigir sistemas de agentes.', audio: true },
  chipAgents: { nombre: 'Agents (tools, planning & failure modes) — Chip Huyen', referente: 'Chip Huyen', credencial: "Autora de 'AI Engineering' (O'Reilly)", tipo: 'docs', url: 'https://huyenchip.com/2025/01/07/agents.html', gratis: 'gratis', duracion: 'lectura larga', nivel: 'avanzado', porQue: 'El mapa completo de agentes: herramientas, planificación y los modos de fallo (saber cuándo la IA se equivoca). Criterio de director.', audio: true },
  hamelFieldGuide: { nombre: 'A Field Guide to Rapidly Improving AI Products', referente: 'Hamel Husain', credencial: 'Su curso de evals es el #1 de Maven', tipo: 'docs', url: 'https://hamel.dev/blog/posts/field-guide/', gratis: 'gratis', duracion: 'lectura', nivel: 'avanzado', porQue: 'Evals como disciplina de DATOS (no dashboards): cómo mejorar un producto de IA con criterio medible. El "verificar" del director.', audio: true },
  hamelLlmJudge: { nombre: 'Creating a LLM-as-a-Judge that aligns with humans', referente: 'Hamel Husain & Shreya Shankar', credencial: 'Practitioners de evals reales', tipo: 'docs', url: 'https://hamel.dev/blog/posts/llm-judge/', gratis: 'gratis', duracion: 'lectura', nivel: 'avanzado', porQue: 'Cómo construir un juez-IA que coincide con tu criterio: el corazón de evaluar lo que la IA produce.' },
  appliedLlms: { nombre: "What We've Learned From A Year of Building with LLMs", referente: 'Yan/Bischof/Frye/Liu + Hamel/Shreya', credencial: 'Enviaron productos LLM reales (Amazon, Hex, Modal…)', tipo: 'docs', url: 'https://applied-llms.org/', gratis: 'gratis', duracion: 'guía larga', nivel: 'avanzado', porQue: 'La guía práctica de quienes ya lo hicieron: prompting, evals, ops, organización. Lo que funciona de verdad.', audio: true },
  openaiOrchestrating: { nombre: 'Orchestrating Agents: Routines and Handoffs (OpenAI)', referente: 'OpenAI Cookbook', credencial: 'Recetas oficiales de OpenAI', tipo: 'docs', url: 'https://developers.openai.com/cookbook/examples/orchestrating_agents', gratis: 'gratis', duracion: 'tutorial', nivel: 'avanzado', porQue: 'Patrones de routines + handoffs entre agentes con código. Complemento práctico a la teoría de orquestación.' },
  twelveFactorAgents: { nombre: '12-Factor Agents (Dex / HumanLayer)', referente: 'HumanLayer', credencial: 'El "12-factor" para agentes confiables', tipo: 'docs', url: 'https://github.com/humanlayer/12-factor-agents', gratis: 'gratis', duracion: 'principios', nivel: 'avanzado', porQue: 'Los principios para construir agentes LLM confiables y de producción (no demos). El checklist del director de agentes.', audio: true },
  whyHallucinate: { nombre: 'Why Language Models Hallucinate (Kalai et al., OpenAI)', referente: 'OpenAI', credencial: 'Paper 2025', tipo: 'docs', url: 'https://arxiv.org/abs/2509.04664', gratis: 'gratis', duracion: 'paper', nivel: 'avanzado', porQue: 'Por qué los modelos alucinan (incentivos de entrenamiento) — para saber cuándo desconfiar y verificar. Criterio anti-error.' },
} satisfies Record<string, SynapseMaterial>;

export const SYNAPSE_MATERIALES = M;

// ─── Meta ───
export const SYNAPSE_META = {
  titulo: 'SYNAPSE',
  subtitulo: 'MIND · AI-ENGINEERED — médico → especialista en IA nivel Anthropic',
  tesis: 'La sinapsis entre tu cerebro médico y las máquinas. Python, datos, deep learning, agentes, ciberseguridad y post-training — SOLO con los referentes (Anthropic, Stanford, MIT, Harvard, creadores de las herramientas), cero youtubers del momento. 30 min/día en espacios muertos, proyecto público por fase.',
  accent: '#7C83D6', // periwinkle — color canónico de la consola (alineado con SidebarAccents.Synapse)
  nota: 'Motor ACTIVO (pestaña ⚡ Hoy): 12 semanas día a día — F0 completa (sem 1-8) + arranque F1/CS50P (sem 9-12) — con lecciones EXACTAS de los temarios reales extraídos el 10-jun-2026 (DATA/SYNAPSE/curricula/). Bloques A 15\' pantalla · B 10\' audio · C 5\' lectura + sábado PC opcional. Progreso manual real (empieza 0%). Las semanas 13+ se regeneran con DATA/_scripts/gen_synapse_plan.js al avanzar de fase.',
} as const;

// ─── Fases ───
export const SYNAPSE_FASES: SynapseFase[] = [
  {
    id: 'f0', fase: 'F0', titulo: 'La Escuela de Anthropic', duracion: 'sem 1–4', estado: 'activa',
    desc: 'La "licenciatura básica" de Anthropic con la que pediste empezar: Academy completa de nivel base + la visión panorámica de Karpathy. Todo apto para huecos móviles.',
    entregable: 'Certificados Claude 101 + AI Fluency · dominar los 5 patrones de agentes',
    materiales: [M.academy, M.claude101, M.aiFluency, M.effectiveAgents, M.karpathyIntro, M.karpathyDeep, M.nn3b1b],
  },
  {
    id: 'f1', fase: 'F1', titulo: 'Código: Python + terminal + Git', duracion: 'sem 5–12', estado: 'pendiente',
    desc: 'La base que un médico no tiene y Anthropic da por sentada. Python es el ÚNICO requisito universal en todos sus puestos (verificado en sus vacantes reales).',
    entregable: 'Primer repo público en GitHub con scripts Python propios para Pulso',
    materiales: [M.cs50p, M.automate, M.pyTutorial, M.proGit, M.missingSemester, M.cs50x],
  },
  {
    id: 'f2', fase: 'F2', titulo: 'Datos: pandas + SQL + probabilidad', duracion: 'sem 13–20', estado: 'pendiente',
    desc: 'Data science por los CREADORES de las herramientas (McKinney = pandas) + la probabilidad de Harvard que todo el ML asume.',
    entregable: 'Análisis pandas de un dataset real (Pulso/LIVIANO) publicado en GitHub',
    materiales: [M.kaggle, M.mckinney, M.vanderplas, M.sqlbolt, M.widom, M.stat110],
  },
  {
    id: 'f3', fase: 'F3', titulo: 'Deep learning: cómo piensa la máquina', duracion: 'sem 21–32', estado: 'pendiente',
    desc: 'De la intuición visual (3Blue1Brown) a construir un GPT desde cero con Karpathy. MIT + Harvard + fast.ai como columna.',
    entregable: 'Tu primer GPT entrenado desde cero (Zero to Hero) + certificado CS50 AI',
    materiales: [M.algebra3b1b, M.calculo3b1b, M.mit6s191, M.fastai, M.zeroToHero, M.cs50ai, M.nanochat, M.cs336, M.raschkaScratch],
  },
  {
    id: 'f4', fase: 'F4', titulo: 'Ingeniería de agentes y workflows (EL CORAZÓN)', duracion: 'sem 33–48', estado: 'pendiente',
    desc: 'API de Claude, MCP, Agent SDK, evals, LangGraph y n8n (tu motor APEX). "Experiencia LLM en producción pesa más que credenciales académicas" — patrón verificado en los puestos de Anthropic.',
    entregable: '1–2 agentes REALES en producción con evals (motor APEX v2 con Agent SDK + MCP propio)',
    materiales: [M.claudeApi, M.promptTutorial, M.anthropicCourses, M.claudeCookbooks, M.mcpIntro, M.mcpAdvanced, M.claudeCodeAction, M.agentSkills, M.agentSdk, M.evalsDocs, M.contextEng, M.harnesses, M.agentSkillsEssay, M.ccaF, M.hamelEvals, M.aieBook, M.llmZoomcamp, M.hfAgents, M.dlaiMcp, M.dlaiComputerUse, M.dlaiClaudeCode, M.dlaiLanggraph, M.langchainAcademy, M.n8nLevelOne, M.n8nAdvancedAi, M.openaiAgentsGuide, M.aiEngineering, M.raschkaLlm],
  },
  {
    id: 'f5', fase: 'F5', titulo: 'Ciberseguridad (web clásica → seguridad de IA)', duracion: 'sem 49–60', estado: 'pendiente',
    desc: 'OWASP + PortSwigger (creadores de Burp) + Simon Willison + la investigación de seguridad de la propia Anthropic. Cierra con red teaming de IA (HTB × Google).',
    entregable: 'Auditoría de seguridad documentada de tus propios agentes (OWASP LLM Top 10)',
    materiales: [M.owaspTop10, M.owaspLlm, M.portswigger, M.webLlmAttacks, M.willisonPi, M.lethalTrifecta, M.cs253, M.tryhackme, M.htbAiRedTeam, M.manyShotJb, M.constClassifiers, M.rsp],
  },
  {
    id: 'f6', fase: 'F6', titulo: 'Nivel Anthropic: post-training + alignment', duracion: 'sem 61+', estado: 'meta',
    desc: 'RLHF, ARENA (la prep real del Fellows), MLOps de Berkeley, DSA del MIT y la teoría élite de Stanford. La meta: aplicar al Anthropic Fellows Program.',
    entregable: 'Aplicación al Anthropic Fellows Program + portfolio público completo',
    materiales: [M.rlhfBook, M.dpoPaper, M.arena, M.transformerCircuits, M.jaxQuickstart, M.fsdl, M.mit6006, M.cs50w, M.cs229, M.cs224n, M.cs25, M.fellows],
  },
];

// ─── Biblioteca por categoría ───
export const SYNAPSE_BIBLIOTECA: { categoria: string; icon: string; items: SynapseMaterial[] }[] = [
  { categoria: 'La Escuela de Anthropic', icon: '🏛', items: [M.academy, M.ccaF, M.claude101, M.aiFluency, M.claudeApi, M.mcpIntro, M.mcpAdvanced, M.claudeCodeAction, M.agentSkills, M.promptTutorial, M.anthropicCourses, M.claudeCookbooks, M.agentSdk, M.evalsDocs, M.effectiveAgents, M.contextEng, M.harnesses, M.agentSkillsEssay, M.fellows] },
  { categoria: 'Python & código', icon: '🐍', items: [M.cs50p, M.cs50x, M.automate, M.pyTutorial, M.proGit, M.missingSemester, M.realPython] },
  { categoria: 'Datos & estadística', icon: '📊', items: [M.kaggle, M.mckinney, M.vanderplas, M.sqlbolt, M.widom, M.stat110] },
  { categoria: 'Matemática visual', icon: '🧮', items: [M.nn3b1b, M.algebra3b1b, M.calculo3b1b] },
  { categoria: 'Deep learning', icon: '🧠', items: [M.karpathyIntro, M.karpathyDeep, M.zeroToHero, M.nanochat, M.cs336, M.raschkaScratch, M.mit6s191, M.fastai, M.cs50ai] },
  { categoria: 'Agentes & LLM engineering', icon: '🤖', items: [M.hfAgents, M.hfLlm, M.dlaiMcp, M.dlaiComputerUse, M.dlaiClaudeCode, M.dlaiLanggraph, M.langchainAcademy, M.n8nLevelOne, M.n8nAdvancedAi, M.openaiCookbook, M.openaiAgentsGuide, M.aiEngineering, M.raschkaLlm, M.aheadOfAi] },
  { categoria: 'EVALS · pilar transversal (★ el skill #1 2026)', icon: '📈', items: [M.hamelEvals, M.evalsDocs, M.anthropicCourses, M.aieBook, M.hamelLlmJudge, M.hamelFieldGuide, M.llmZoomcamp] },
  { categoria: 'RAG · embeddings · vector search (core AI-engineer aplicado)', icon: '🔎', items: [M.llmZoomcamp, M.aiEngineering, M.aieBook, M.claudeApi, M.n8nAdvancedAi] },
  { categoria: 'Ciberseguridad', icon: '🛡', items: [M.owaspTop10, M.owaspLlm, M.portswigger, M.webLlmAttacks, M.willisonPi, M.lethalTrifecta, M.cs253, M.tryhackme, M.htbAiRedTeam, M.manyShotJb, M.constClassifiers, M.rsp] },
  { categoria: 'Teoría élite Stanford/MIT/Berkeley (CS336 = eje F3→F6)', icon: '🎓', items: [M.cs336, M.cs229, M.cs224n, M.cs25, M.mit6006, M.fsdl, M.cs50w, M.mlSpec, M.rlhfBook, M.dpoPaper, M.arena, M.transformerCircuits] },
  { categoria: 'CS-core: la base sólida (teachyourselfcs · 9 pilares)', icon: '🏗', items: [M.teachYourselfCs, M.composingPrograms, M.ostep, M.nand2tetris, M.csapp, M.kuroseRoss, M.cs144, M.mit6042, M.mit6006, M.skiena] },
  { categoria: 'Frontier-lab avanzado (RL · DPO · JAX · papers · interpretabilidad)', icon: '🔬', items: [M.attentionPaper, M.annotatedTransformer, M.spinningUp, M.dpoPaper, M.jaxQuickstart, M.hfDeepRl, M.lilLog, M.mlEngineering, M.neelNanda, M.biologyLlm, M.bluedotAlignment] },
  { categoria: 'Backend de producción (Python · APIs · datos · system design)', icon: '⚙️', items: [M.roadmapBackend, M.fastapiTut, M.djangoRest, M.postgresqlTut, M.cs50sql, M.pytest, M.testdriven, M.arjancodes, M.mit6031, M.dockerGetStarted, M.twelveFactor, M.sysDesignPrimer, M.bytebytego, M.ddia, M.grokkingSD] },
  { categoria: 'Frontend & diseño web (HTML/CSS/JS · React · UI/UX)', icon: '🎨', items: [M.roadmapFrontend, M.odinProject, M.learnCssWebdev, M.kevinPowell, M.joshComeau, M.mdnLearn, M.freecodecamp, M.fullStackOpen, M.nextjsLearn, M.cs50w, M.refactoringUi, M.lawsOfUx, M.learnA11y, M.googleUx, M.vercelDeploy] },
  { categoria: '🤖 Construir CON IA — AI-first 2026 (dirigir, no teclear de memoria)', icon: '🤖', items: [M.claudeCodeDocs, M.claudeCodeBest, M.claudeCodeWorkflows, M.claudeCodeChrome, M.dlaiClaudeCode, M.promptOverview, M.claudePromptBest, M.promptTutorial, M.v0, M.cursor, M.anthropicQuickstarts, M.effectiveAgents, M.contextEng, M.writingToolsAgents, M.githubHello, M.mdnInternet, M.vercelDeploy] },
  { categoria: 'Dirigir a la IA — vibe coding + sistemas de agentes (ser el DIRECTOR)', icon: '🎬', items: [M.karpathySoftware3, M.latentS3, M.willisonVibe, M.pragmaticHardTruths, M.specKit, M.specKitBlog, M.claudeCodeExpertise, M.swyxAiEngineer, M.aiEngineerYt, M.anthropicMultiAgent, M.chipAgents, M.hamelFieldGuide, M.hamelLlmJudge, M.appliedLlms, M.openaiOrchestrating, M.twelveFactorAgents, M.whyHallucinate] },
  { categoria: 'Audio para espacios muertos', icon: '🎧', items: [M.lexDario, M.dwarkeshDario, M.lexKarpathy, M.dwarkeshInterp, M.dwarkeshDemis, M.latentSpace, M.noPriors, M.anthropicYt, M.dlaiYt, M.theBatch] },
];

// ─── KPIs ───
const ALL = Object.values(M) as SynapseMaterial[];
export const SYNAPSE_KPIS = {
  fases: SYNAPSE_FASES.length,
  materialesVerificados: ALL.length,
  fasesCompletadas: 0, // progreso REAL — empieza en 0
  metaFinal: 'Anthropic Fellows Program',
} as const;

// ─── Protocolo (horario REAL en Google Calendar — confirmado por Joseph el 10-jun-2026) ───
export const SYNAPSE_HORARIO: { min: string; bloque: string; que: string; formato: string }[] = [
  { min: "30'", bloque: 'L–V 12:30–13:00 · evento "🧠 SYNAPSE — misión del día"', que: "La misión completa de la pestaña ⚡ Hoy: A lección 15' + B audio 10' + C lectura 5'", formato: 'pantalla' },
  { min: '2 h', bloque: 'Sábado 15:00–17:00 · "🧠 SYNAPSE — PC sábado"', que: 'Bloque de teclado: notebooks, repo público synapse-journal, Problem Sets de CS50P + ponerse al día', formato: 'requiere PC' },
  { min: '2 h', bloque: 'Domingo 15:00–17:00 · "🧠 SYNAPSE — repaso + PC" (14 y 21-jun libres)', que: 'Repaso semanal (Feynman en voz alta) + terminar lo que quedó del bloque PC', formato: 'repaso' },
  { min: 'extra', bloque: 'Viajes · colas · gaps sueltos (opcional)', que: 'Adelantar audio (B) o lectura móvil (C) en cualquier hueco muerto del día', formato: 'sí-audio' },
];

// ─── Quick links (right panel) ───
export const SYNAPSE_QUICKLINKS: { label: string; url: string; nota: string }[] = [
  { label: '◆ Obsidian — Mapa SYNAPSE', url: 'obsidian://open?vault=Vault_Medicina%20MIR_Joseph&file=05_SYNAPSE_IA%2F00_Mapa_SYNAPSE', nota: 'tu segundo cerebro: 7 fases · 82 subtemas con temario real' },
  { label: '🏛 Anthropic Academy', url: 'https://www.anthropic.com/learn', nota: 'La escuela oficial — F0 empieza aquí' },
  { label: '🎓 Claude 101', url: 'https://anthropic.skilljar.com/claude-101', nota: 'Primer curso con certificado' },
  { label: '📜 Building Effective Agents', url: 'https://www.anthropic.com/engineering/building-effective-agents', nota: 'El ensayo fundacional (25 min)' },
  { label: '🎙 Karpathy: Intro to LLMs', url: 'https://www.youtube.com/watch?v=zjkBMFhNj_g', nota: '1 h en audio — hoy mismo' },
  { label: '🌐 Traductor EN→ES (páginas)', url: 'https://translate.google.com/?op=websites', nota: 'Pega cualquier URL en inglés y léela en español; o en Chrome clic derecho → Traducir. YouTube: subtítulos → traducir automáticamente.' },
];

// ─── El nivel meta (verificado en vacantes reales de Anthropic, jun-2026) ───
export const SYNAPSE_NIVEL_META: { skill: string; fuente: string }[] = [
  { skill: 'Python sólido a nivel producción', fuente: 'el ÚNICO requisito universal en todos los puestos (Research Engineer Evals $320-485k, Interpretability $315-560k)' },
  { skill: 'Evals / evaluation frameworks', fuente: 'aparece en casi todos los puestos Y en el Fellows — por eso F4 los trabaja con el material oficial de Anthropic' },
  { skill: 'Experiencia LLM en producción > títulos', fuente: 'Applied AI Architect ($240-315k) pide "builder credibility como ingeniero o fundador técnico" — tu perfil Pulso ya suma' },
  { skill: 'MCP + context engineering', fuente: 'textual en los requisitos de los puestos Applied AI' },
  { skill: 'Distributed systems / data pipelines', fuente: 'mínimos del Research Engineer (se cubren en F6 con FSDL + MIT 6.006)' },
  { skill: 'Fellows Program: ejecución, no credenciales', fuente: '"You don’t need a PhD, prior ML experience, or published papers" (textual) — piden Python fluido + convertir problemas ambiguos en progreso + motivación AI safety. Stipend $3,850/semana + ~$15k/mes de cómputo' },
];

// ─── Honestidad (no inventado) ───
export const SYNAPSE_ADVERTENCIAS: string[] = [
  'Fellows Program: requiere autorización de trabajo en US/UK/Canadá (sin sponsorship de visa) — verificar tu situación antes de apuntar a la beca; los skills sirven igual para Applied AI y para Pulso.',
  'A 30 min/día la ruta completa es 12–18 meses realistas. F0 y F4 son las de mayor ROI inmediato (la F4 mejora directamente el motor APEX y Pulso).',
  'Zero to Hero, ARENA, MIT 6.006 y CS50W exigen bloques largos de TECLADO — no caben en huecos de 10-15 min; van al bloque opcional de fin de semana.',
  'ACTUALIZACIÓN 2026: Andrej Karpathy se unió a ANTHROPIC (may-2026) a liderar research de pre-training de Claude — refuerza la tesis del segmento ("aprende de quienes construyen Claude"). Su LLM101n/Eureka Labs quedó APLAZADO (no cerrado); su obra publicada y vigente es Zero to Hero + nanochat (usa nanochat, no el deprecado nanoGPT).',
  'ML Specialization de Ng ya no tiene audit gratis a nivel especialización ($49/mes); intentar audit por curso individual o ayuda financiera antes de pagar.',
  'Veredicto del auditor de completitud: lo que consigue la entrevista no es el temario sino PROYECTOS PÚBLICOS demostrables en GitHub — por eso cada fase exige un entregable público.',
  'Las 85 URLs fueron verificadas en vivo el 10-jun-2026 (WebFetch/oEmbed). Si alguna cambia, la fuente canónica es DATA/SYNAPSE/materiales-verificados.md.',
  'Ruta FULL-STACK senior añadida 18-jun (categorías "Backend de producción" y "Frontend & diseño web", +29 recursos verificados): FastAPI/Postgres/pytest/system design + HTML-CSS-JS/React-Next/UI-UX. A 30-60 min/día, senior full-stack es horizonte de 3 años — roadmap Año 1/2/3 en DATA/SYNAPSE/ROADMAP_SENIOR_MULTIANIO.md. El material en inglés se traduce (ver quicklink 🌐 Traductor).',
  'FILOSOFÍA AI-FIRST (18-jun): no memorizar sintaxis ni teclear código que la IA ya escribe — el skill humano es DIRIGIR y VERIFICAR (vocabulario, prompting, criterio, arquitectura, gusto). Ver pestaña 🚀 Agosto: mini-fase de 10 semanas para ya poder pedirle a la IA "construye tal sistema" CON CRITERIO. CS50P/Automate/MIT 6.006/nand2tetris se degradan para esta mini-fase (vuelven en las fases profundas de sept+).',
  'ÉNFASIS 2026 (re-jerarquización, sin cambiar fechas): (1) EVALS es pilar transversal medible, no un tema de F4 — es "el skill más subestimado" y aparece en casi todo puesto; se trabaja con Hamel + Chip Huyen + evals docs. (2) DPO ya es el estándar de alineación en producción (desplazó a RLHF/PPO): ancla DPO añadida en F6 (paper Rafailov + cap. DPO del RLHF Book). (3) Ruta JAX mínima añadida en F6 porque Anthropic entrena en JAX. (4) RAG/embeddings/vector-search es categoría propia de Biblioteca. (5) CS336-2026 es el eje declarado de F3→F6 para "construir un LLM de verdad".',
];

// ─── Mini-Fase AGOSTO (AI-first) + Práctica deliberada (Peak/Ericsson) ───
// Bases ejecutables/medibles para CONSTRUIR con IA. Doc: DATA/SYNAPSE/MINIFASE_AGOSTO_AIFIRST.md
export type MiniFaseSemana = { rango: string; foco: string; entregable: string; recurso?: string };
export interface MiniFase {
  titulo: string; etiqueta: string; objetivo: string; entregableFinal: string;
  kpis: string[]; semanas: MiniFaseSemana[];
}
export const SYNAPSE_MINIFASE: MiniFase = {
  titulo: 'Bases AI-first · construir software DIRIGIENDO a la IA',
  etiqueta: '10 semanas · 19-jun → 31-ago',
  objetivo: 'Pasar de "sé que la IA programa" a "dirijo a la IA para construir y desplegar software real CON CRITERIO". Al cerrar agosto: especificas una landing/app para ALLPA o Qori, conduces explore→plan→code→commit, verificas con Claude in Chrome, despliegas en Vercel y EXPLICAS cada pieza. No memorizas sintaxis: la lees y la diriges.',
  entregableFinal: 'Una mini-app/landing REAL y pública en Vercel (URL viva) para ALLPA o Qori Golden, hecha dirigiendo a la IA: SPEC.md propio, generada con v0/Claude Code, verificada con Claude in Chrome, desplegada y documentada en README. La prueba: abrir el repo y EXPLICAR cada archivo + el journal (prompts.md, glosario.md).',
  kpis: [
    'Prompts efectivos/semana (resuelven al 1.º-2.º intento): de ~3 (S1) a ~12 (S10), nota 1-5 en prompts.md',
    'Features VIVAS en URL pública de Vercel: acumulado ≥ 8 (cada una con commit + link)',
    '%-de-código-que-entiendo (sobre nº de archivos): de ~30% (S2) a ≥ 80% (S10) — métrica estrella',
    'Vocabulario activo señalado en tu proyecto: 15/15 (API, DB, frontend, backend, deploy, auth, repo, commit, branch, PR, env var…)',
    'Ciclos explore→plan→code→commit con plan mode: ≥ 10',
    'Bugs detectados en el navegador y resueltos con Claude in Chrome: ≥ 5',
  ],
  semanas: [
    { rango: 'S1 · 19-28 jun', foco: 'Vocabulario (repo/commit/branch/PR; cliente-servidor) + instalar Claude Code y PREGUNTARLE (no codear)', entregable: 'glosario.md con 15 términos en tus palabras + captura de Claude Code respondiendo 3 preguntas (KPI 8/15)', recurso: 'GitHub Hello World · MDN Internet · Claude Code Quickstart' },
    { rango: 'S2 · 29 jun-5 jul', foco: 'El agentic loop + flujo explore→plan→code→commit; plan mode ANTES de codear', entregable: '1 ciclo completo documentado (plan → diff → commit). KPI 3 prompts efectivos', recurso: 'Claude Code: How it works + Best practices' },
    { rango: 'S3 · 6-12 jul', foco: 'Promptear para construir: claro y directo, contexto, ejemplos, referenciar archivos', entregable: 'prompts.md con 5 pares vago↔específico, nota 1-5 c/u. KPI 5 efectivos', recurso: 'Prompt Engineering Overview + Tutorial interactivo' },
    { rango: 'S4 · 13-19 jul', foco: 'CLAUDE.md + dar a la IA forma de VERIFICAR (trust-then-verify)', entregable: 'CLAUDE.md propio + 1 caso "corre-el-check-y-arregla". KPI 12/15 vocab', recurso: 'Claude Code Best practices' },
    { rango: 'S5 · 20-26 jul', foco: 'PROYECTO REAL: landing ALLPA/Qori con v0; LEER lo que generó', entregable: 'repo público "landing v1" + journal por archivo (qué hace cada uno). KPI %-entiendo 45%', recurso: 'v0 by Vercel + Common workflows' },
    { rango: 'S6 · 27 jul-2 ago', foco: 'DESPLEGAR en Vercel: build, producción vs preview, dominio, push→redeploy', entregable: 'URL pública viva + journal de términos. KPI 2 features, 15/15 vocab', recurso: 'Vercel — Getting started / Deploy' },
    { rango: 'S7 · 3-9 ago', foco: 'Iterar y VERIFICAR en el navegador con Claude in Chrome (consola, formulario, diseño)', entregable: '2 bugs detectados en el navegador y resueltos. KPI 3 bugs, 10 prompts efectivos', recurso: 'Claude Code with Chrome' },
    { rango: 'S8 · 10-16 ago', foco: 'Backend simple: formulario de lead que GUARDE datos (Supabase/Neon vía Vercel)', entregable: 'formulario VIVO que captura leads + journal de endpoint/env var. KPI %-entiendo 65%, 5 features', recurso: 'Vercel — Add a database' },
    { rango: 'S9 · 17-23 ago', foco: 'Leer el código como REVISOR; un agente fresco revisa tu diff (detectar AI slop / over-engineering)', entregable: '1 revisión + 3 mejoras aplicadas que ENTENDISTE y aprobaste. KPI %-entiendo 75%', recurso: 'Claude Code Best practices (revisión adversarial)' },
    { rango: 'S10 · 24-31 ago', foco: 'CAPSTONE: Claude te entrevista → SPEC.md, construyes, verificas y despliegas la app FINAL', entregable: 'app FINAL pública + SPEC.md + README propio + demo de 5 min. Cierre: %-entiendo 80%, 8 features, 15/15, 12 efectivos', recurso: 'Best practices (let Claude interview you)' },
  ],
};

export interface PracticaDeliberada { resumen: string; principios: string[]; sistemaMedible: string[]; compresion: string }
export const SYNAPSE_PRACTICA: PracticaDeliberada = {
  resumen: 'Práctica deliberada (Anders Ericsson, "Peak"): el coach de élite que necesitas es la IA, 24/7. Cada sesión PRODUCE un entregable y se CALIFICA — el % de avance mide DOMINIO, no minutos. Ver vídeos sin parir y medir es "naive practice" (el médico que repite años sin feedback y se estanca: ese riesgo es real).',
  principios: [
    'Objetivo específico y CALIFICABLE por sesión (no "estudiar X" sino "lograr Y medible en <T sin mirar docs"). Decláralo antes de empezar.',
    'Foco total, una sola cosa a la vez: 30 min de atención real > 2 h difusas. Sin notificaciones, un sub-skill por día.',
    'Feedback inmediato y específico: la IA evalúa el entregable al instante (corre el código, critica el PITCH, marca el error exacto). Es la pieza que hoy falta.',
    'Salir de la zona de confort: el sistema sube dificultad cuando aciertas y la baja cuando fallas — nunca repetir lo ya dominado.',
    'Construir representaciones mentales, no acumular datos: cada sesión cierra con auto-explicación (Feynman) que la IA puntúa.',
    'Corregir el error, no esconderlo: diagnosticar POR QUÉ falló (prompt vago, falta contexto) y reescribir.',
    'Maestría antes de avanzar (mastery learning): no se pasa de sub-skill sin superar el umbral (~85) dos veces.',
  ],
  sistemaMedible: [
    'Rúbrica por sesión 0-100, 4 ejes (25 c/u): Objetivo cumplido · Calidad · Independencia (¿con cuántas pistas?) · Reflexión (auto-explicación). La IA devuelve los 4 sub-scores + 1 acción de mejora.',
    'INPUT (ver/leer) NO mueve el % de maestría — solo PRÁCTICA (producir algo evaluable) lo mueve. Separarlos es el cambio clave.',
    'Pre-test / post-test rápido por sub-skill: el delta = aprendizaje real de la sesión.',
    'Mastery gate: sub-skill "dominado" sólo con 2 sesiones ≥ umbral; mientras no, reaparece. Reemplaza el "completé la fase" binario.',
    'Error-log: la IA lista 1-3 fallos; el sistema los re-inyecta como drill futuro (repetición espaciada del error).',
    'Borde de dificultad (niveles 1-5): si score ≥90 ×2 sube; si ≤60 baja. Mantenerse en zona 70-85 = sigues fuera de tu zona de confort.',
    'Journal en repo público (prompts.md · glosario.md · progreso.md) = tu "caja negra"; revisión semanal de 15 min (sábado) para calibrar.',
  ],
  compresion: 'Lo que comprime el camino NO son las horas, es la CALIDAD del bucle (objetivo→feedback→corrección) — Ericsson DESMONTA el mito de las 10.000 h ("hacer más de lo mismo no te hace mejor"). La palanca: Bloom (1984) mostró que tutoría 1-a-1 + mastery learning lleva al alumno medio sobre el 98% de la clase (+2σ); el problema era escalar un tutor humano — la IA lo resuelve a coste ~0 y 24/7. RCT de Harvard (Kestin 2025): con tutor-IA se aprendió >2× por hora que en clase activa. Traducción honesta de horizontes a 30-60 min/día: TOP-10% de un dominio acotado (construir/desplegar con IA; cierre 1-a-1) — manual ~1-2 años, con coach-IA ~6-10 meses. TOP-5% — manual ~3 años, con IA ~1.5-2 años. TOP-1% — la IA NO lo comprime: exige miles de horas en el borde y el salto del 10.º al 1.er puesto cuesta desproporcionadamente más que llegar al 10.º. La IA convierte "aprender a HACERLO" (años) en "aprender a DIRIGIRLO y MEDIRLO" (semanas para las bases); el techo lo pone el juicio humano entrenado con repeticiones reales, no la herramienta.',
};
