/**
 * synapseDailyPlan.ts — Motor día-a-día SYNAPSE (12 semanas · 82 días · 2026-07-09 → 2026-09-28).
 * v7 (23-jun): arranque mié 24-jun-2026 (20-23 no se estudió; todo el sistema corre a 24-jun) · sem 1 = mié→dom · TODOS los domingos LIBRES (sin misión).
 * GENERADO por DATA/_scripts/gen_synapse_plan.js desde DATA/SYNAPSE/curricula/_extracted.json
 * (temarios REALES extraídos con WebFetch/oEmbed + verificación adversarial, 10-jun-2026).
 * NO editar a mano — regenerar: node DATA/_scripts/gen_synapse_plan.js
 *
 * Estructura del día (30 min en espacios muertos, instrucción verbatim de Joseph):
 *  A (15', pantalla)  lección EXACTA de la fase actual con link directo
 *  B (10', audio)     rotación: No Priors → Dwarkesh → Lex #452 (outline real) → The Batch (jue) → canal Anthropic (vie)
 *  C (5', lectura)    píldora móvil: Pro Git / Willison / Python Tutorial / Automate / research de Anthropic
 *  PC (sáb, 60-90', OPCIONAL) teclado: setup, repo público, problem sets CS50P
 *  Dom = repaso (nada nuevo). Progreso REAL manual (PlanKey 'synapse', empieza 0%).
 * real:true = lección/temario verificado; real:false = "siguiente episodio/tramo" (honesto, sin inventar).
 * Cobertura: F0 completa (sem 1-8) + arranque F1 (sem 9-12, CS50P Weeks 0-3). Las semanas 13+
 * se generan al avanzar de fase añadiendo A-units en el script y re-ejecutándolo.
 */
export type SynFormato = 'pantalla' | 'audio' | 'lectura' | 'pc' | 'repaso';
export interface SynBloque {
  tag: 'A' | 'B' | 'C' | 'PC' | 'R';
  min: number;
  formato: SynFormato;
  material: string;
  leccion: string;
  url?: string;
  dur?: string;
  real: boolean;
}
export interface DiaSynapse {
  d: number; fecha: string; wd: string; semana: number;
  faseId: 'f0' | 'f1'; fase: string; bloques: SynBloque[];
}

export const SYN_PLAN_META = {
  inicio: '2026-07-09', fin: '2026-09-28', totalDias: 82, semanas: 12,
  bloque: "A 15' pantalla · B 10' audio · C 5' lectura · sáb PC 60-90' opcional · dom repaso",
  fases: { f0: 'F0 · La Escuela de Anthropic (sem 1-8)', f1: 'F1 · Código: Python (arranque, sem 9-12)' },
} as const;

export const SYN_DIAS: DiaSynapse[] = [
{d:1,fecha:"2026-07-09",wd:"Jue",semana:1,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Anthropic Academy",leccion:"Crea tu cuenta en la Academy y regístrate en \"AI Fluency: Framework & Foundations\" (Register · FREE). Hoy solo eso: deja la cuenta lista.",url:"https://www.anthropic.com/learn",real:true},{tag:"B",min:10,formato:"audio",material:"The Batch (Andrew Ng)",leccion:"El número de esta semana (sale los jueves): la carta de Ng + 2 noticias — 10 min y fuera",url:"https://www.deeplearning.ai/the-batch/",real:false},{tag:"C",min:5,formato:"lectura",material:"Automate the Boring Stuff (3ª ed.)",leccion:"5' del cap. 0: \"Introduction\"",url:"https://automatetheboringstuff.com/3e/chapter0.html",real:true}]},
{d:2,fecha:"2026-07-10",wd:"Vie",semana:1,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"AI Fluency: Framework & Foundations",leccion:"Lecciones \"Introduction to AI Fluency\" + \"Why do we need AI Fluency?\"",url:"https://anthropic.skilljar.com/ai-fluency-framework-foundations",real:true},{tag:"B",min:10,formato:"audio",material:"Canal Anthropic (YouTube)",leccion:"\"AI prompt engineering: A deep dive\" — tramo 1",url:"https://www.youtube.com/watch?v=T9aRN5JkmL8",real:true},{tag:"C",min:5,formato:"lectura",material:"Simon Willison",leccion:"The lethal trifecta for AI agents — EL artículo de seguridad de agentes",url:"https://simonwillison.net/2025/Jun/16/the-lethal-trifecta/",real:true}]},
{d:3,fecha:"2026-07-11",wd:"Sáb",semana:1,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"AI Fluency: Framework & Foundations",leccion:"Lección \"The 4D Framework\": Delegation · Description · Discernment · Diligence — el vocabulario interno de Anthropic",url:"https://anthropic.skilljar.com/ai-fluency-framework-foundations",real:true},{tag:"B",min:10,formato:"audio",material:"Comodín de audio",leccion:"Retoma el audio que quedó a medias esta semana (Lex, Dwarkesh o No Priors). Nada nuevo.",real:false},{tag:"C",min:5,formato:"lectura",material:"Comodín de lectura",leccion:"Termina la lectura que quedó a medias esta semana. Nada nuevo.",real:false},{tag:"PC",min:75,formato:"pc",material:"Setup del entorno",leccion:"Instala Python 3 + VS Code + Git. Deja la máquina lista para F1 — hoy solo instalar y verificar que corre.",url:"https://docs.python.org/3/tutorial/",real:true}]},
{d:4,fecha:"2026-07-12",wd:"Dom",semana:1,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"R",min:0,formato:"repaso",material:"Domingo LIBRE",leccion:"Domingo LIBRE (v3: todos los domingos sin actividad). Sin misión SYNAPSE hoy; si quieres conservar la racha, márcalo ✓ y listo.",real:true}]},
{d:5,fecha:"2026-07-13",wd:"Lun",semana:2,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"AI Fluency: Framework & Foundations",leccion:"Deep Dive 1: \"Generative AI fundamentals\" + \"Capabilities & limitations\"",url:"https://anthropic.skilljar.com/ai-fluency-framework-foundations",real:true},{tag:"B",min:10,formato:"audio",material:"No Priors (Sarah Guo + Elad Gil)",leccion:"Episodio de esta semana — el más reciente o el siguiente de tu cola (22-56 min: te da para 2-3 huecos)",url:"https://podcasts.apple.com/us/podcast/no-priors-artificial-intelligence-technology-startups/id1668002688",real:false},{tag:"C",min:5,formato:"lectura",material:"Pro Git (Scott Chacon)",leccion:"5' del cap. 1: \"Getting Started\" — sigue donde quedaste",url:"https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control",real:true}]},
{d:6,fecha:"2026-07-14",wd:"Mar",semana:2,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"AI Fluency: Framework & Foundations",leccion:"\"A closer look at Delegation\" + \"Project planning and Delegation\"",url:"https://anthropic.skilljar.com/ai-fluency-framework-foundations",real:true},{tag:"B",min:10,formato:"audio",material:"Dwarkesh — Dario Amodei",leccion:"Tramo 2/3 (10'): continúa donde quedaste del episodio (1h58)",url:"https://www.dwarkesh.com/p/dario-amodei",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"El siguiente artículo de la serie que no hayas leído (10-20 min: empiézalo, termínalo en otro hueco)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:7,fecha:"2026-07-15",wd:"Mié",semana:2,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"AI Fluency: Framework & Foundations",leccion:"\"A closer look at Description\" + Deep Dive 2: \"Effective prompting techniques\"",url:"https://anthropic.skilljar.com/ai-fluency-framework-foundations",real:true},{tag:"B",min:10,formato:"audio",material:"Lex #452 — Dario Amodei (CEO Anthropic)",leccion:"Outline cap. 2: \"Scaling laws\" (desde 10:19)",url:"https://lexfridman.com/dario-amodei",dur:"desde 10:19",real:true},{tag:"C",min:5,formato:"lectura",material:"The Python Tutorial (docs oficiales)",leccion:"Sección 2: \"Using the Python Interpreter\" — prepara el terreno para CS50P",url:"https://docs.python.org/3/tutorial/interpreter.html",real:true}]},
{d:8,fecha:"2026-07-16",wd:"Jue",semana:2,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"AI Fluency: Framework & Foundations",leccion:"\"A closer look at Discernment\" + \"The Description-Discernment loop\"",url:"https://anthropic.skilljar.com/ai-fluency-framework-foundations",real:true},{tag:"B",min:10,formato:"audio",material:"The Batch (Andrew Ng)",leccion:"El número de esta semana (sale los jueves): la carta de Ng + 2 noticias — 10 min y fuera",url:"https://www.deeplearning.ai/the-batch/",real:false},{tag:"C",min:5,formato:"lectura",material:"Automate the Boring Stuff (3ª ed.)",leccion:"5' del cap. 1: \"Python Basics\"",url:"https://automatetheboringstuff.com/3e/chapter1.html",real:true}]},
{d:9,fecha:"2026-07-17",wd:"Vie",semana:2,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"AI Fluency: Framework & Foundations",leccion:"\"A closer look at Diligence\" — la D que separa uso casual de uso profesional",url:"https://anthropic.skilljar.com/ai-fluency-framework-foundations",real:true},{tag:"B",min:10,formato:"audio",material:"Canal Anthropic (YouTube)",leccion:"\"AI prompt engineering: A deep dive\" — tramo 2 (termínalo)",url:"https://www.youtube.com/watch?v=T9aRN5JkmL8",real:true},{tag:"C",min:5,formato:"lectura",material:"Anthropic Research",leccion:"Many-shot jailbreaking — cómo se rompe un LLM con contexto largo",url:"https://www.anthropic.com/research/many-shot-jailbreaking",real:true}]},
{d:10,fecha:"2026-07-18",wd:"Sáb",semana:2,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"AI Fluency: Framework & Foundations",leccion:"\"Conclusion\" + evaluación final → descarga tu CERTIFICADO (1º entregable de F0)",url:"https://anthropic.skilljar.com/ai-fluency-framework-foundations",real:true},{tag:"B",min:10,formato:"audio",material:"Comodín de audio",leccion:"Retoma el audio que quedó a medias esta semana (Lex, Dwarkesh o No Priors). Nada nuevo.",real:false},{tag:"C",min:5,formato:"lectura",material:"Comodín de lectura",leccion:"Termina la lectura que quedó a medias esta semana. Nada nuevo.",real:false},{tag:"PC",min:75,formato:"pc",material:"AI Fluency",leccion:"Ponte al día con las lecciones pendientes y deja el certificado descargado.",url:"https://anthropic.skilljar.com/ai-fluency-framework-foundations",real:true}]},
{d:11,fecha:"2026-07-19",wd:"Dom",semana:2,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"R",min:0,formato:"repaso",material:"Domingo LIBRE",leccion:"Domingo LIBRE (v3: todos los domingos sin actividad). Sin misión SYNAPSE hoy; si quieres conservar la racha, márcalo ✓ y listo.",real:true}]},
{d:12,fecha:"2026-07-20",wd:"Lun",semana:3,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Claude 101",leccion:"Módulo \"Meet Claude\": What is Claude? · Your first conversation · Getting better results · Desktop app (Chat, Cowork, Code)",url:"https://anthropic.skilljar.com/claude-101",real:true},{tag:"B",min:10,formato:"audio",material:"No Priors (Sarah Guo + Elad Gil)",leccion:"Episodio de esta semana — el más reciente o el siguiente de tu cola (22-56 min: te da para 2-3 huecos)",url:"https://podcasts.apple.com/us/podcast/no-priors-artificial-intelligence-technology-startups/id1668002688",real:false},{tag:"C",min:5,formato:"lectura",material:"Pro Git (Scott Chacon)",leccion:"5' del cap. 2: \"Git Basics\" — sigue donde quedaste",url:"https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository",real:true}]},
{d:13,fecha:"2026-07-21",wd:"Mar",semana:3,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Claude 101",leccion:"Módulo \"Organizing your work and knowledge\": projects · artifacts · skills",url:"https://anthropic.skilljar.com/claude-101",real:true},{tag:"B",min:10,formato:"audio",material:"Dwarkesh — Dario Amodei",leccion:"Tramo 3/3 (10'): continúa donde quedaste del episodio (1h58)",url:"https://www.dwarkesh.com/p/dario-amodei",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"El siguiente artículo de la serie que no hayas leído (10-20 min: empiézalo, termínalo en otro hueco)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:14,fecha:"2026-07-22",wd:"Mié",semana:3,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Claude 101",leccion:"Módulo \"Expanding Claude's reach\": connecting your tools · enterprise search · research mode",url:"https://anthropic.skilljar.com/claude-101",real:true},{tag:"B",min:10,formato:"audio",material:"Lex #452 — Dario Amodei (CEO Anthropic)",leccion:"Outline cap. 3: \"Limits of LLM scaling\" (desde 19:25)",url:"https://lexfridman.com/dario-amodei",dur:"desde 19:25",real:true},{tag:"C",min:5,formato:"lectura",material:"The Python Tutorial (docs oficiales)",leccion:"Sección 3: \"An Informal Introduction to Python\" — prepara el terreno para CS50P",url:"https://docs.python.org/3/tutorial/introduction.html",real:true}]},
{d:15,fecha:"2026-07-23",wd:"Jue",semana:3,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Claude 101",leccion:"\"Putting it all together\" (use-cases by role · other ways to work) + \"What's next?\" → CERTIFICADO Claude 101",url:"https://anthropic.skilljar.com/claude-101",real:true},{tag:"B",min:10,formato:"audio",material:"The Batch (Andrew Ng)",leccion:"El número de esta semana (sale los jueves): la carta de Ng + 2 noticias — 10 min y fuera",url:"https://www.deeplearning.ai/the-batch/",real:false},{tag:"C",min:5,formato:"lectura",material:"Automate the Boring Stuff (3ª ed.)",leccion:"5' del cap. 2: \"if-else and Flow Control\"",url:"https://automatetheboringstuff.com/3e/chapter2.html",real:true}]},
{d:16,fecha:"2026-07-24",wd:"Vie",semana:3,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Claude Code 101",leccion:"\"What is Claude Code?\" + \"How Claude Code works\" — el agente con el que ya trabajas, por dentro",url:"https://anthropic.skilljar.com/claude-code-101",real:true},{tag:"B",min:10,formato:"audio",material:"Canal Anthropic (YouTube)",leccion:"\"Tips for building AI agents\" — completo",url:"https://www.youtube.com/watch?v=LP5OCa20Zpg",real:true},{tag:"C",min:5,formato:"lectura",material:"Anthropic Research",leccion:"Constitutional Classifiers — el estado del arte en DEFENSA",url:"https://www.anthropic.com/research/constitutional-classifiers",real:true}]},
{d:17,fecha:"2026-07-25",wd:"Sáb",semana:3,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Claude Code 101",leccion:"\"Installing Claude Code\" + \"Your first prompt\"",url:"https://anthropic.skilljar.com/claude-code-101",real:true},{tag:"B",min:10,formato:"audio",material:"Comodín de audio",leccion:"Retoma el audio que quedó a medias esta semana (Lex, Dwarkesh o No Priors). Nada nuevo.",real:false},{tag:"C",min:5,formato:"lectura",material:"Comodín de lectura",leccion:"Termina la lectura que quedó a medias esta semana. Nada nuevo.",real:false},{tag:"PC",min:75,formato:"pc",material:"Claude Code en vivo",leccion:"Instala Claude Code y lanza tu primer prompt en una carpeta real (lo de Code 101, practicado).",url:"https://anthropic.skilljar.com/claude-code-101",real:true}]},
{d:18,fecha:"2026-07-26",wd:"Dom",semana:3,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"R",min:0,formato:"repaso",material:"Domingo LIBRE",leccion:"Domingo LIBRE (v3: todos los domingos sin actividad). Sin misión SYNAPSE hoy; si quieres conservar la racha, márcalo ✓ y listo.",real:true}]},
{d:19,fecha:"2026-07-27",wd:"Lun",semana:4,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Claude Code 101",leccion:"Módulo \"Daily workflows\": the explore → plan → code → commit workflow · Context management · Code review",url:"https://anthropic.skilljar.com/claude-code-101",real:true},{tag:"B",min:10,formato:"audio",material:"No Priors (Sarah Guo + Elad Gil)",leccion:"Episodio de esta semana — el más reciente o el siguiente de tu cola (22-56 min: te da para 2-3 huecos)",url:"https://podcasts.apple.com/us/podcast/no-priors-artificial-intelligence-technology-startups/id1668002688",real:false},{tag:"C",min:5,formato:"lectura",material:"Pro Git (Scott Chacon)",leccion:"5' del cap. 2: \"Git Basics\" — sigue donde quedaste",url:"https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository",real:true}]},
{d:20,fecha:"2026-07-28",wd:"Mar",semana:4,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Claude Code 101",leccion:"Módulo \"Customizing\": CLAUDE.md · Subagents · Skills · MCP · Hooks + quiz final del curso",url:"https://anthropic.skilljar.com/claude-code-101",real:true},{tag:"B",min:10,formato:"audio",material:"Dwarkesh — Demis Hassabis",leccion:"Episodio de 1h (Nobel 2024 por AlphaFold): IA × ciencia — directo a tu perfil médico",url:"https://www.dwarkesh.com/p/demis-hassabis",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"El siguiente artículo de la serie que no hayas leído (10-20 min: empiézalo, termínalo en otro hueco)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:21,fecha:"2026-07-29",wd:"Mié",semana:4,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Claude Platform 101",leccion:"\"What is the Claude Developer Platform?\" + \"Your first API call\" + \"Choosing the right model\"",url:"https://anthropic.skilljar.com/claude-platform-101",real:true},{tag:"B",min:10,formato:"audio",material:"Lex #452 — Dario Amodei (CEO Anthropic)",leccion:"Outline cap. 4: \"Competition with OpenAI, Google, xAI, Meta\" (desde 27:51)",url:"https://lexfridman.com/dario-amodei",dur:"desde 27:51",real:true},{tag:"C",min:5,formato:"lectura",material:"The Python Tutorial (docs oficiales)",leccion:"Sección 4: \"More Control Flow Tools\" — prepara el terreno para CS50P",url:"https://docs.python.org/3/tutorial/controlflow.html",real:true}]},
{d:22,fecha:"2026-07-30",wd:"Jue",semana:4,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Claude Platform 101",leccion:"Módulo \"Teaching your Agent\": The agent loop explained · What is tool use? · What is thinking?",url:"https://anthropic.skilljar.com/claude-platform-101",real:true},{tag:"B",min:10,formato:"audio",material:"The Batch (Andrew Ng)",leccion:"El número de esta semana (sale los jueves): la carta de Ng + 2 noticias — 10 min y fuera",url:"https://www.deeplearning.ai/the-batch/",real:false},{tag:"C",min:5,formato:"lectura",material:"Automate the Boring Stuff (3ª ed.)",leccion:"5' del cap. 3: \"Loops\"",url:"https://automatetheboringstuff.com/3e/chapter3.html",real:true}]},
{d:23,fecha:"2026-07-31",wd:"Vie",semana:4,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Claude Platform 101",leccion:"\"Extending your Agent\" (built-in tools · skills · MCP · context) + \"Managed Agents\" + quiz → serie 101 COMPLETA",url:"https://anthropic.skilljar.com/claude-platform-101",real:true},{tag:"B",min:10,formato:"audio",material:"Canal Anthropic (YouTube)",leccion:"\"Building Anthropic | A conversation with our co-founders\" — tramo 1",url:"https://www.youtube.com/watch?v=om2lIWXLLN4",real:true},{tag:"C",min:5,formato:"lectura",material:"Anthropic",leccion:"Responsible Scaling Policy — los niveles ASL, lenguaje obligatorio del sector",url:"https://www.anthropic.com/news/anthropics-responsible-scaling-policy",real:true}]},
{d:24,fecha:"2026-08-01",wd:"Sáb",semana:4,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Building Effective AI Agents (ensayo)",leccion:"Parte I: \"What are agents?\" · \"When (and when not) to use agents\" · \"When and how to use frameworks\" · \"The augmented LLM\"",url:"https://www.anthropic.com/engineering/building-effective-agents",real:true},{tag:"B",min:10,formato:"audio",material:"Comodín de audio",leccion:"Retoma el audio que quedó a medias esta semana (Lex, Dwarkesh o No Priors). Nada nuevo.",real:false},{tag:"C",min:5,formato:"lectura",material:"Comodín de lectura",leccion:"Termina la lectura que quedó a medias esta semana. Nada nuevo.",real:false},{tag:"PC",min:75,formato:"pc",material:"Proyecto público #1",leccion:"Crea tu repo público \"synapse-journal\" en GitHub y sube tus notas Feynman de F0 (Pro Git cap. 6 te guía). El auditor fue claro: los proyectos públicos consiguen la entrevista.",url:"https://git-scm.com/book/en/v2/GitHub-Account-Setup-and-Configuration",real:true}]},
{d:25,fecha:"2026-08-02",wd:"Dom",semana:4,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"R",min:0,formato:"repaso",material:"Domingo LIBRE",leccion:"Domingo LIBRE (v3: todos los domingos sin actividad). Sin misión SYNAPSE hoy; si quieres conservar la racha, márcalo ✓ y listo.",real:true}]},
{d:26,fecha:"2026-08-03",wd:"Lun",semana:5,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Building Effective AI Agents (ensayo)",leccion:"Parte II: los 5 workflows — Prompt chaining · Routing · Parallelization · Orchestrator-workers · Evaluator-optimizer — + \"Agents\" + \"Summary\". Son pregunta de entrevista: apréndelos con nombre.",url:"https://www.anthropic.com/engineering/building-effective-agents",real:true},{tag:"B",min:10,formato:"audio",material:"No Priors (Sarah Guo + Elad Gil)",leccion:"Episodio de esta semana — el más reciente o el siguiente de tu cola (22-56 min: te da para 2-3 huecos)",url:"https://podcasts.apple.com/us/podcast/no-priors-artificial-intelligence-technology-startups/id1668002688",real:false},{tag:"C",min:5,formato:"lectura",material:"Pro Git (Scott Chacon)",leccion:"5' del cap. 3: \"Git Branching\" — sigue donde quedaste",url:"https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell",real:true}]},
{d:27,fecha:"2026-08-04",wd:"Mar",semana:5,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Karpathy — [1hr Talk] Intro to LLMs",leccion:"Part 1: LLMs (00:00 → 25:43): inference · training · LLM dreams · finetuning into an Assistant",url:"https://www.youtube.com/watch?v=zjkBMFhNj_g&t=0s",dur:"~26 min (2 huecos)",real:true},{tag:"B",min:10,formato:"audio",material:"Dwarkesh — Sholto & Trenton: How LLMs actually think",leccion:"Tramo 1/4 (10'): denso — interpretabilidad desde dentro de los labs",url:"https://www.dwarkesh.com/p/sholto-douglas-trenton-bricken",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"El siguiente artículo de la serie que no hayas leído (10-20 min: empiézalo, termínalo en otro hueco)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:28,fecha:"2026-08-05",wd:"Mié",semana:5,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Karpathy — [1hr Talk] Intro to LLMs",leccion:"Part 2: Future of LLMs (25:43 → 45:43): scaling laws · tool use · multimodality · System 1/2 · LLM OS",url:"https://www.youtube.com/watch?v=zjkBMFhNj_g&t=1543s",dur:"~20 min",real:true},{tag:"B",min:10,formato:"audio",material:"Lex #452 — Dario Amodei (CEO Anthropic)",leccion:"Outline cap. 5: \"Claude\" (desde 33:14)",url:"https://lexfridman.com/dario-amodei",dur:"desde 33:14",real:true},{tag:"C",min:5,formato:"lectura",material:"The Python Tutorial (docs oficiales)",leccion:"Sección 5: \"Data Structures\" — prepara el terreno para CS50P",url:"https://docs.python.org/3/tutorial/datastructures.html",real:true}]},
{d:29,fecha:"2026-08-06",wd:"Jue",semana:5,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Karpathy — [1hr Talk] Intro to LLMs",leccion:"Part 3: LLM Security (45:43 → fin): jailbreaks · prompt injection · data poisoning",url:"https://www.youtube.com/watch?v=zjkBMFhNj_g&t=2743s",dur:"~14 min",real:true},{tag:"B",min:10,formato:"audio",material:"The Batch (Andrew Ng)",leccion:"El número de esta semana (sale los jueves): la carta de Ng + 2 noticias — 10 min y fuera",url:"https://www.deeplearning.ai/the-batch/",real:false},{tag:"C",min:5,formato:"lectura",material:"Automate the Boring Stuff (3ª ed.)",leccion:"5' del cap. 4: \"Functions\"",url:"https://automatetheboringstuff.com/3e/chapter4.html",real:true}]},
{d:30,fecha:"2026-08-07",wd:"Vie",semana:5,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Karpathy — Deep Dive into LLMs",leccion:"Tramo 1/11 · caps 1-3: introduction · pretraining data (internet) · tokenization",url:"https://www.youtube.com/watch?v=7xTGNNLPyMI&t=0s",dur:"~14 min",real:true},{tag:"B",min:10,formato:"audio",material:"Canal Anthropic (YouTube)",leccion:"\"Building Anthropic | A conversation with our co-founders\" — tramo 2 (termínalo)",url:"https://www.youtube.com/watch?v=om2lIWXLLN4",real:true},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"Siguiente artículo de la serie (o un número atrasado de The Batch)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:31,fecha:"2026-08-08",wd:"Sáb",semana:5,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Karpathy — Deep Dive into LLMs",leccion:"Tramo 2/11 · caps 4-6: neural network I/O · internals · inference",url:"https://www.youtube.com/watch?v=7xTGNNLPyMI&t=867s",dur:"~17 min",real:true},{tag:"B",min:10,formato:"audio",material:"Comodín de audio",leccion:"Retoma el audio que quedó a medias esta semana (Lex, Dwarkesh o No Priors). Nada nuevo.",real:false},{tag:"C",min:5,formato:"lectura",material:"Comodín de lectura",leccion:"Termina la lectura que quedó a medias esta semana. Nada nuevo.",real:false},{tag:"PC",min:75,formato:"pc",material:"Karpathy — Deep Dive",leccion:"Sesión larga: adelanta 2-3 tramos del Deep Dive con notas en el repo.",url:"https://www.youtube.com/watch?v=7xTGNNLPyMI",real:true}]},
{d:32,fecha:"2026-08-09",wd:"Dom",semana:5,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"R",min:0,formato:"repaso",material:"Domingo LIBRE",leccion:"Domingo LIBRE (v3: todos los domingos sin actividad). Sin misión SYNAPSE hoy; si quieres conservar la racha, márcalo ✓ y listo.",real:true}]},
{d:33,fecha:"2026-08-10",wd:"Lun",semana:6,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Karpathy — Deep Dive into LLMs",leccion:"Tramo 3/11 · cap 7: GPT-2 — training and inference",url:"https://www.youtube.com/watch?v=7xTGNNLPyMI&t=1869s",dur:"~12 min",real:true},{tag:"B",min:10,formato:"audio",material:"No Priors (Sarah Guo + Elad Gil)",leccion:"Episodio de esta semana — el más reciente o el siguiente de tu cola (22-56 min: te da para 2-3 huecos)",url:"https://podcasts.apple.com/us/podcast/no-priors-artificial-intelligence-technology-startups/id1668002688",real:false},{tag:"C",min:5,formato:"lectura",material:"Pro Git (Scott Chacon)",leccion:"5' del cap. 3: \"Git Branching\" — sigue donde quedaste",url:"https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell",real:true}]},
{d:34,fecha:"2026-08-11",wd:"Mar",semana:6,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Karpathy — Deep Dive into LLMs",leccion:"Tramo 4/11 · cap 8: Llama 3.1 base model inference",url:"https://www.youtube.com/watch?v=7xTGNNLPyMI&t=2572s",dur:"~17 min",real:true},{tag:"B",min:10,formato:"audio",material:"Dwarkesh — Sholto & Trenton: How LLMs actually think",leccion:"Tramo 2/4 (10'): denso — interpretabilidad desde dentro de los labs",url:"https://www.dwarkesh.com/p/sholto-douglas-trenton-bricken",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"El siguiente artículo de la serie que no hayas leído (10-20 min: empiézalo, termínalo en otro hueco)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:35,fecha:"2026-08-12",wd:"Mié",semana:6,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Karpathy — Deep Dive into LLMs",leccion:"Tramo 5/11 · caps 9-10: pretraining → post-training · conversations",url:"https://www.youtube.com/watch?v=7xTGNNLPyMI&t=3563s",dur:"~21 min",real:true},{tag:"B",min:10,formato:"audio",material:"Lex #452 — Dario Amodei (CEO Anthropic)",leccion:"Outline cap. 6: \"Opus 3.5\" (desde 36:50)",url:"https://lexfridman.com/dario-amodei",dur:"desde 36:50",real:true},{tag:"C",min:5,formato:"lectura",material:"The Python Tutorial (docs oficiales)",leccion:"Sección 6: \"Modules\" — prepara el terreno para CS50P",url:"https://docs.python.org/3/tutorial/modules.html",real:true}]},
{d:36,fecha:"2026-08-13",wd:"Jue",semana:6,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Karpathy — Deep Dive into LLMs",leccion:"Tramo 6/11 · cap 11: hallucinations · tool use · knowledge/working memory",url:"https://www.youtube.com/watch?v=7xTGNNLPyMI&t=4832s",dur:"~21 min",real:true},{tag:"B",min:10,formato:"audio",material:"The Batch (Andrew Ng)",leccion:"El número de esta semana (sale los jueves): la carta de Ng + 2 noticias — 10 min y fuera",url:"https://www.deeplearning.ai/the-batch/",real:false},{tag:"C",min:5,formato:"lectura",material:"Automate the Boring Stuff (3ª ed.)",leccion:"5' del cap. 5: \"Debugging\"",url:"https://automatetheboringstuff.com/3e/chapter5.html",real:true}]},
{d:37,fecha:"2026-08-14",wd:"Vie",semana:6,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Karpathy — Deep Dive into LLMs",leccion:"Tramo 7/11 · caps 12-14: knowledge of self · models need tokens to think · spelling",url:"https://www.youtube.com/watch?v=7xTGNNLPyMI&t=6106s",dur:"~23 min",real:true},{tag:"B",min:10,formato:"audio",material:"Canal Anthropic (YouTube)",leccion:"\"How difficult is AI alignment? | Anthropic Research Salon\" — tramo 1",url:"https://www.youtube.com/watch?v=IPmt8b-qLgk",real:true},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"Siguiente artículo de la serie (o un número atrasado de The Batch)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:38,fecha:"2026-08-15",wd:"Sáb",semana:6,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Karpathy — Deep Dive into LLMs",leccion:"Tramo 8/11 · caps 15-17: jagged intelligence · supervised finetuning → reinforcement learning",url:"https://www.youtube.com/watch?v=7xTGNNLPyMI&t=7493s",dur:"~23 min",real:true},{tag:"B",min:10,formato:"audio",material:"Comodín de audio",leccion:"Retoma el audio que quedó a medias esta semana (Lex, Dwarkesh o No Priors). Nada nuevo.",real:false},{tag:"C",min:5,formato:"lectura",material:"Comodín de lectura",leccion:"Termina la lectura que quedó a medias esta semana. Nada nuevo.",real:false},{tag:"PC",min:75,formato:"pc",material:"Git real",leccion:"Pasa tus notas de 3B1B al repo synapse-journal: add → commit → push de verdad (Pro Git cap. 2).",url:"https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository",real:true}]},
{d:39,fecha:"2026-08-16",wd:"Dom",semana:6,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"R",min:0,formato:"repaso",material:"Domingo LIBRE",leccion:"Domingo LIBRE (v3: todos los domingos sin actividad). Sin misión SYNAPSE hoy; si quieres conservar la racha, márcalo ✓ y listo.",real:true}]},
{d:40,fecha:"2026-08-17",wd:"Lun",semana:7,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Karpathy — Deep Dive into LLMs",leccion:"Tramo 9/11 · caps 18-19: DeepSeek-R1 · AlphaGo",url:"https://www.youtube.com/watch?v=7xTGNNLPyMI&t=8867s",dur:"~21 min",real:true},{tag:"B",min:10,formato:"audio",material:"No Priors (Sarah Guo + Elad Gil)",leccion:"Episodio de esta semana — el más reciente o el siguiente de tu cola (22-56 min: te da para 2-3 huecos)",url:"https://podcasts.apple.com/us/podcast/no-priors-artificial-intelligence-technology-startups/id1668002688",real:false},{tag:"C",min:5,formato:"lectura",material:"Pro Git (Scott Chacon)",leccion:"5' del cap. 6: \"GitHub\" — sigue donde quedaste",url:"https://git-scm.com/book/en/v2/GitHub-Account-Setup-and-Configuration",real:true}]},
{d:41,fecha:"2026-08-18",wd:"Mar",semana:7,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Karpathy — Deep Dive into LLMs",leccion:"Tramo 10/11 · cap 20: reinforcement learning from human feedback (RLHF)",url:"https://www.youtube.com/watch?v=7xTGNNLPyMI&t=10106s",dur:"~21 min",real:true},{tag:"B",min:10,formato:"audio",material:"Dwarkesh — Sholto & Trenton: How LLMs actually think",leccion:"Tramo 3/4 (10'): denso — interpretabilidad desde dentro de los labs",url:"https://www.dwarkesh.com/p/sholto-douglas-trenton-bricken",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"El siguiente artículo de la serie que no hayas leído (10-20 min: empiézalo, termínalo en otro hueco)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:42,fecha:"2026-08-19",wd:"Mié",semana:7,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"Karpathy — Deep Dive into LLMs",leccion:"Tramo 11/11 · caps 21-24: preview of things to come · keeping track · where to find LLMs · grand summary",url:"https://www.youtube.com/watch?v=7xTGNNLPyMI&t=11379s",dur:"~21 min",real:true},{tag:"B",min:10,formato:"audio",material:"Lex #452 — Dario Amodei (CEO Anthropic)",leccion:"Outline cap. 7: \"Sonnet 3.5\" (desde 41:36)",url:"https://lexfridman.com/dario-amodei",dur:"desde 41:36",real:true},{tag:"C",min:5,formato:"lectura",material:"The Python Tutorial (docs oficiales)",leccion:"Sección 7: \"Input and Output\" — prepara el terreno para CS50P",url:"https://docs.python.org/3/tutorial/inputoutput.html",real:true}]},
{d:43,fecha:"2026-08-20",wd:"Jue",semana:7,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"3Blue1Brown — Neural networks",leccion:"But what is a neural network? | Deep learning chapter 1",url:"https://www.youtube.com/watch?v=aircAruvnKk",dur:"18:40 (duración según la playlist)",real:true},{tag:"B",min:10,formato:"audio",material:"The Batch (Andrew Ng)",leccion:"El número de esta semana (sale los jueves): la carta de Ng + 2 noticias — 10 min y fuera",url:"https://www.deeplearning.ai/the-batch/",real:false},{tag:"C",min:5,formato:"lectura",material:"Automate the Boring Stuff (3ª ed.)",leccion:"5' del cap. 6: \"Lists\"",url:"https://automatetheboringstuff.com/3e/chapter6.html",real:true}]},
{d:44,fecha:"2026-08-21",wd:"Vie",semana:7,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"3Blue1Brown — Neural networks",leccion:"Gradient descent, how neural networks learn | Deep Learning Chapter 2",url:"https://www.youtube.com/watch?v=IHZwWFHWa-w",dur:"20:33 (duración según la playlist)",real:true},{tag:"B",min:10,formato:"audio",material:"Canal Anthropic (YouTube)",leccion:"\"Interpretability: Understanding how AI models think\" — tramo 1",url:"https://www.youtube.com/watch?v=fGKNUvivvnc",real:true},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"Siguiente artículo de la serie (o un número atrasado de The Batch)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:45,fecha:"2026-08-22",wd:"Sáb",semana:7,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"3Blue1Brown — Neural networks",leccion:"Backpropagation, intuitively | Deep Learning Chapter 3",url:"https://www.youtube.com/watch?v=Ilg3gGewQ5U",dur:"12:47 (duración según la playlist)",real:true},{tag:"B",min:10,formato:"audio",material:"Comodín de audio",leccion:"Retoma el audio que quedó a medias esta semana (Lex, Dwarkesh o No Priors). Nada nuevo.",real:false},{tag:"C",min:5,formato:"lectura",material:"Comodín de lectura",leccion:"Termina la lectura que quedó a medias esta semana. Nada nuevo.",real:false},{tag:"PC",min:75,formato:"pc",material:"Prompt Engineering Interactive Tutorial",leccion:"Lee los caps. 1-3 del tutorial oficial en GitHub (36k★). Solo lectura: ejecutar notebooks vendrá en F4.",url:"https://github.com/anthropics/prompt-eng-interactive-tutorial",real:true}]},
{d:46,fecha:"2026-08-23",wd:"Dom",semana:7,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"R",min:0,formato:"repaso",material:"Domingo LIBRE",leccion:"Domingo LIBRE (v3: todos los domingos sin actividad). Sin misión SYNAPSE hoy; si quieres conservar la racha, márcalo ✓ y listo.",real:true}]},
{d:47,fecha:"2026-08-24",wd:"Lun",semana:8,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"3Blue1Brown — Neural networks",leccion:"Backpropagation calculus | Deep Learning Chapter 4",url:"https://www.youtube.com/watch?v=tIeHLnjs5U8",dur:"10:18 (duración según la playlist)",real:true},{tag:"B",min:10,formato:"audio",material:"No Priors (Sarah Guo + Elad Gil)",leccion:"Episodio de esta semana — el más reciente o el siguiente de tu cola (22-56 min: te da para 2-3 huecos)",url:"https://podcasts.apple.com/us/podcast/no-priors-artificial-intelligence-technology-startups/id1668002688",real:false},{tag:"C",min:5,formato:"lectura",material:"Pro Git (Scott Chacon)",leccion:"5' del cap. 6: \"GitHub\" — sigue donde quedaste",url:"https://git-scm.com/book/en/v2/GitHub-Account-Setup-and-Configuration",real:true}]},
{d:48,fecha:"2026-08-25",wd:"Mar",semana:8,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"3Blue1Brown — Neural networks",leccion:"Large Language Models explained briefly — repasa la serie hasta aquí en tus palabras",url:"https://www.youtube.com/watch?v=LPZh9BOjkQs",dur:"7:58 (duración según la playlist)",real:true},{tag:"B",min:10,formato:"audio",material:"Dwarkesh — Sholto & Trenton: How LLMs actually think",leccion:"Tramo 4/4 (10'): denso — interpretabilidad desde dentro de los labs",url:"https://www.dwarkesh.com/p/sholto-douglas-trenton-bricken",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"El siguiente artículo de la serie que no hayas leído (10-20 min: empiézalo, termínalo en otro hueco)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:49,fecha:"2026-08-26",wd:"Mié",semana:8,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"3Blue1Brown — Neural networks",leccion:"Transformers, the tech behind LLMs | Deep Learning Chapter 5 — 1ª mitad (para en ~min 14)",url:"https://www.youtube.com/watch?v=wjZofJX0v4M",dur:"27:14",real:true},{tag:"B",min:10,formato:"audio",material:"Lex #452 — Dario Amodei (CEO Anthropic)",leccion:"Outline cap. 8: \"Claude 4.0\" (desde 44:56)",url:"https://lexfridman.com/dario-amodei",dur:"desde 44:56",real:true},{tag:"C",min:5,formato:"lectura",material:"The Python Tutorial (docs oficiales)",leccion:"Sección 8: \"Errors and Exceptions\" — prepara el terreno para CS50P",url:"https://docs.python.org/3/tutorial/errors.html",real:true}]},
{d:50,fecha:"2026-08-27",wd:"Jue",semana:8,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"3Blue1Brown — Neural networks",leccion:"Transformers, the tech behind LLMs | Deep Learning Chapter 5 — 2ª mitad (termina el vídeo)",url:"https://www.youtube.com/watch?v=wjZofJX0v4M",dur:"27:14",real:true},{tag:"B",min:10,formato:"audio",material:"The Batch (Andrew Ng)",leccion:"El número de esta semana (sale los jueves): la carta de Ng + 2 noticias — 10 min y fuera",url:"https://www.deeplearning.ai/the-batch/",real:false},{tag:"C",min:5,formato:"lectura",material:"Automate the Boring Stuff (3ª ed.)",leccion:"5' del cap. 7: \"Dictionaries and Structuring Data\"",url:"https://automatetheboringstuff.com/3e/chapter7.html",real:true}]},
{d:51,fecha:"2026-08-28",wd:"Vie",semana:8,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"3Blue1Brown — Neural networks",leccion:"Attention in transformers, step-by-step | Deep Learning Chapter 6 — 1ª mitad",url:"https://www.youtube.com/watch?v=eMlx5fFNoYc",dur:"26:10",real:true},{tag:"B",min:10,formato:"audio",material:"Canal Anthropic (YouTube)",leccion:"termina los tramos pendientes de las semanas previas",url:"https://www.youtube.com/@anthropic-ai",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"Siguiente artículo de la serie (o un número atrasado de The Batch)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:52,fecha:"2026-08-29",wd:"Sáb",semana:8,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"A",min:15,formato:"pantalla",material:"3Blue1Brown — Neural networks",leccion:"Attention in transformers, step-by-step | Deep Learning Chapter 6 — 2ª mitad",url:"https://www.youtube.com/watch?v=eMlx5fFNoYc",dur:"26:10",real:true},{tag:"B",min:10,formato:"audio",material:"Comodín de audio",leccion:"Retoma el audio que quedó a medias esta semana (Lex, Dwarkesh o No Priors). Nada nuevo.",real:false},{tag:"C",min:5,formato:"lectura",material:"Comodín de lectura",leccion:"Termina la lectura que quedó a medias esta semana. Nada nuevo.",real:false},{tag:"PC",min:75,formato:"pc",material:"CIERRE F0",leccion:"Certificados al repo + README \"los 5 patrones de agentes en mis palabras\". Bonus: \"But how do AI images and videos actually work? | Guest video by Welch Labs\" (37:20).",url:"https://www.youtube.com/watch?v=iv-5mZ_9CPY",real:true}]},
{d:53,fecha:"2026-08-30",wd:"Dom",semana:8,faseId:"f0",fase:"F0 · La Escuela de Anthropic",bloques:[{tag:"R",min:0,formato:"repaso",material:"Domingo LIBRE",leccion:"Domingo LIBRE (v3: todos los domingos sin actividad). Sin misión SYNAPSE hoy; si quieres conservar la racha, márcalo ✓ y listo.",real:true}]},
{d:54,fecha:"2026-08-31",wd:"Lun",semana:9,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"3Blue1Brown — Neural networks",leccion:"How might LLMs store facts | Deep Learning Chapter 7 → CIERRE F0: ya puedes explicar un LLM por dentro",url:"https://www.youtube.com/watch?v=9-Jl0dxWQs8",dur:"22:43",real:true},{tag:"B",min:10,formato:"audio",material:"No Priors (Sarah Guo + Elad Gil)",leccion:"Episodio de esta semana — el más reciente o el siguiente de tu cola (22-56 min: te da para 2-3 huecos)",url:"https://podcasts.apple.com/us/podcast/no-priors-artificial-intelligence-technology-startups/id1668002688",real:false},{tag:"C",min:5,formato:"lectura",material:"Pro Git (Scott Chacon)",leccion:"5' del cap. 7: \"Git Tools\" — sigue donde quedaste",url:"https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection",real:true}]},
{d:55,fecha:"2026-09-01",wd:"Mar",semana:9,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 0: Functions, Variables",leccion:"Lecture — tramo 1/5 (15'): empieza desde el minuto 0",url:"https://cs50.harvard.edu/python/weeks/0/",real:true},{tag:"B",min:10,formato:"audio",material:"Latent Space — The AI Engineer Podcast",leccion:"Episodio reciente a elección (el podcast del rol al que apuntas)",url:"https://www.latent.space/",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"El siguiente artículo de la serie que no hayas leído (10-20 min: empiézalo, termínalo en otro hueco)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:56,fecha:"2026-09-02",wd:"Mié",semana:9,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 0: Functions, Variables",leccion:"Lecture — tramo 2/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/0/",real:true},{tag:"B",min:10,formato:"audio",material:"Lex #452 — Dario Amodei (CEO Anthropic)",leccion:"Outline cap. 9: \"Criticism of Claude\" (desde 49:07)",url:"https://lexfridman.com/dario-amodei",dur:"desde 49:07",real:true},{tag:"C",min:5,formato:"lectura",material:"The Python Tutorial (docs oficiales)",leccion:"Sección 9: \"Classes\" — prepara el terreno para CS50P",url:"https://docs.python.org/3/tutorial/classes.html",real:true}]},
{d:57,fecha:"2026-09-03",wd:"Jue",semana:9,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 0: Functions, Variables",leccion:"Lecture — tramo 3/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/0/",real:true},{tag:"B",min:10,formato:"audio",material:"The Batch (Andrew Ng)",leccion:"El número de esta semana (sale los jueves): la carta de Ng + 2 noticias — 10 min y fuera",url:"https://www.deeplearning.ai/the-batch/",real:false},{tag:"C",min:5,formato:"lectura",material:"Automate the Boring Stuff (3ª ed.)",leccion:"5' del cap. 8: \"Strings and Text Editing\"",url:"https://automatetheboringstuff.com/3e/chapter8.html",real:true}]},
{d:58,fecha:"2026-09-04",wd:"Vie",semana:9,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 0: Functions, Variables",leccion:"Lecture — tramo 4/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/0/",real:true},{tag:"B",min:10,formato:"audio",material:"Canal Anthropic (YouTube)",leccion:"Siguiente vídeo del canal que no hayas visto (elige uno de 10-20 min)",url:"https://www.youtube.com/@anthropic-ai",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"Siguiente artículo de la serie (o un número atrasado de The Batch)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:59,fecha:"2026-09-05",wd:"Sáb",semana:9,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 0: Functions, Variables",leccion:"Lecture — tramo 5/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/0/",real:true},{tag:"B",min:10,formato:"audio",material:"Comodín de audio",leccion:"Retoma el audio que quedó a medias esta semana (Lex, Dwarkesh o No Priors). Nada nuevo.",real:false},{tag:"C",min:5,formato:"lectura",material:"Comodín de lectura",leccion:"Termina la lectura que quedó a medias esta semana. Nada nuevo.",real:false},{tag:"PC",min:75,formato:"pc",material:"CS50P — Problem Set 0",leccion:"Resuelve el Problem Set de la Week 0 en el editor web de CS50.",url:"https://cs50.harvard.edu/python/weeks/0/",real:true}]},
{d:60,fecha:"2026-09-06",wd:"Dom",semana:9,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"R",min:0,formato:"repaso",material:"Domingo LIBRE",leccion:"Domingo LIBRE (v3: todos los domingos sin actividad). Sin misión SYNAPSE hoy; si quieres conservar la racha, márcalo ✓ y listo.",real:true}]},
{d:61,fecha:"2026-09-07",wd:"Lun",semana:10,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 0: Functions, Variables",leccion:"Shorts de la Week 0 + cierra apuntes. El Problem Set va al bloque PC del sábado.",url:"https://cs50.harvard.edu/python/weeks/0/",real:true},{tag:"B",min:10,formato:"audio",material:"No Priors (Sarah Guo + Elad Gil)",leccion:"Episodio de esta semana — el más reciente o el siguiente de tu cola (22-56 min: te da para 2-3 huecos)",url:"https://podcasts.apple.com/us/podcast/no-priors-artificial-intelligence-technology-startups/id1668002688",real:false},{tag:"C",min:5,formato:"lectura",material:"Pro Git (Scott Chacon)",leccion:"5' del cap. 7: \"Git Tools\" — sigue donde quedaste",url:"https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection",real:true}]},
{d:62,fecha:"2026-09-08",wd:"Mar",semana:10,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 1: Conditionals",leccion:"Lecture — tramo 1/5 (15'): empieza desde el minuto 0",url:"https://cs50.harvard.edu/python/weeks/1/",real:true},{tag:"B",min:10,formato:"audio",material:"Latent Space — The AI Engineer Podcast",leccion:"Episodio reciente a elección (el podcast del rol al que apuntas)",url:"https://www.latent.space/",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"El siguiente artículo de la serie que no hayas leído (10-20 min: empiézalo, termínalo en otro hueco)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:63,fecha:"2026-09-09",wd:"Mié",semana:10,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 1: Conditionals",leccion:"Lecture — tramo 2/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/1/",real:true},{tag:"B",min:10,formato:"audio",material:"Lex #452 — Dario Amodei (CEO Anthropic)",leccion:"Outline cap. 10: \"AI Safety Levels\" (desde 1:01:54)",url:"https://lexfridman.com/dario-amodei",dur:"desde 1:01:54",real:true},{tag:"C",min:5,formato:"lectura",material:"The Python Tutorial (docs oficiales)",leccion:"Sección 10: \"Brief tour of the standard library\" — prepara el terreno para CS50P",url:"https://docs.python.org/3/tutorial/stdlib.html",real:true}]},
{d:64,fecha:"2026-09-10",wd:"Jue",semana:10,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 1: Conditionals",leccion:"Lecture — tramo 3/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/1/",real:true},{tag:"B",min:10,formato:"audio",material:"The Batch (Andrew Ng)",leccion:"El número de esta semana (sale los jueves): la carta de Ng + 2 noticias — 10 min y fuera",url:"https://www.deeplearning.ai/the-batch/",real:false},{tag:"C",min:5,formato:"lectura",material:"Automate the Boring Stuff (3ª ed.)",leccion:"5' del cap. 9: \"Text Pattern Matching with Regular Expressions\"",url:"https://automatetheboringstuff.com/3e/chapter9.html",real:true}]},
{d:65,fecha:"2026-09-11",wd:"Vie",semana:10,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 1: Conditionals",leccion:"Lecture — tramo 4/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/1/",real:true},{tag:"B",min:10,formato:"audio",material:"Canal Anthropic (YouTube)",leccion:"Siguiente vídeo del canal que no hayas visto (elige uno de 10-20 min)",url:"https://www.youtube.com/@anthropic-ai",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"Siguiente artículo de la serie (o un número atrasado de The Batch)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:66,fecha:"2026-09-12",wd:"Sáb",semana:10,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 1: Conditionals",leccion:"Lecture — tramo 5/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/1/",real:true},{tag:"B",min:10,formato:"audio",material:"Comodín de audio",leccion:"Retoma el audio que quedó a medias esta semana (Lex, Dwarkesh o No Priors). Nada nuevo.",real:false},{tag:"C",min:5,formato:"lectura",material:"Comodín de lectura",leccion:"Termina la lectura que quedó a medias esta semana. Nada nuevo.",real:false},{tag:"PC",min:75,formato:"pc",material:"CS50P — Problem Set 1",leccion:"Problem Set de la Week 1 (Conditionals) completo.",url:"https://cs50.harvard.edu/python/weeks/1/",real:true}]},
{d:67,fecha:"2026-09-13",wd:"Dom",semana:10,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"R",min:0,formato:"repaso",material:"Domingo LIBRE",leccion:"Domingo LIBRE (v3: todos los domingos sin actividad). Sin misión SYNAPSE hoy; si quieres conservar la racha, márcalo ✓ y listo.",real:true}]},
{d:68,fecha:"2026-09-14",wd:"Lun",semana:11,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 1: Conditionals",leccion:"Shorts de la Week 1 + cierra apuntes. El Problem Set va al bloque PC del sábado.",url:"https://cs50.harvard.edu/python/weeks/1/",real:true},{tag:"B",min:10,formato:"audio",material:"No Priors (Sarah Guo + Elad Gil)",leccion:"Episodio de esta semana — el más reciente o el siguiente de tu cola (22-56 min: te da para 2-3 huecos)",url:"https://podcasts.apple.com/us/podcast/no-priors-artificial-intelligence-technology-startups/id1668002688",real:false},{tag:"C",min:5,formato:"lectura",material:"Pro Git (Scott Chacon)",leccion:"5' del cap. 5: \"Distributed Git\" — sigue donde quedaste",url:"https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows",real:true}]},
{d:69,fecha:"2026-09-15",wd:"Mar",semana:11,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 2: Loops",leccion:"Lecture — tramo 1/5 (15'): empieza desde el minuto 0",url:"https://cs50.harvard.edu/python/weeks/2/",real:true},{tag:"B",min:10,formato:"audio",material:"Latent Space — The AI Engineer Podcast",leccion:"Episodio reciente a elección (el podcast del rol al que apuntas)",url:"https://www.latent.space/",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"El siguiente artículo de la serie que no hayas leído (10-20 min: empiézalo, termínalo en otro hueco)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:70,fecha:"2026-09-16",wd:"Mié",semana:11,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 2: Loops",leccion:"Lecture — tramo 2/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/2/",real:true},{tag:"B",min:10,formato:"audio",material:"Lex #452 — Dario Amodei (CEO Anthropic)",leccion:"Outline cap. 11: \"ASL-3 and ASL-4\" (desde 1:12:42)",url:"https://lexfridman.com/dario-amodei",dur:"desde 1:12:42",real:true},{tag:"C",min:5,formato:"lectura",material:"The Python Tutorial (docs oficiales)",leccion:"Sección 11: \"Brief tour of the standard library — part II\" — prepara el terreno para CS50P",url:"https://docs.python.org/3/tutorial/stdlib2.html",real:true}]},
{d:71,fecha:"2026-09-17",wd:"Jue",semana:11,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 2: Loops",leccion:"Lecture — tramo 3/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/2/",real:true},{tag:"B",min:10,formato:"audio",material:"The Batch (Andrew Ng)",leccion:"El número de esta semana (sale los jueves): la carta de Ng + 2 noticias — 10 min y fuera",url:"https://www.deeplearning.ai/the-batch/",real:false},{tag:"C",min:5,formato:"lectura",material:"Automate the Boring Stuff (3ª ed.)",leccion:"5' del cap. 10: \"Reading and Writing Files\"",url:"https://automatetheboringstuff.com/3e/chapter10.html",real:true}]},
{d:72,fecha:"2026-09-18",wd:"Vie",semana:11,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 2: Loops",leccion:"Lecture — tramo 4/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/2/",real:true},{tag:"B",min:10,formato:"audio",material:"Canal Anthropic (YouTube)",leccion:"Siguiente vídeo del canal que no hayas visto (elige uno de 10-20 min)",url:"https://www.youtube.com/@anthropic-ai",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"Siguiente artículo de la serie (o un número atrasado de The Batch)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:73,fecha:"2026-09-19",wd:"Sáb",semana:11,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 2: Loops",leccion:"Lecture — tramo 5/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/2/",real:true},{tag:"B",min:10,formato:"audio",material:"Comodín de audio",leccion:"Retoma el audio que quedó a medias esta semana (Lex, Dwarkesh o No Priors). Nada nuevo.",real:false},{tag:"C",min:5,formato:"lectura",material:"Comodín de lectura",leccion:"Termina la lectura que quedó a medias esta semana. Nada nuevo.",real:false},{tag:"PC",min:75,formato:"pc",material:"CS50P — Problem Set 2",leccion:"Problem Set de la Week 2 (Loops) completo.",url:"https://cs50.harvard.edu/python/weeks/2/",real:true}]},
{d:74,fecha:"2026-09-20",wd:"Dom",semana:11,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"R",min:0,formato:"repaso",material:"Domingo LIBRE",leccion:"Domingo LIBRE (v3: todos los domingos sin actividad). Sin misión SYNAPSE hoy; si quieres conservar la racha, márcalo ✓ y listo.",real:true}]},
{d:75,fecha:"2026-09-21",wd:"Lun",semana:12,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 2: Loops",leccion:"Shorts de la Week 2 + cierra apuntes. El Problem Set va al bloque PC del sábado.",url:"https://cs50.harvard.edu/python/weeks/2/",real:true},{tag:"B",min:10,formato:"audio",material:"No Priors (Sarah Guo + Elad Gil)",leccion:"Episodio de esta semana — el más reciente o el siguiente de tu cola (22-56 min: te da para 2-3 huecos)",url:"https://podcasts.apple.com/us/podcast/no-priors-artificial-intelligence-technology-startups/id1668002688",real:false},{tag:"C",min:5,formato:"lectura",material:"Pro Git (Scott Chacon)",leccion:"5' del cap. 5: \"Distributed Git\" — sigue donde quedaste",url:"https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows",real:true}]},
{d:76,fecha:"2026-09-22",wd:"Mar",semana:12,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 3: Exceptions",leccion:"Lecture — tramo 1/5 (15'): empieza desde el minuto 0",url:"https://cs50.harvard.edu/python/weeks/3/",real:true},{tag:"B",min:10,formato:"audio",material:"Latent Space — The AI Engineer Podcast",leccion:"Episodio reciente a elección (el podcast del rol al que apuntas)",url:"https://www.latent.space/",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"El siguiente artículo de la serie que no hayas leído (10-20 min: empiézalo, termínalo en otro hueco)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:77,fecha:"2026-09-23",wd:"Mié",semana:12,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 3: Exceptions",leccion:"Lecture — tramo 2/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/3/",real:true},{tag:"B",min:10,formato:"audio",material:"Lex #452 — Dario Amodei (CEO Anthropic)",leccion:"Outline cap. 12: \"Computer use\" (desde 1:16:46)",url:"https://lexfridman.com/dario-amodei",dur:"desde 1:16:46",real:true},{tag:"C",min:5,formato:"lectura",material:"The Python Tutorial (docs oficiales)",leccion:"Sección 12: \"Virtual Environments and Packages\" — prepara el terreno para CS50P",url:"https://docs.python.org/3/tutorial/venv.html",real:true}]},
{d:78,fecha:"2026-09-24",wd:"Jue",semana:12,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 3: Exceptions",leccion:"Lecture — tramo 3/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/3/",real:true},{tag:"B",min:10,formato:"audio",material:"The Batch (Andrew Ng)",leccion:"El número de esta semana (sale los jueves): la carta de Ng + 2 noticias — 10 min y fuera",url:"https://www.deeplearning.ai/the-batch/",real:false},{tag:"C",min:5,formato:"lectura",material:"Automate the Boring Stuff (3ª ed.)",leccion:"5' del cap. 11: \"Organizing Files\"",url:"https://automatetheboringstuff.com/3e/chapter11.html",real:true}]},
{d:79,fecha:"2026-09-25",wd:"Vie",semana:12,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 3: Exceptions",leccion:"Lecture — tramo 4/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/3/",real:true},{tag:"B",min:10,formato:"audio",material:"Canal Anthropic (YouTube)",leccion:"Siguiente vídeo del canal que no hayas visto (elige uno de 10-20 min)",url:"https://www.youtube.com/@anthropic-ai",real:false},{tag:"C",min:5,formato:"lectura",material:"Simon Willison — serie Prompt injection",leccion:"Siguiente artículo de la serie (o un número atrasado de The Batch)",url:"https://simonwillison.net/series/prompt-injection/",real:false}]},
{d:80,fecha:"2026-09-26",wd:"Sáb",semana:12,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 3: Exceptions",leccion:"Lecture — tramo 5/5 (15'): retoma EXACTAMENTE donde quedaste",url:"https://cs50.harvard.edu/python/weeks/3/",real:true},{tag:"B",min:10,formato:"audio",material:"Comodín de audio",leccion:"Retoma el audio que quedó a medias esta semana (Lex, Dwarkesh o No Priors). Nada nuevo.",real:false},{tag:"C",min:5,formato:"lectura",material:"Comodín de lectura",leccion:"Termina la lectura que quedó a medias esta semana. Nada nuevo.",real:false},{tag:"PC",min:75,formato:"pc",material:"CS50P — Problem Set 3",leccion:"Problem Set de la Week 3 (Exceptions) completo.",url:"https://cs50.harvard.edu/python/weeks/3/",real:true}]},
{d:81,fecha:"2026-09-27",wd:"Dom",semana:12,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"R",min:0,formato:"repaso",material:"Domingo LIBRE",leccion:"Domingo LIBRE (v3: todos los domingos sin actividad). Sin misión SYNAPSE hoy; si quieres conservar la racha, márcalo ✓ y listo.",real:true}]},
{d:82,fecha:"2026-09-28",wd:"Lun",semana:12,faseId:"f1",fase:"F1 · Código: Python + terminal + Git",bloques:[{tag:"A",min:15,formato:"pantalla",material:"CS50P — Week 3: Exceptions",leccion:"Shorts de la Week 3 + cierra apuntes. El Problem Set va al bloque PC del sábado.",url:"https://cs50.harvard.edu/python/weeks/3/",real:true},{tag:"B",min:10,formato:"audio",material:"No Priors (Sarah Guo + Elad Gil)",leccion:"Episodio de esta semana — el más reciente o el siguiente de tu cola (22-56 min: te da para 2-3 huecos)",url:"https://podcasts.apple.com/us/podcast/no-priors-artificial-intelligence-technology-startups/id1668002688",real:false},{tag:"C",min:5,formato:"lectura",material:"Pro Git (Scott Chacon)",leccion:"5' del cap. 5: \"Distributed Git\" — sigue donde quedaste",url:"https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows",real:true},{tag:"PC",min:75,formato:"pc",material:"CS50P — Problem Set 3",leccion:"Problem Set de la Week 3 (Exceptions) completo.",url:"https://cs50.harvard.edu/python/weeks/3/",real:true}]}
];

export function synDiaDe(fechaISO: string): DiaSynapse | undefined { return SYN_DIAS.find(x => x.fecha === fechaISO); }
export function syn7d(fromD: number): DiaSynapse[] { return SYN_DIAS.filter(x => x.d >= fromD && x.d < fromD + 7); }

export const SYN_FORMATO_ICON: Record<SynFormato, string> = {
  pantalla: '📱', audio: '🎧', lectura: '📖', pc: '⌨️', repaso: '🌿',
};
export const SYN_TAG_LABEL: Record<SynBloque['tag'], string> = {
  A: "A · 15' lección", B: "B · 10' audio", C: "C · 5' lectura", PC: "PC · 60-90' (opcional)", R: "Repaso · 30'",
};
