/**
 * vibecodingPlan.ts — Motor día-a-día del VIBECODING 04:15-05:00 (L-V, 45') · 12 proyectos S1-S12 ·
 * 60 días hábiles · 2026-09-07 → 2026-11-27 (sáb y dom libres; sábado PC SYNAPSE = SHIP del proyecto).
 * GENERADO por DATA/_scripts/gen_vibecoding_plan.js desde DATA/SYNAPSE/vibecoding_proyectos.json.
 * NO editar a mano — regenerar: node DATA/_scripts/gen_vibecoding_plan.js YYYY-MM-DD
 *
 * Filosofía (CURSO_IA_04H_31AGO.md): builder, no estudiante. Cada semana termina 1 proyecto REAL con
 * entregable verificable (commit / URL viva / test verde) y criterio de aceptación — se mide por OUTPUT,
 * no por tiempo sentado (Palmerton). Ciclo diario: 5' objetivo → 35' construir → 5' commit + nota synapse-journal.
 * Progreso REAL manual: PlanKey 'vibecoding' (studyProgress.ts), empieza 0%.
 * Semana DELOAD (post-NBME 26): carga 50% (2 días de 45' + 3 de 15'), fechas intactas.
 */
export type VibeRotacion = 'yocpmd' | 'preguntas' | 'bots' | 'contenido';
export type VibeTipo = 'definir' | 'construir' | 'verificar' | 'ship-prep';
export interface VibeDoc { label: string; url: string }
export interface VibeProyecto {
  s: number; id: string; nombre: string; rotacion: VibeRotacion; deload: boolean;
  ini: string; fin: string; ship: string;            // L-V del proyecto + sábado de SHIP (PC SYNAPSE)
  sirveA: string; objetivo: string; entregable: string; aceptacion: string[]; repo: string;
  docs: VibeDoc[]; pasos: string[]; shipTxt: string;
}
export interface DiaVibe {
  d: number; fecha: string; wd: string; semana: number; proyecto: string; k: number;
  tipo: VibeTipo; min: number; deload: boolean; paso: string;
}

export const VIBE_META = {
  inicio: '2026-09-07', fin: '2026-11-27', totalDias: 60, semanas: 12,
  franja: "04:15–05:00 L-V (45') · sáb 15:00-17:00 PC SYNAPSE = SHIP · dom = Feynman del proyecto (10', opcional)",
  ciclo: "5' objetivo → 35' construir con Claude Code → 5' commit + nota synapse-journal",
  rotacion: { yocpmd: 'Automatización YoCPMD', preguntas: 'Pipeline de preguntas ENCAPS/USMLE', bots: 'Bots CRM Pulso / LIVIANO', contenido: 'Contenido IA para las marcas' },
} as const;

export const VIBE_PROYECTOS: VibeProyecto[] = [
{s:1,id:"apex-parser",nombre:"Fix parser APEX (P0-2 / P0-3) + test multilínea",rotacion:"yocpmd",deload:false,ini:"2026-09-07",fin:"2026-09-11",ship:"2026-09-12",sirveA:"USMLE — el plan de 97 días apoya en ≤10 tarjetas de MECANISMO/día vía APEX; hoy el parser trunca REVERSO/CASO_CLINICO/FISIO_EXPANDIDA a la 1ª línea (verificado 4-sep, mtime 7-may)",objetivo:"Que un APEX multilínea llegue ÍNTEGRO a Anki (tarjeta) y a Obsidian (nota con caso_clinico + fisio_expandida).",entregable:"Commit en D:/agente_estudio (parsers + creador de nota) + scripts/test_parser_multilinea.js verde (3/3) + 1 APEX de prueba íntegro en Anki y en el vault (is_test=true).",aceptacion:["node scripts/test_parser_multilinea.js → 3/3 OK (REVERSO, CASO_CLINICO, FISIO_EXPANDIDA con ≥3 líneas cada uno)","Tarjeta de prueba en Anki con el REVERSO completo (no solo la 1ª línea)","Nota en 01_USMLE con las secciones caso_clinico y fisio_expandida renderizadas","n8n_parser_v2_3.js re-pegado en el nodo Code de n8n (redeploy) y hash del commit anotado en synapse-journal"],repo:"D:/agente_estudio/scripts (node_parsear_tarjeta_v2_3.js:27 · n8n_parser_v2_3.js:56 · node_crear_nota_v2_3.js)",docs:[{label:"Claude Code — Best practices (verificar con un test que Claude pueda correr)",url:"https://code.claude.com/docs/en/best-practices"},{label:"Claude Code — Automate actions with hooks",url:"https://code.claude.com/docs/en/hooks-guide"}],pasos:["Reproducir el bug: pegar un APEX con REVERSO de 3 líneas por node scripts/node_parsear_tarjeta_v2_3.js y ver el truncado. Escribir scripts/test_parser_multilinea.js con 3 fixtures que HOY fallan (rojo). Objetivo del día: test rojo reproducible.","P0-2: cambiar el lookahead en node_parsear_tarjeta_v2_3.js:27 y n8n_parser_v2_3.js:56 a (?=\\n[A-Z_]+:|\\n═|(?![\\s\\S])) (sin '$' bajo flag m). Correr el test → verde.","P0-3: node_crear_nota_v2_3.js renderiza caso_clinico y fisio_expandida en la nota Obsidian (sección condicional si viene vacía). Test de la nota con fixture.","Verificar en vivo: pegar n8n_parser_v2_3.js en el nodo Code de n8n (redeploy), enviar 1 APEX de prueba (Ctrl+Shift+A, is_test) → abrir Anki y el vault y comprobar que llega íntegro.","Commit en agente_estudio + cerrar P0-2/P0-3 en DATA/ENCAPS/AUDITORIA_AGENTE_ESTUDIO_2026-07-02.md (fecha) + nota synapse-journal. Preparar el SHIP del sábado: lista de lo que falta (T1/T2/T3 Palmerton = P1-6, queda para otra semana)."],shipTxt:"SHIP S1: test verde + tarjeta y nota de prueba íntegras + commit. Si algo falla, el sábado PC se usa para cerrarlo; no se arrastra a S2."},
{s:2,id:"anki-telemetria",nombre:"Telemetría AnkiConnect en producción (due / backlog / retención)",rotacion:"yocpmd",deload:false,ini:"2026-09-14",fin:"2026-09-18",ship:"2026-09-19",sirveA:"USMLE — la alarma G de Palmerton 'capar u omitir revisiones vencidas → avalancha' no tiene detector; el Anki de sáb/dom (30'/15') se dimensiona a ojo",objetivo:"Un JSON diario automático con due, backlog (vencidas), revisadas hoy, % Again y retención FSRS del deck USMLE + KPI visible en el Home.",entregable:"DATA/USMLE/_anki_telemetria.json con ≥5 días consecutivos generados sin intervención + KPI 'Due/backlog/retención' en CockpitStatusBar + tarea programada.",aceptacion:["node DATA/_scripts/anki_telemetria.js con Anki abierto coincide (±5%) con la pantalla Stats de Anki","5 entradas consecutivas en _anki_telemetria.json generadas por la tarea programada (schtasks) o por un hook SessionEnd","CockpitStatusBar muestra Due/backlog/retención del último JSON (localStorage 'jmd-anki-telemetria')","El script imprime los minutos recomendados del Anki de finde (due × 20 s) y avisa si backlog > 100"],repo:"D:/joseph-md-app/DATA/_scripts/anki_telemetria.js (v1 ya existe: hoy tolera Anki cerrado) · src/components/home/CockpitStatusBar.tsx",docs:[{label:"AnkiConnect — repositorio oficial (API JSON en localhost:8765)",url:"https://git.sr.ht/~foosoft/anki-connect"},{label:"AnkiConnect — add-on en AnkiWeb (2055492159)",url:"https://ankiweb.net/shared/info/2055492159"},{label:"Claude Code — Run prompts on a schedule",url:"https://code.claude.com/docs/en/scheduled-tasks"}],pasos:["Correr node DATA/_scripts/anki_telemetria.js con Anki abierto. Comparar due/backlog/revisadas con la pantalla Stats de Anki y anotar discrepancias (deck pattern APEX::USMLE* vs AnKing).","Retención real: usar cardReviews de los últimos 30 días (reviewType=1) y calcular 1 − Again/total; validar que getDeckConfig devuelve 10 nuevas/día y desired retention 0.9 (si no, corregir en Anki, no en el script).","Automatizar: tarea programada de Windows (schtasks /create … 21:05 L-D) o hook SessionEnd de Claude Code que ejecute el script; comprobar que escribe sin ventana abierta.","KPI en Home: pegar el one-liner localStorage que imprime el script y verificar en vivo que CockpitStatusBar lo muestra; opcional: servir el JSON desde public/ para no pegar a mano.","Regla 'Anki finde = due × 20 s' en DATA/SYNC_ANKI_OBSIDIAN_APP.md (ya escrita) + commit + nota synapse-journal."],shipTxt:"SHIP S2: 5 días de JSON + KPI en el Home + tarea programada activa."},
{s:3,id:"usmle-scores",nombre:"Captura diaria de scores USMLE → Supabase (pre-test / 30Q / eval + tipo de error)",rotacion:"preguntas",deload:false,ini:"2026-09-21",fin:"2026-09-25",ship:"2026-09-26",sirveA:"USMLE — sin scores no se puede aplicar el gate 80% de Palmerton, ni detectar el ~50% de errores de interpretación, ni comparar contra los mínimos on-track por hito, ni alimentar la revisión semanal",objetivo:"Registrar cada día 3 números (pre-test /10 · 30Q % · eval 18:00 %) + error dominante (knowledge / transfer / proceso) + CCSN, con fallback localStorage y espejo en Supabase.",entregable:"UsmleTodayPlan con 3 campos + selector de error → tabla usmle_daily_scores (o study_sim_scores con examen='USMLE') + ReadinessBar con media móvil 7d y distancia al mínimo on-track del próximo hito.",aceptacion:["5 días de scores reales persistidos (recargar la app y siguen) y visibles en Supabase","ReadinessBar muestra media 7d de eval y 'a X puntos del mínimo on-track del NBME 25 (≥51%)'","gen_revision_semanal.js importa los scores (la métrica 1 deja de decir 'sin dato')","Esquema documentado en src/lib/supabase-schema.sql (migración aplicada con Joseph, nunca automática)"],repo:"src/components/study/UsmleTodayPlan.tsx · src/components/study/ReadinessBar.tsx · src/lib/supabase.ts · src/lib/supabase-schema.sql",docs:[{label:"Supabase — JavaScript select (Getting your data · Querying with count)",url:"https://supabase.com/docs/reference/javascript/select"},{label:"Supabase — Row Level Security (Secure a table with RLS · Write a policy for each operation)",url:"https://supabase.com/docs/guides/database/postgres/row-level-security"},{label:"Claude Code — How Claude remembers your project (CLAUDE.md)",url:"https://code.claude.com/docs/en/memory"}],pasos:["Definir el esquema: tabla usmle_daily_scores(fecha date pk, pretest_10 int, q30_pct numeric, eval_pct numeric, error_dominante text, ccsn int, nota text) con RLS; escribir la migración en supabase-schema.sql (NO aplicar aún). Alternativa: study_sim_scores con examen='USMLE'.","UI: en UsmleTodayPlan añadir 3 inputs numéricos + selector knowledge/transfer/proceso + contador CCSN; guardar en localStorage 'jmd-usmle-scores' (try/catch) al instante.","Espejo: upsert en Supabase (anon + RLS por usuario) con reintento; lectura de los últimos 7 días para ReadinessBar (media móvil + distancia al mínimo on-track de la tabla Parte V).","Verificar en vivo (web): registrar los 3 valores de hoy, recargar, comprobar persistencia y la fila en Supabase (MCP execute_sql SELECT).","Conectar gen_revision_semanal.js (fuente usmle_daily_scores) + commit + nota synapse-journal."],shipTxt:"SHIP S3: 5 días de scores reales + ReadinessBar con media 7d + migración aplicada (con Joseph)."},
{s:4,id:"revision-semanal",nombre:"gen_revision_semanal.js en producción (10 métricas con dato real)",rotacion:"yocpmd",deload:false,ini:"2026-09-28",fin:"2026-10-02",ship:"2026-10-03",sirveA:"TODOS los frentes — el checklist G de Palmerton se revisaba solo en cada NBME (~3 semanas); con 1 día perdido = +1 hábil hace falta un ritual semanal de 20'",objetivo:"Que el sábado 07:15 la revisión ya esté pre-rellenada (Supabase + localStorage + AnkiConnect + JSON locales) y Joseph solo decida.",entregable:"DATA/USMLE/REVISIONES/S04_<fecha>.md con ≥8/10 métricas con dato real + _semanas.json con 4 entradas + export de localStorage automatizado.",aceptacion:["node DATA/_scripts/gen_revision_semanal.js genera S04 con ≥8 métricas reales (no 'sin dato')","_semanas.json tiene las entradas S1-S4 (append-only, sin duplicados)","El export de localStorage se hace con 1 clic/comando (skill o snippet), no copiando a mano","La tarjeta 'Semana N/20' del Home coincide con la semana de la revisión"],repo:"DATA/_scripts/gen_revision_semanal.js (v1 ya existe) · DATA/REVISION_SEMANAL.md · DATA/USMLE/REVISIONES/",docs:[{label:"Claude Code — Extend Claude with skills (Create your first skill)",url:"https://code.claude.com/docs/en/skills"},{label:"Claude Code — Run Claude Code programmatically (claude -p · --output-format json)",url:"https://code.claude.com/docs/en/headless"},{label:"Supabase — Data REST API",url:"https://supabase.com/docs/guides/api"}],pasos:["Correr node DATA/_scripts/gen_revision_semanal.js y listar cada métrica que sale 'sin dato'; elegir las 3 más baratas de conectar.","Conectar fuentes: scores USMLE (S3), telemetría Anki (S2), % ciego ENCAPS del viernes desde TRACKING_ERRORES/_registro_resoluciones.json (rondas de la semana).","Export de localStorage sin fricción: skill /export-ls (imprime el snippet de consola) o botón en la app que descarga jmd-*.json a DATA/USMLE/REVISIONES/_localstorage_export.json.","Generar la revisión de esta semana en seco, leerla completa, corregir la plantilla (DATA/REVISION_SEMANAL.md) donde no ayude a decidir.","Automatizar: viernes 21:00 el script pre-genera (schtasks o /schedule); sábado 07:15 Joseph rellena 20'. Commit + nota synapse-journal."],shipTxt:"SHIP S4: primera revisión semanal completa (sábado 3-oct 07:15-07:35) con ≥8/10 métricas reales."},
{s:5,id:"remap-verificado",nombre:"remap_todo.js: corrimiento de 1 comando + verificación automática",rotacion:"yocpmd",deload:false,ini:"2026-10-05",fin:"2026-10-09",ship:"2026-10-10",sirveA:"TODOS los planes — ya van 5 corrimientos (31-ago→7-sep) y cada uno exige 5 scripts a mano + execute_sql + docs; un error de fecha rompe el Home de todos los frentes",objetivo:"Un solo comando que encadene remap_inicio.js + gen_synapse_plan.js + gen_aurum_plan.js + gen_vibecoding_plan.js + gen_encaps_mantenimiento_2027.js y VERIFIQUE (nº de días, L-V, feriados, fechas monótonas, tsc) antes de dar el OK.",entregable:"DATA/_scripts/remap_todo.js <fecha> [--dry-run] + DATA/_scripts/verificar_planes.js + skill /remap.",aceptacion:["node DATA/_scripts/remap_todo.js 2026-10-12 --dry-run termina verde en < 2 min sin tocar el repo","verificar_planes.js detecta un sábado o un feriado inyectado a propósito en un .ts (test negativo)","La skill /remap <fecha> muestra el diff de fechas por plan y pide confirmación antes de escribir","El SQL de ENCAPS se genera pero NO se ejecuta (execute_sql sigue siendo manual con backup)"],repo:"DATA/_scripts/remap_inicio.js (leer, no romper sus regex) · gen_*_plan.js · .claude/skills/remap/SKILL.md",docs:[{label:"Claude Code — Extend Claude with skills (Pass arguments to skills · Pre-approve tools)",url:"https://code.claude.com/docs/en/skills"},{label:"Claude Code — Automate actions with hooks (PostToolUse · Stop)",url:"https://code.claude.com/docs/en/hooks-guide"},{label:"Claude Code — Hooks reference",url:"https://code.claude.com/docs/en/hooks"}],pasos:["Escribir remap_todo.js: encadena los 5 generadores con child_process, acepta --dry-run (trabaja sobre una copia temporal de src/lib) y resume fechas inicio→fin por plan.","verificar_planes.js: lee cada src/lib/*DailyPlan.ts y usmleStep1Daily.ts (regex fecha:\"20\\d\\d-\\d\\d-\\d\\d\"), falla si hay sáb/dom, 25-dic/31-dic/1-ene, duplicados o fechas no crecientes; imprime nº de días vs esperado (USMLE 97 · MIR 78 · LIVIANO 90 · SYNAPSE 82 · VIBE 60).","Skill /remap <fecha> (.claude/skills/remap/SKILL.md, disable-model-invocation: true): ejecuta el dry-run, muestra el diff y pide confirmación; hook PostToolUse opcional que corre verificar_planes.js al editar src/lib/*Plan.ts.","Prueba negativa: inyectar un sábado en una copia y ver que verificar_planes.js falla; prueba positiva con la fecha real.","Doc breve en DATA/_scripts (cabecera del script) + memoria de Claude (regla: usar remap_todo.js) + commit + nota synapse-journal."],shipTxt:"SHIP S5: remap_todo.js --dry-run verde + verificar_planes.js con test negativo + skill /remap."},
{s:6,id:"rls-datos-tesis",nombre:"RLS en datos_tesis y kappa_piloto (P0 de seguridad abierto desde el 2-jul)",rotacion:"yocpmd",deload:false,ini:"2026-10-12",fin:"2026-10-16",ship:"2026-10-17",sirveA:"Research — datos de menores (edad 14-18) en una tabla con RLS OFF y la anon key en un repo con remoto GitHub (verificado 5-sep: datos_tesis 55 filas RLS false, kappa_piloto RLS false)",objetivo:"Que la anon key NO pueda leer datos_tesis ni kappa_piloto; el pipeline de la tesis usa service_role desde .env local.",entregable:"Migración SQL (enable RLS + policies) aplicada con Joseph + scripts/test_rls_anon.js verde + get_advisors sin 'RLS disabled' para esas tablas.",aceptacion:["SELECT con anon key sobre datos_tesis devuelve 0 filas o 401 (test automático)","El pipeline Python de agente_estudio sigue escribiendo (service_role en .env, nunca en el repo)","get_advisors (security) no lista datos_tesis ni kappa_piloto","SECURITY_AUDIT.md de agente_estudio actualizado con fecha y hash"],repo:"D:/agente_estudio (SECURITY_AUDIT.md · SECURITY_AUDIT_PHASE_A_C.sql) · Supabase qacynpqdrorpuegsmtcy",docs:[{label:"Supabase — Row Level Security (Enable RLS and set the grants · Policy tests · Bypassing RLS)",url:"https://supabase.com/docs/guides/database/postgres/row-level-security"},{label:"Supabase — Data REST API",url:"https://supabase.com/docs/guides/api"}],pasos:["Inventario: quién lee/escribe datos_tesis y kappa_piloto (grep en agente_estudio + SECURITY_AUDIT_PHASE_A_C.sql ya existente); decidir política: solo service_role (pipeline) + rol médico.","Escribir la migración: alter table … enable row level security + policies; probar en una rama de Supabase (create_branch) o con --dry-run en local.","Mover el acceso del pipeline a SUPABASE_SERVICE_ROLE_KEY en .env (gitignored); comprobar que el pipeline sigue insertando.","scripts/test_rls_anon.js: con la anon key, SELECT → espera 0 filas/401; correr get_advisors y adjuntar salida.","Aplicar con Joseph (apply_migration, backup previo) + SECURITY_AUDIT.md + commit + nota synapse-journal."],shipTxt:"SHIP S6: RLS activo en producción + test anon verde + advisors limpio."},
{s:7,id:"vitals-puente",nombre:"Puente VITALS → rendimiento (sueño y agua cruzados con % eval)",rotacion:"yocpmd",deload:false,ini:"2026-10-19",fin:"2026-10-23",ship:"2026-10-24",sirveA:"USMLE + salud — VITALS ya registra mv_wellness_logs (tipo agua|sueno, 119 filas, misma Supabase) pero la doctrina 'si fallas <70% 3 días → bajar carga + dormir' no tiene datos con los que dispararse",objetivo:"Tabla 'sueño vs % eval' y 'noches <7h' en la revisión semanal + 'Sueño anoche: X h' en el Home + sugerencia automática de modo ÁMBAR si sueño <6h.",entregable:"gen_revision_semanal.js con la tabla sueño×eval real (7 noches) + CockpitStatusBar con sueño de anoche + TodayMission sugiere ÁMBAR (Joseph decide).",aceptacion:["La revisión semanal muestra 7 noches con horas reales y el cruce con eval % del mismo día","El Home muestra 'Sueño anoche: X h' (lectura RLS del usuario médico o JSON de la revisión)","Con sueño <6h el selector de modo de TodayMission propone ÁMBAR (no lo fuerza)","Quick-log de sueño/agua a las 07:00 registrado ≥5/7 días (hábito de 20 s en VITALS)"],repo:"VITALS/web (quick-log.tsx ya existe) · DATA/_scripts/gen_revision_semanal.js · src/components/home/CockpitStatusBar.tsx · src/components/home/TodayMission.tsx",docs:[{label:"Supabase — Row Level Security (auth.uid() · Helper functions)",url:"https://supabase.com/docs/guides/database/postgres/row-level-security"},{label:"Supabase — Build a User Management App with Expo React Native (Get API details · Account page)",url:"https://supabase.com/docs/guides/getting-started/tutorials/with-expo-react-native"}],pasos:["Consultar mv_wellness_logs (tipo sueno/agua) con la anon key: si RLS bloquea, definir la policy de lectura para el usuario médico (is_medico) o usar el JSON de la revisión como puente.","gen_revision_semanal.js: tabla sueño×eval por fecha (join con usmle_daily_scores de S3) + contador de noches <7h y <6h.","CockpitStatusBar: 'Sueño anoche: X h' (lectura del último log o del JSON) con try/catch y '—' si no hay dato.","TodayMission: si el sueño de anoche <6h → chip 'sugerido: ÁMBAR' junto al selector de modo (PROTOCOLO_MODO_MINIMO); Joseph decide.","Doc: fuente de datos en PROTOCOLO_MODO_MINIMO.md (sección Fuentes) + commit + nota synapse-journal."],shipTxt:"SHIP S7: revisión con 7 noches reales + sueño en el Home + sugerencia ÁMBAR funcionando."},
{s:8,id:"motor-preguntas-encaps",nombre:"Motor de preguntas ENCAPS semiautomático v0 (skill /pregunta-encaps) — semana DELOAD",rotacion:"preguntas",deload:true,ini:"2026-10-26",fin:"2026-10-30",ship:"2026-10-31",sirveA:"ENCAPS — la hora de banqueo 16:15 depende de que el chat genere preguntas con el mapa (pronóstico v3 + TRACKING_ERRORES) y registre la ronda; hoy es manual y se pierde data",objetivo:"Una skill que lea el mapa del examen y el perfil de errores, genere 5 viñetas ciegas (sin clave, fuente citada) y registre la ronda en _registro_resoluciones.json. Carga 50% (deload post-NBME 26).",entregable:".claude/skills/pregunta-encaps/SKILL.md + 1 ronda real de 5Q registrada con confianza/error/ruta.",aceptacion:["La skill genera 5 viñetas del subtema del día (rotación v3) sin claves inventadas (cita fuente real: QX/MINSA/clave oficial PDF)","La ronda se APENDA a DATA/ENCAPS/TRACKING_ERRORES/_registro_resoluciones.json con el esquema del README (tu/correcta/ok/confianza/error/ruta)","PERFIL_CONOCIMIENTO.md se actualiza con el % ciego real de la ronda","Deload respetado: 2 días de 45' + 3 días de ≤15'"],repo:".claude/skills/pregunta-encaps/ · DATA/ENCAPS/TRACKING_ERRORES/ · DATA/ENCAPS/PROTOCOLO_HORA_MANTENIMIENTO.md",docs:[{label:"Anthropic Academy — Introduction to agent skills",url:"https://anthropic.skilljar.com/introduction-to-agent-skills"},{label:"Claude Code — Extend Claude with skills (Inject dynamic context · Run skills in a subagent)",url:"https://code.claude.com/docs/en/skills"}],pasos:["(45') Escribir SKILL.md: lee PRONOSTICO v3 + rotación del día + PERFIL_CONOCIMIENTO → genera 5 viñetas ciegas, formato pregunta→solución interactiva, sin clave hasta que Joseph responda.","(15' deload) Revisar el formato de salida con 1 viñeta; nada más.","(45') Registro: la skill apenda la ronda a _registro_resoluciones.json (esquema README) y vuelca RONDAS/<codigo>_<fecha>.json.","(15' deload) Descanso activo: leer 1 ronda anterior y anotar 1 mejora.","(15') 1 ronda real de 5Q en la hora ENCAPS (16:15) registrada + commit + nota synapse-journal."],shipTxt:"SHIP S8 (deload): skill funcionando + 1 ronda registrada. Sin ampliar alcance."},
{s:9,id:"overlays-hitos",nombre:"Migrador de overlays de hitos del Calendar (UWSA/NBME) tras cada corrimiento",rotacion:"yocpmd",deload:false,ini:"2026-11-02",fin:"2026-11-06",ship:"2026-11-07",sirveA:"USMLE — los 9 viernes de hito son overlays naranjas del Calendar; cada corrimiento los desalinea del .ts y hoy se recrean a mano (recurrenceData del MCP está roto para UPDATE → delete + create)",objetivo:"Script que, dado el START, calcule las fechas de los hitos desde usmleStep1Daily.ts y emita el JSON de instrucciones delete_event/create_event (con la descripción del protocolo test-day) para ejecutarlo con confirmación.",entregable:"DATA/_scripts/gen_hitos_overlays.js <START> → DATA/USMLE/_hitos_overlays.json + diff contra el Calendar vivo (list_events) sin falsos positivos.",aceptacion:["El JSON contiene los 9-12 hitos (UWSA1, NBME 25-31, UWSA2, NBME 32/33, Free 120) con fecha = la del .ts","La descripción de cada overlay incluye el protocolo test-day (cronograma de breaks, Ziploc Break 1/2/3, almuerzo dentro del sim, sin carbohidratos simples) tomado de PALMERTON_POR_MATERIA §F","Un diff en seco contra el Calendar (search_events 'NBME') lista solo los overlays que cambian","Nada se ejecuta sin confirmación explícita de Joseph"],repo:"src/lib/usmleStep1Daily.ts (solo lectura) · DATA/USMLE/CALENDARIO_5_MESES.md · MCP Google Calendar",docs:[{label:"Claude Code — Connect Claude Code to tools via MCP (Installing MCP servers · Practical examples)",url:"https://code.claude.com/docs/en/mcp"},{label:"Claude Code — Connect to MCP servers (quickstart)",url:"https://code.claude.com/docs/en/mcp-quickstart"}],pasos:["Listar los hitos y su D# desde usmleStep1Daily.ts (DIAS con palm/hito) y la regla 'hito = viernes de su semana'; escribir la tabla esperada para START=2026-09-07 y comparar con CALENDARIO_5_MESES.md.","gen_hitos_overlays.js: lee el .ts, calcula fechas, emite JSON {hito, fecha, hora, descripcion, accion:'delete+create'}; sin llamadas al Calendar.","Descripción del overlay = protocolo test-day generado desde PALMERTON_POR_MATERIA §F (texto fijo + hora de cada break).","Diff en seco: con el MCP (list_events/search_events 'NBME'|'UWSA') comparar fechas y listar solo cambios; corregir falsos positivos.","Doc + commit + nota synapse-journal. Ejecutar delete/create solo tras confirmación de Joseph (y solo si hubo corrimiento)."],shipTxt:"SHIP S9: JSON de overlays + diff en seco limpio; ejecución real solo con OK de Joseph."},
{s:10,id:"bot-whatsapp-ocr",nombre:"Bot WhatsApp → OCR → ficha LIVIANO (n8n Webhook + visión)",rotacion:"bots",deload:false,ini:"2026-11-09",fin:"2026-11-13",ship:"2026-11-14",sirveA:"LIVIANO / Pulso — el paciente manda foto (análisis, balanza, receta) por WhatsApp y hoy se transcribe a mano al CRM",objetivo:"Webhook de n8n que recibe la imagen de WhatsApp, la pasa por OCR/visión (Claude o Gemini), valida un JSON de ficha y lo guarda en Supabase con respuesta automática al paciente.",entregable:"Workflow n8n exportado (JSON) + tabla de fichas en Supabase + 3 pruebas reales en < 60 s con ≥5 campos correctos.",aceptacion:["Enviar una foto por WhatsApp → fila en Supabase en < 60 s (3/3 pruebas)","≥5 campos correctos por ficha (nombre, fecha, peso/talla o valores de laboratorio, medicación, observación)","Verificación de firma del webhook activa; credenciales solo en n8n (nunca en el repo)","Respuesta automática al paciente con resumen y aviso de revisión médica"],repo:"n8n (instancia propia) · Supabase (tabla nueva liviano_fichas con RLS) · CRM Pulso (solo lectura, copiar nunca borrar)",docs:[{label:"n8n — Build your first workflow (trigger · If · test)",url:"https://docs.n8n.io/build-your-first-workflow/"},{label:"n8n — Webhook node (Webhook URLs · HTTP Method · Respond)",url:"https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.webhook/"},{label:"n8n — AI Agent node",url:"https://docs.n8n.io/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.agent/"},{label:"Supabase — Edge Functions quickstart (alternativa serverless)",url:"https://supabase.com/docs/guides/functions/quickstart"}],pasos:["Diseño: WhatsApp Cloud API → Webhook n8n → descarga de media → visión (prompt de extracción a JSON) → validación → Supabase → respuesta. Credenciales de WhatsApp: A VERIFICAR con Joseph (cuenta Meta Business).","n8n: Webhook node (POST, path propio) + verificación de firma + descarga de la imagen; probar con curl y una imagen local.","OCR/visión: prompt de extracción con esquema JSON fijo (campos de la ficha) + 2 ejemplos; validar con un nodo Code (campos obligatorios, unidades).","Guardar en Supabase (tabla liviano_fichas, RLS) + respuesta automática; 3 pruebas con imágenes reales y medir latencia.","Exportar el workflow (JSON) a DATA/BUSINESS/ + doc + commit + nota synapse-journal."],shipTxt:"SHIP S10: 3/3 pruebas reales en < 60 s con ≥5 campos correctos."},
{s:11,id:"contenido-marcas",nombre:"Pipeline de contenido de marcas (brief → 3 guiones + títulos + thumbnail) con la API de Claude",rotacion:"contenido",deload:false,ini:"2026-11-16",fin:"2026-11-20",ship:"2026-11-21",sirveA:"Marcas (LIVIANO primero; CURVA/DENSA arrancan en febrero) — hoy el contenido se improvisa; la academia LIVIANO produce conocimiento que no se convierte en piezas",objetivo:"Un script que, dado marca + tema, produzca 3 guiones de 45 s (hook-cuerpo-CTA), 5 títulos, marcadores de corte y un prompt de thumbnail; 1 pieza publicada.",entregable:"DATA/_scripts/gen_contenido.js <marca> <tema> → DATA/BUSINESS/CONTENIDO/<marca>/<fecha>/ + 1 pieza publicada con métrica de alcance anotada.",aceptacion:["gen_contenido.js genera 3 guiones + 5 títulos + prompt de thumbnail en < 1 min","1 pieza publicada (LIVIANO) con el guion generado y revisado por Joseph","Alcance a 48 h anotado en el .md de la pieza","Sin claims médicos no verificados: cada afirmación clínica cita fuente (academia LIVIANO)"],repo:"DATA/_scripts/gen_contenido.js (nuevo) · DATA/BUSINESS/CONTENIDO/ (nuevo) · academia LIVIANO (src/lib/livianoStudyPlan.ts como banco de temas)",docs:[{label:"Anthropic Academy — Building with the Claude API (Prompt engineering techniques · Structured data · Prompt evaluation)",url:"https://anthropic.skilljar.com/claude-with-the-anthropic-api"},{label:"Claude Code — Run Claude Code programmatically (claude -p con --json-schema)",url:"https://code.claude.com/docs/en/headless"}],pasos:["Brief por marca (LIVIANO): 3 pilares + tono + 3 temas de la academia; escribir gen_contenido.js que arma el prompt y llama a la API (o claude -p --json-schema) con salida JSON.","Guiones: 3 guiones de 45 s (hook-cuerpo-CTA) + 5 títulos; guardar en DATA/BUSINESS/CONTENIDO/liviano/<fecha>/guiones.md.","Thumbnail: prompt de imagen + 1 imagen generada con la herramienta disponible; marcadores de corte para clips.","Revisión humana (claims clínicos con fuente) + publicar 1 pieza.","Anotar alcance a 48 h + commit + nota synapse-journal."],shipTxt:"SHIP S11: 1 pieza publicada con guion generado + carpeta de la pieza completa."},
{s:12,id:"capstone-readme",nombre:"Capstone: README del sistema YoCPMD + demo 5' + retro de 12 semanas",rotacion:"yocpmd",deload:false,ini:"2026-11-23",fin:"2026-11-27",ship:"2026-11-28",sirveA:"Joseph futuro y cualquier agente nuevo — hoy el conocimiento del sistema vive en la memoria de Claude y en 40 scripts sin mapa",objetivo:"Un README que permita a un agente/persona nueva operar el sistema (scripts, hooks, skills, pipeline de corrimiento, revisión semanal) + demo grabada + retro honesta de los 12 entregables.",entregable:"README_SISTEMA.md en DATA/ + demo de 5' + retro con estado de los 12 proyectos + decisión CCA-F.",aceptacion:["README con mapa de DATA/_scripts (qué genera cada uno y en qué orden), hooks, skills y los 3 rituales (diario, viernes, sábado)","Demo de 5' grabada recorriendo Home → Estudio → revisión semanal","Retro: 12 proyectos con estado (shipped / parcial / no) y 1 lección por proyecto","Decisión escrita: examen CCA-F (fecha) o no, y plan de la fase siguiente (F2 del motor SYNAPSE)"],repo:"DATA/README_SISTEMA.md (nuevo) · DATA/SYNAPSE/VIBECODING_12_PROYECTOS.md (retro) · synapse-journal",docs:[{label:"Anthropic Academy — Claude Code in Action (Verify and Share · Plugins)",url:"https://anthropic.skilljar.com/claude-code-in-action"},{label:"Claude Code — Create plugins (empaquetar skills/hooks propios)",url:"https://code.claude.com/docs/en/plugins"},{label:"Anthropic Academy — catálogo (22 cursos, prep CCA-F)",url:"https://anthropic.skilljar.com/"}],pasos:["README_SISTEMA.md: inventario de DATA/_scripts (generadores, remap, telemetría, revisión), hooks y skills; orden del pipeline de corrimiento.","Demo 5': grabar (OBS/Loom) Home → Estudio → revisión semanal; subir y enlazar.","Retro: tabla de los 12 proyectos con estado + 1 lección cada uno; qué se automatiza en F2.","Decisión CCA-F: revisar dominios (Agentic Architecture 27% · Claude Code 20% · Tool Design & MCP 18% · Prompt Engineering 20% · Context Management 15%) contra lo hecho; fijar fecha o no.","Commit final + tag vibecoding-s12 + nota synapse-journal (cierre)."],shipTxt:"SHIP S12: README + demo + retro + decisión CCA-F publicados."}
];

export const VIBE_DIAS: DiaVibe[] = [
{d:1,fecha:"2026-09-07",wd:"Lun",semana:1,proyecto:"apex-parser",k:1,tipo:"definir",min:45,deload:false,paso:"Reproducir el bug: pegar un APEX con REVERSO de 3 líneas por node scripts/node_parsear_tarjeta_v2_3.js y ver el truncado. Escribir scripts/test_parser_multilinea.js con 3 fixtures que HOY fallan (rojo). Objetivo del día: test rojo reproducible."},
{d:2,fecha:"2026-09-08",wd:"Mar",semana:1,proyecto:"apex-parser",k:2,tipo:"construir",min:45,deload:false,paso:"P0-2: cambiar el lookahead en node_parsear_tarjeta_v2_3.js:27 y n8n_parser_v2_3.js:56 a (?=\\n[A-Z_]+:|\\n═|(?![\\s\\S])) (sin '$' bajo flag m). Correr el test → verde."},
{d:3,fecha:"2026-09-09",wd:"Mié",semana:1,proyecto:"apex-parser",k:3,tipo:"construir",min:45,deload:false,paso:"P0-3: node_crear_nota_v2_3.js renderiza caso_clinico y fisio_expandida en la nota Obsidian (sección condicional si viene vacía). Test de la nota con fixture."},
{d:4,fecha:"2026-09-10",wd:"Jue",semana:1,proyecto:"apex-parser",k:4,tipo:"verificar",min:45,deload:false,paso:"Verificar en vivo: pegar n8n_parser_v2_3.js en el nodo Code de n8n (redeploy), enviar 1 APEX de prueba (Ctrl+Shift+A, is_test) → abrir Anki y el vault y comprobar que llega íntegro."},
{d:5,fecha:"2026-09-11",wd:"Vie",semana:1,proyecto:"apex-parser",k:5,tipo:"ship-prep",min:45,deload:false,paso:"Commit en agente_estudio + cerrar P0-2/P0-3 en DATA/ENCAPS/AUDITORIA_AGENTE_ESTUDIO_2026-07-02.md (fecha) + nota synapse-journal. Preparar el SHIP del sábado: lista de lo que falta (T1/T2/T3 Palmerton = P1-6, queda para otra semana)."},
{d:6,fecha:"2026-09-14",wd:"Lun",semana:2,proyecto:"anki-telemetria",k:1,tipo:"definir",min:45,deload:false,paso:"Correr node DATA/_scripts/anki_telemetria.js con Anki abierto. Comparar due/backlog/revisadas con la pantalla Stats de Anki y anotar discrepancias (deck pattern APEX::USMLE* vs AnKing)."},
{d:7,fecha:"2026-09-15",wd:"Mar",semana:2,proyecto:"anki-telemetria",k:2,tipo:"construir",min:45,deload:false,paso:"Retención real: usar cardReviews de los últimos 30 días (reviewType=1) y calcular 1 − Again/total; validar que getDeckConfig devuelve 10 nuevas/día y desired retention 0.9 (si no, corregir en Anki, no en el script)."},
{d:8,fecha:"2026-09-16",wd:"Mié",semana:2,proyecto:"anki-telemetria",k:3,tipo:"construir",min:45,deload:false,paso:"Automatizar: tarea programada de Windows (schtasks /create … 21:05 L-D) o hook SessionEnd de Claude Code que ejecute el script; comprobar que escribe sin ventana abierta."},
{d:9,fecha:"2026-09-17",wd:"Jue",semana:2,proyecto:"anki-telemetria",k:4,tipo:"verificar",min:45,deload:false,paso:"KPI en Home: pegar el one-liner localStorage que imprime el script y verificar en vivo que CockpitStatusBar lo muestra; opcional: servir el JSON desde public/ para no pegar a mano."},
{d:10,fecha:"2026-09-18",wd:"Vie",semana:2,proyecto:"anki-telemetria",k:5,tipo:"ship-prep",min:45,deload:false,paso:"Regla 'Anki finde = due × 20 s' en DATA/SYNC_ANKI_OBSIDIAN_APP.md (ya escrita) + commit + nota synapse-journal."},
{d:11,fecha:"2026-09-21",wd:"Lun",semana:3,proyecto:"usmle-scores",k:1,tipo:"definir",min:45,deload:false,paso:"Definir el esquema: tabla usmle_daily_scores(fecha date pk, pretest_10 int, q30_pct numeric, eval_pct numeric, error_dominante text, ccsn int, nota text) con RLS; escribir la migración en supabase-schema.sql (NO aplicar aún). Alternativa: study_sim_scores con examen='USMLE'."},
{d:12,fecha:"2026-09-22",wd:"Mar",semana:3,proyecto:"usmle-scores",k:2,tipo:"construir",min:45,deload:false,paso:"UI: en UsmleTodayPlan añadir 3 inputs numéricos + selector knowledge/transfer/proceso + contador CCSN; guardar en localStorage 'jmd-usmle-scores' (try/catch) al instante."},
{d:13,fecha:"2026-09-23",wd:"Mié",semana:3,proyecto:"usmle-scores",k:3,tipo:"construir",min:45,deload:false,paso:"Espejo: upsert en Supabase (anon + RLS por usuario) con reintento; lectura de los últimos 7 días para ReadinessBar (media móvil + distancia al mínimo on-track de la tabla Parte V)."},
{d:14,fecha:"2026-09-24",wd:"Jue",semana:3,proyecto:"usmle-scores",k:4,tipo:"verificar",min:45,deload:false,paso:"Verificar en vivo (web): registrar los 3 valores de hoy, recargar, comprobar persistencia y la fila en Supabase (MCP execute_sql SELECT)."},
{d:15,fecha:"2026-09-25",wd:"Vie",semana:3,proyecto:"usmle-scores",k:5,tipo:"ship-prep",min:45,deload:false,paso:"Conectar gen_revision_semanal.js (fuente usmle_daily_scores) + commit + nota synapse-journal."},
{d:16,fecha:"2026-09-28",wd:"Lun",semana:4,proyecto:"revision-semanal",k:1,tipo:"definir",min:45,deload:false,paso:"Correr node DATA/_scripts/gen_revision_semanal.js y listar cada métrica que sale 'sin dato'; elegir las 3 más baratas de conectar."},
{d:17,fecha:"2026-09-29",wd:"Mar",semana:4,proyecto:"revision-semanal",k:2,tipo:"construir",min:45,deload:false,paso:"Conectar fuentes: scores USMLE (S3), telemetría Anki (S2), % ciego ENCAPS del viernes desde TRACKING_ERRORES/_registro_resoluciones.json (rondas de la semana)."},
{d:18,fecha:"2026-09-30",wd:"Mié",semana:4,proyecto:"revision-semanal",k:3,tipo:"construir",min:45,deload:false,paso:"Export de localStorage sin fricción: skill /export-ls (imprime el snippet de consola) o botón en la app que descarga jmd-*.json a DATA/USMLE/REVISIONES/_localstorage_export.json."},
{d:19,fecha:"2026-10-01",wd:"Jue",semana:4,proyecto:"revision-semanal",k:4,tipo:"verificar",min:45,deload:false,paso:"Generar la revisión de esta semana en seco, leerla completa, corregir la plantilla (DATA/REVISION_SEMANAL.md) donde no ayude a decidir."},
{d:20,fecha:"2026-10-02",wd:"Vie",semana:4,proyecto:"revision-semanal",k:5,tipo:"ship-prep",min:45,deload:false,paso:"Automatizar: viernes 21:00 el script pre-genera (schtasks o /schedule); sábado 07:15 Joseph rellena 20'. Commit + nota synapse-journal."},
{d:21,fecha:"2026-10-05",wd:"Lun",semana:5,proyecto:"remap-verificado",k:1,tipo:"definir",min:45,deload:false,paso:"Escribir remap_todo.js: encadena los 5 generadores con child_process, acepta --dry-run (trabaja sobre una copia temporal de src/lib) y resume fechas inicio→fin por plan."},
{d:22,fecha:"2026-10-06",wd:"Mar",semana:5,proyecto:"remap-verificado",k:2,tipo:"construir",min:45,deload:false,paso:"verificar_planes.js: lee cada src/lib/*DailyPlan.ts y usmleStep1Daily.ts (regex fecha:\"20\\d\\d-\\d\\d-\\d\\d\"), falla si hay sáb/dom, 25-dic/31-dic/1-ene, duplicados o fechas no crecientes; imprime nº de días vs esperado (USMLE 97 · MIR 78 · LIVIANO 90 · SYNAPSE 82 · VIBE 60)."},
{d:23,fecha:"2026-10-07",wd:"Mié",semana:5,proyecto:"remap-verificado",k:3,tipo:"construir",min:45,deload:false,paso:"Skill /remap <fecha> (.claude/skills/remap/SKILL.md, disable-model-invocation: true): ejecuta el dry-run, muestra el diff y pide confirmación; hook PostToolUse opcional que corre verificar_planes.js al editar src/lib/*Plan.ts."},
{d:24,fecha:"2026-10-08",wd:"Jue",semana:5,proyecto:"remap-verificado",k:4,tipo:"verificar",min:45,deload:false,paso:"Prueba negativa: inyectar un sábado en una copia y ver que verificar_planes.js falla; prueba positiva con la fecha real."},
{d:25,fecha:"2026-10-09",wd:"Vie",semana:5,proyecto:"remap-verificado",k:5,tipo:"ship-prep",min:45,deload:false,paso:"Doc breve en DATA/_scripts (cabecera del script) + memoria de Claude (regla: usar remap_todo.js) + commit + nota synapse-journal."},
{d:26,fecha:"2026-10-12",wd:"Lun",semana:6,proyecto:"rls-datos-tesis",k:1,tipo:"definir",min:45,deload:false,paso:"Inventario: quién lee/escribe datos_tesis y kappa_piloto (grep en agente_estudio + SECURITY_AUDIT_PHASE_A_C.sql ya existente); decidir política: solo service_role (pipeline) + rol médico."},
{d:27,fecha:"2026-10-13",wd:"Mar",semana:6,proyecto:"rls-datos-tesis",k:2,tipo:"construir",min:45,deload:false,paso:"Escribir la migración: alter table … enable row level security + policies; probar en una rama de Supabase (create_branch) o con --dry-run en local."},
{d:28,fecha:"2026-10-14",wd:"Mié",semana:6,proyecto:"rls-datos-tesis",k:3,tipo:"construir",min:45,deload:false,paso:"Mover el acceso del pipeline a SUPABASE_SERVICE_ROLE_KEY en .env (gitignored); comprobar que el pipeline sigue insertando."},
{d:29,fecha:"2026-10-15",wd:"Jue",semana:6,proyecto:"rls-datos-tesis",k:4,tipo:"verificar",min:45,deload:false,paso:"scripts/test_rls_anon.js: con la anon key, SELECT → espera 0 filas/401; correr get_advisors y adjuntar salida."},
{d:30,fecha:"2026-10-16",wd:"Vie",semana:6,proyecto:"rls-datos-tesis",k:5,tipo:"ship-prep",min:45,deload:false,paso:"Aplicar con Joseph (apply_migration, backup previo) + SECURITY_AUDIT.md + commit + nota synapse-journal."},
{d:31,fecha:"2026-10-19",wd:"Lun",semana:7,proyecto:"vitals-puente",k:1,tipo:"definir",min:45,deload:false,paso:"Consultar mv_wellness_logs (tipo sueno/agua) con la anon key: si RLS bloquea, definir la policy de lectura para el usuario médico (is_medico) o usar el JSON de la revisión como puente."},
{d:32,fecha:"2026-10-20",wd:"Mar",semana:7,proyecto:"vitals-puente",k:2,tipo:"construir",min:45,deload:false,paso:"gen_revision_semanal.js: tabla sueño×eval por fecha (join con usmle_daily_scores de S3) + contador de noches <7h y <6h."},
{d:33,fecha:"2026-10-21",wd:"Mié",semana:7,proyecto:"vitals-puente",k:3,tipo:"construir",min:45,deload:false,paso:"CockpitStatusBar: 'Sueño anoche: X h' (lectura del último log o del JSON) con try/catch y '—' si no hay dato."},
{d:34,fecha:"2026-10-22",wd:"Jue",semana:7,proyecto:"vitals-puente",k:4,tipo:"verificar",min:45,deload:false,paso:"TodayMission: si el sueño de anoche <6h → chip 'sugerido: ÁMBAR' junto al selector de modo (PROTOCOLO_MODO_MINIMO); Joseph decide."},
{d:35,fecha:"2026-10-23",wd:"Vie",semana:7,proyecto:"vitals-puente",k:5,tipo:"ship-prep",min:45,deload:false,paso:"Doc: fuente de datos en PROTOCOLO_MODO_MINIMO.md (sección Fuentes) + commit + nota synapse-journal."},
{d:36,fecha:"2026-10-26",wd:"Lun",semana:8,proyecto:"motor-preguntas-encaps",k:1,tipo:"definir",min:45,deload:true,paso:"(45') Escribir SKILL.md: lee PRONOSTICO v3 + rotación del día + PERFIL_CONOCIMIENTO → genera 5 viñetas ciegas, formato pregunta→solución interactiva, sin clave hasta que Joseph responda."},
{d:37,fecha:"2026-10-27",wd:"Mar",semana:8,proyecto:"motor-preguntas-encaps",k:2,tipo:"construir",min:15,deload:true,paso:"(15' deload) Revisar el formato de salida con 1 viñeta; nada más."},
{d:38,fecha:"2026-10-28",wd:"Mié",semana:8,proyecto:"motor-preguntas-encaps",k:3,tipo:"construir",min:45,deload:true,paso:"(45') Registro: la skill apenda la ronda a _registro_resoluciones.json (esquema README) y vuelca RONDAS/<codigo>_<fecha>.json."},
{d:39,fecha:"2026-10-29",wd:"Jue",semana:8,proyecto:"motor-preguntas-encaps",k:4,tipo:"verificar",min:15,deload:true,paso:"(15' deload) Descanso activo: leer 1 ronda anterior y anotar 1 mejora."},
{d:40,fecha:"2026-10-30",wd:"Vie",semana:8,proyecto:"motor-preguntas-encaps",k:5,tipo:"ship-prep",min:15,deload:true,paso:"(15') 1 ronda real de 5Q en la hora ENCAPS (16:15) registrada + commit + nota synapse-journal."},
{d:41,fecha:"2026-11-02",wd:"Lun",semana:9,proyecto:"overlays-hitos",k:1,tipo:"definir",min:45,deload:false,paso:"Listar los hitos y su D# desde usmleStep1Daily.ts (DIAS con palm/hito) y la regla 'hito = viernes de su semana'; escribir la tabla esperada para START=2026-09-07 y comparar con CALENDARIO_5_MESES.md."},
{d:42,fecha:"2026-11-03",wd:"Mar",semana:9,proyecto:"overlays-hitos",k:2,tipo:"construir",min:45,deload:false,paso:"gen_hitos_overlays.js: lee el .ts, calcula fechas, emite JSON {hito, fecha, hora, descripcion, accion:'delete+create'}; sin llamadas al Calendar."},
{d:43,fecha:"2026-11-04",wd:"Mié",semana:9,proyecto:"overlays-hitos",k:3,tipo:"construir",min:45,deload:false,paso:"Descripción del overlay = protocolo test-day generado desde PALMERTON_POR_MATERIA §F (texto fijo + hora de cada break)."},
{d:44,fecha:"2026-11-05",wd:"Jue",semana:9,proyecto:"overlays-hitos",k:4,tipo:"verificar",min:45,deload:false,paso:"Diff en seco: con el MCP (list_events/search_events 'NBME'|'UWSA') comparar fechas y listar solo cambios; corregir falsos positivos."},
{d:45,fecha:"2026-11-06",wd:"Vie",semana:9,proyecto:"overlays-hitos",k:5,tipo:"ship-prep",min:45,deload:false,paso:"Doc + commit + nota synapse-journal. Ejecutar delete/create solo tras confirmación de Joseph (y solo si hubo corrimiento)."},
{d:46,fecha:"2026-11-09",wd:"Lun",semana:10,proyecto:"bot-whatsapp-ocr",k:1,tipo:"definir",min:45,deload:false,paso:"Diseño: WhatsApp Cloud API → Webhook n8n → descarga de media → visión (prompt de extracción a JSON) → validación → Supabase → respuesta. Credenciales de WhatsApp: A VERIFICAR con Joseph (cuenta Meta Business)."},
{d:47,fecha:"2026-11-10",wd:"Mar",semana:10,proyecto:"bot-whatsapp-ocr",k:2,tipo:"construir",min:45,deload:false,paso:"n8n: Webhook node (POST, path propio) + verificación de firma + descarga de la imagen; probar con curl y una imagen local."},
{d:48,fecha:"2026-11-11",wd:"Mié",semana:10,proyecto:"bot-whatsapp-ocr",k:3,tipo:"construir",min:45,deload:false,paso:"OCR/visión: prompt de extracción con esquema JSON fijo (campos de la ficha) + 2 ejemplos; validar con un nodo Code (campos obligatorios, unidades)."},
{d:49,fecha:"2026-11-12",wd:"Jue",semana:10,proyecto:"bot-whatsapp-ocr",k:4,tipo:"verificar",min:45,deload:false,paso:"Guardar en Supabase (tabla liviano_fichas, RLS) + respuesta automática; 3 pruebas con imágenes reales y medir latencia."},
{d:50,fecha:"2026-11-13",wd:"Vie",semana:10,proyecto:"bot-whatsapp-ocr",k:5,tipo:"ship-prep",min:45,deload:false,paso:"Exportar el workflow (JSON) a DATA/BUSINESS/ + doc + commit + nota synapse-journal."},
{d:51,fecha:"2026-11-16",wd:"Lun",semana:11,proyecto:"contenido-marcas",k:1,tipo:"definir",min:45,deload:false,paso:"Brief por marca (LIVIANO): 3 pilares + tono + 3 temas de la academia; escribir gen_contenido.js que arma el prompt y llama a la API (o claude -p --json-schema) con salida JSON."},
{d:52,fecha:"2026-11-17",wd:"Mar",semana:11,proyecto:"contenido-marcas",k:2,tipo:"construir",min:45,deload:false,paso:"Guiones: 3 guiones de 45 s (hook-cuerpo-CTA) + 5 títulos; guardar en DATA/BUSINESS/CONTENIDO/liviano/<fecha>/guiones.md."},
{d:53,fecha:"2026-11-18",wd:"Mié",semana:11,proyecto:"contenido-marcas",k:3,tipo:"construir",min:45,deload:false,paso:"Thumbnail: prompt de imagen + 1 imagen generada con la herramienta disponible; marcadores de corte para clips."},
{d:54,fecha:"2026-11-19",wd:"Jue",semana:11,proyecto:"contenido-marcas",k:4,tipo:"verificar",min:45,deload:false,paso:"Revisión humana (claims clínicos con fuente) + publicar 1 pieza."},
{d:55,fecha:"2026-11-20",wd:"Vie",semana:11,proyecto:"contenido-marcas",k:5,tipo:"ship-prep",min:45,deload:false,paso:"Anotar alcance a 48 h + commit + nota synapse-journal."},
{d:56,fecha:"2026-11-23",wd:"Lun",semana:12,proyecto:"capstone-readme",k:1,tipo:"definir",min:45,deload:false,paso:"README_SISTEMA.md: inventario de DATA/_scripts (generadores, remap, telemetría, revisión), hooks y skills; orden del pipeline de corrimiento."},
{d:57,fecha:"2026-11-24",wd:"Mar",semana:12,proyecto:"capstone-readme",k:2,tipo:"construir",min:45,deload:false,paso:"Demo 5': grabar (OBS/Loom) Home → Estudio → revisión semanal; subir y enlazar."},
{d:58,fecha:"2026-11-25",wd:"Mié",semana:12,proyecto:"capstone-readme",k:3,tipo:"construir",min:45,deload:false,paso:"Retro: tabla de los 12 proyectos con estado + 1 lección cada uno; qué se automatiza en F2."},
{d:59,fecha:"2026-11-26",wd:"Jue",semana:12,proyecto:"capstone-readme",k:4,tipo:"verificar",min:45,deload:false,paso:"Decisión CCA-F: revisar dominios (Agentic Architecture 27% · Claude Code 20% · Tool Design & MCP 18% · Prompt Engineering 20% · Context Management 15%) contra lo hecho; fijar fecha o no."},
{d:60,fecha:"2026-11-27",wd:"Vie",semana:12,proyecto:"capstone-readme",k:5,tipo:"ship-prep",min:45,deload:false,paso:"Commit final + tag vibecoding-s12 + nota synapse-journal (cierre)."}
];

export const VIBE_TIPO_LABEL: Record<VibeTipo, string> = {"definir":"5' objetivo → spec del día","construir":"construir con Claude Code","verificar":"verificar en vivo (test/URL/dato)","ship-prep":"doc + commit + preparar SHIP"};
export const VIBE_ROTACION_ICON: Record<VibeRotacion, string> = { yocpmd: '⚙️', preguntas: '❓', bots: '🤖', contenido: '🎬' };

export function vibeDiaDe(fechaISO: string): DiaVibe | undefined { return VIBE_DIAS.find((x) => x.fecha === fechaISO); }
export function vibeProyectoDe(s: number): VibeProyecto | undefined { return VIBE_PROYECTOS.find((x) => x.s === s); }
/** Proyecto vigente para una fecha: el de su semana L-V, o (sáb/dom) el de la semana que acaba de cerrar. */
export function vibeProyectoEnFecha(fechaISO: string): VibeProyecto | undefined {
  const dia = vibeDiaDe(fechaISO);
  if (dia) return vibeProyectoDe(dia.semana);
  const prev = [...VIBE_DIAS].reverse().find((x) => x.fecha < fechaISO);
  if (prev) return vibeProyectoDe(prev.semana);
  return VIBE_PROYECTOS[0];
}
/** Nº de proyectos SHIPPED = semanas con sus 5 días marcados ✓ (PlanKey 'vibecoding'). */
export function vibeShipped(done: Set<number>): number {
  return VIBE_PROYECTOS.filter((p) => VIBE_DIAS.filter((x) => x.semana === p.s).every((x) => done.has(x.d))).length;
}
