-- ============================================================
-- 0002 · Seed de CATÁLOGO (alimentos peruanos + RAG). Generado por generate_seed.py.
-- NO contiene datos de usuarios (esos vienen de auth.users tras el signup).
-- ============================================================

-- Alimentos peruanos (base tipo Fitia, reuso del CRM).
insert into foods (nombre,categoria,kcal,proteina_g,carbo_g,grasa_g,porcion_g,porcion_nombre,es_peruano) values
  ('Pechuga de pollo','proteina',165,31,0,3.6,100,'100 g',true),
  ('Pescado jurel','proteina',140,23,0,5,100,'100 g',true),
  ('Huevo de gallina','proteina',143,13,1,10,50,'1 unidad',true),
  ('Lomo de res magro','proteina',180,27,0,8,100,'100 g',true),
  ('Arroz blanco cocido','cereal',130,2.7,28,0.3,150,'1 taza',true),
  ('Quinua cocida','cereal',120,4.4,21,1.9,100,'100 g',true),
  ('Papa blanca sancochada','tuberculo',87,2,20,0.1,150,'1 unidad',true),
  ('Camote','tuberculo',86,1.6,20,0.1,130,'1 unidad',true),
  ('Lenteja guisada','legumbre',116,9,20,0.4,100,'1 cucharón',true),
  ('Palta (aguacate)','grasa',160,2,9,15,100,'1/2 unidad',true),
  ('Lechuga','verdura',15,1.4,2.9,0.2,50,'1 plato',true),
  ('Zanahoria','verdura',41,0.9,10,0.2,60,'1 unidad',true),
  ('Brócoli','verdura',34,2.8,7,0.4,80,'1 porción',true),
  ('Plátano','fruta',89,1.1,23,0.3,120,'1 unidad',true),
  ('Manzana','fruta',52,0.3,14,0.2,150,'1 unidad',true),
  ('Avena','cereal',389,17,66,7,40,'1/2 taza',true),
  ('Leche evaporada','lacteo',134,7,10,7.6,100,'100 ml',true),
  ('Yogurt natural','lacteo',61,3.5,5,3.3,150,'1 vaso',true),
  ('Pan integral','cereal',247,13,41,3.4,30,'1 rebanada',true),
  ('Atún en agua','proteina',116,26,0,1,100,'1 lata',true),
  ('Choclo (maíz)','cereal',96,3.4,21,1.5,100,'1/2 unidad',true),
  ('Frejol canario','legumbre',127,9,23,0.5,100,'1 cucharón',true),
  ('Aceite de oliva','grasa',884,0,0,100,10,'1 cucharada',false),
  ('Queso fresco','lacteo',264,17,3,21,40,'1 tajada',true),
  ('Pollo broaster','preparado',290,22,14,17,150,'1 presa',true),
  ('Papas fritas','preparado',312,3.4,41,15,100,'1 porción',true)
on conflict do nothing;

-- Base de conocimiento (RAG) + chunks. Embeddings se rellenan con backfill.
do $$
declare kid uuid;
begin
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Cuánta proteína para ganar/preservar músculo','Para maximizar la masa muscular con entrenamiento de fuerza, la evidencia apunta a ~1.6 g de proteína por kg de peso al día, con beneficio posible hasta ~2.2 g/kg. Reparte en 3-4 comidas de 30-40 g (aprox. 0.4 g/kg por toma). En déficit calórico o bajo GLP-1, sube el piso a 1.8-2.2 g/kg para proteger el músculo.','nutricion','Morton, Murphy & Phillips (Br J Sports Med 2018)','["proteina", "musculo", "macros"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Cuánta proteína para ganar/preservar músculo. Para maximizar la masa muscular con entrenamiento de fuerza, la evidencia apunta a ~1.6 g de proteína por kg de peso al día, con beneficio posible hasta ~2.2 g/kg. Reparte en 3-4 comidas de 30-40 g (aprox. 0.4 g/kg por toma). En déficit calórico o bajo GLP-1, sube el piso a 1.8-2.2 g/kg para proteger el músculo.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','La ventana anabólica no es tan estrecha','No arruinas tus resultados por comer la proteína una o dos horas después de entrenar. Lo que más pesa es el total diario de proteína y de calorías, y sobre todo la constancia. No te castigues por el reloj: cuida el total y la adherencia.','nutricion','Aragon & Schoenfeld (JISSN 2013)','["timing", "mitos", "proteina"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'La ventana anabólica no es tan estrecha. No arruinas tus resultados por comer la proteína una o dos horas después de entrenar. Lo que más pesa es el total diario de proteína y de calorías, y sobre todo la constancia. No te castigues por el reloj: cuida el total y la adherencia.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','La adherencia es lo que más predice el resultado','El mejor plan es el que puedes sostener. La jerarquía es: primero adherencia, luego volumen/intensidad de entrenamiento, luego frecuencia, después el timing y al final los suplementos. Si algo del plan no es sostenible para ti, se ajusta; no se abandona todo.','adherencia','Layne Norton; Eric Helms (pirámide de prioridades)','["adherencia", "habito", "psicologia"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'La adherencia es lo que más predice el resultado. El mejor plan es el que puedes sostener. La jerarquía es: primero adherencia, luego volumen/intensidad de entrenamiento, luego frecuencia, después el timing y al final los suplementos. Si algo del plan no es sostenible para ti, se ajusta; no se abandona todo.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Principio 80/20: hacer una parte ya rinde','Hacer todo el plan da el 100% del beneficio, pero hacer una buena fracción del plan rinde cerca del 80% del beneficio. No existe el ''ya lo arruiné, mejor dejo todo''. Un día imperfecto sigue sumando. La constancia imperfecta gana al perfeccionismo que abandona.','adherencia','Filosofía Pulso (anti-todo-o-nada)','["adherencia", "motivacion", "80-20"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Principio 80/20: hacer una parte ya rinde. Hacer todo el plan da el 100% del beneficio, pero hacer una buena fracción del plan rinde cerca del 80% del beneficio. No existe el ''ya lo arruiné, mejor dejo todo''. Un día imperfecto sigue sumando. La constancia imperfecta gana al perfeccionismo que abandona.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Volumen de entrenamiento para hipertrofia','Para crecer músculo conviene acumular al menos 10 series por grupo muscular a la semana, y muchas personas progresan con 12-20 series repartidas en 2 o más sesiones. Lleva las series cerca del esfuerzo (RIR 1-3). La hipertrofia ocurre en un amplio rango de repeticiones si hay esfuerzo.','ejercicio','Schoenfeld, Ogborn & Krieger (J Sports Sci 2017)','["volumen", "hipertrofia", "series"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Volumen de entrenamiento para hipertrofia. Para crecer músculo conviene acumular al menos 10 series por grupo muscular a la semana, y muchas personas progresan con 12-20 series repartidas en 2 o más sesiones. Lleva las series cerca del esfuerzo (RIR 1-3). La hipertrofia ocurre en un amplio rango de repeticiones si hay esfuerzo.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','RIR: cómo regular el esfuerzo','RIR (reps en reserva) es cuántas repeticiones más podrías hacer al terminar la serie. Para hipertrofia, trabaja con RIR 1-3 (parar 1 a 3 reps antes del fallo). Cuando un peso te deja con más reps de reserva de las planeadas, súbelo o suma repeticiones: eso es sobrecarga progresiva.','ejercicio','Eric Helms (Muscle & Strength Pyramids)','["rir", "intensidad", "tecnica"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'RIR: cómo regular el esfuerzo. RIR (reps en reserva) es cuántas repeticiones más podrías hacer al terminar la serie. Para hipertrofia, trabaja con RIR 1-3 (parar 1 a 3 reps antes del fallo). Cuando un peso te deja con más reps de reserva de las planeadas, súbelo o suma repeticiones: eso es sobrecarga progresiva.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Landmarks de volumen MEV/MAV/MRV y deload','MEV es el volumen mínimo para crecer, MAV el rango donde más adaptas y MRV el máximo que puedes recuperar. Sube el volumen semana a semana desde MEV hacia MAV; cuando el rendimiento cae o te estancas, programa una semana de descarga (deload) y vuelve a subir.','ejercicio','Mike Israetel (Renaissance Periodization)','["periodizacion", "volumen", "deload"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Landmarks de volumen MEV/MAV/MRV y deload. MEV es el volumen mínimo para crecer, MAV el rango donde más adaptas y MRV el máximo que puedes recuperar. Sube el volumen semana a semana desde MEV hacia MAV; cuando el rendimiento cae o te estancas, programa una semana de descarga (deload) y vuelve a subir.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Entrenamiento minimalista: 30 minutos sirven','No necesitas sesiones largas para mantener o ganar músculo. Pocas series bien ejecutadas, cerca del fallo (RIR 0-2), en 30 minutos, son efectivas si eres constante. Para días cortos: prioriza ejercicios multiarticulares y deja el aislamiento si falta tiempo.','ejercicio','Dr. Pak (entrenamiento minimalista)','["tiempo", "minimalista", "30min"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Entrenamiento minimalista: 30 minutos sirven. No necesitas sesiones largas para mantener o ganar músculo. Pocas series bien ejecutadas, cerca del fallo (RIR 0-2), en 30 minutos, son efectivas si eres constante. Para días cortos: prioriza ejercicios multiarticulares y deja el aislamiento si falta tiempo.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Rango de movimiento completo','Entrenar en rango completo, especialmente con el músculo estirado bajo carga, tiende a dar más crecimiento que rangos parciales cortos. Baja con control hasta el estiramiento y controla la fase excéntrica. Las parciales en posición estirada son una herramienta útil al final de la serie.','ejercicio','Milo Wolf, PhD (ROM)','["tecnica", "rom", "estiramiento"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Rango de movimiento completo. Entrenar en rango completo, especialmente con el músculo estirado bajo carga, tiende a dar más crecimiento que rangos parciales cortos. Baja con control hasta el estiramiento y controla la fase excéntrica. Las parciales en posición estirada son una herramienta útil al final de la serie.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Recomposición: ganar músculo y perder grasa a la vez','La recomposición (perder grasa y ganar músculo a la vez) es realista en quienes recién empiezan, vienen de un parón, o tienen grasa que perder. La receta: proteína alta (1.6-2.2 g/kg), entrenamiento de fuerza progresivo y un déficit calórico pequeño o mantenimiento. Paciencia: la balanza se mueve poco aunque cambies por dentro.','ejercicio','Menno Henselmans','["recomposicion", "grasa", "musculo"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Recomposición: ganar músculo y perder grasa a la vez. La recomposición (perder grasa y ganar músculo a la vez) es realista en quienes recién empiezan, vienen de un parón, o tienen grasa que perder. La receta: proteína alta (1.6-2.2 g/kg), entrenamiento de fuerza progresivo y un déficit calórico pequeño o mantenimiento. Paciencia: la balanza se mueve poco aunque cambies por dentro.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','TDEE adaptativo: el plan se ajusta a tu metabolismo real','En vez de confiar en una fórmula fija, tu gasto energético real se estima de tus datos: cuánto comes y cómo cambia tu peso (tendencia suavizada). Si bajas más lento de lo previsto, el plan recorta un poco las calorías; si bajas muy rápido, las sube. Así el objetivo se reestructura solo, sin culpa.','nutricion','MacroFactor (algoritmo adaptativo)','["calorias", "tdee", "adaptativo"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'TDEE adaptativo: el plan se ajusta a tu metabolismo real. En vez de confiar en una fórmula fija, tu gasto energético real se estima de tus datos: cuánto comes y cómo cambia tu peso (tendencia suavizada). Si bajas más lento de lo previsto, el plan recorta un poco las calorías; si bajas muy rápido, las sube. Así el objetivo se reestructura solo, sin culpa.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Velocidad segura de pérdida de peso','Una pérdida sostenible es de 0.5 a 0.75% de tu peso por semana (hasta 1% en personas con más grasa). Perder más rápido de forma sostenida aumenta el riesgo de perder músculo, fatiga y rebote. Si tu tendencia supera 1%/semana de forma constante, hay que revisar el plan con el médico.','nutricion','Helms; Aragon (práctica basada en evidencia)','["deficit", "velocidad", "seguridad"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Velocidad segura de pérdida de peso. Una pérdida sostenible es de 0.5 a 0.75% de tu peso por semana (hasta 1% en personas con más grasa). Perder más rápido de forma sostenida aumenta el riesgo de perder músculo, fatiga y rebote. Si tu tendencia supera 1%/semana de forma constante, hay que revisar el plan con el médico.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Comer real, no demasiado, sobre todo plantas','Prioriza comida de verdad: proteínas (pollo, pescado, huevo), tubérculos (papa, camote), cereales (arroz, quinua), verduras y frutas. Reduce ultraprocesados y azúcares añadidos. No se trata de prohibir, sino de que la base de tu plato sea comida real andina.','nutricion','Michael Pollan (In Defense of Food)','["comida-real", "ultraprocesados", "filosofia"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Comer real, no demasiado, sobre todo plantas. Prioriza comida de verdad: proteínas (pollo, pescado, huevo), tubérculos (papa, camote), cereales (arroz, quinua), verduras y frutas. Reduce ultraprocesados y azúcares añadidos. No se trata de prohibir, sino de que la base de tu plato sea comida real andina.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Ventana de alimentación (TRE) suave','Concentrar tus comidas en una ventana de 10 a 12 horas (por ejemplo de 8am a 7pm) puede ayudar a tu metabolismo sin pasar hambre extrema. No es un ayuno agresivo: es ordenar los horarios. Evita comer muy tarde en la noche. Nada de ayunos prolongados sin indicación médica.','nutricion','Satchin Panda (The Circadian Code)','["ayuno", "ventana", "circadiano"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Ventana de alimentación (TRE) suave. Concentrar tus comidas en una ventana de 10 a 12 horas (por ejemplo de 8am a 7pm) puede ayudar a tu metabolismo sin pasar hambre extrema. No es un ayuno agresivo: es ordenar los horarios. Evita comer muy tarde en la noche. Nada de ayunos prolongados sin indicación médica.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Longevidad: músculo, fuerza y cardio zona 2','Para vivir mejor más años, protege tu masa muscular y tu capacidad aeróbica. Combina entrenamiento de fuerza con cardio de zona 2 (ritmo en el que aún puedes conversar) varias horas por semana, más algo de alta intensidad. La proteína y la fuerza son medicina para la vejez.','ejercicio','Peter Attia (Outlive)','["longevidad", "zona2", "cardio", "fuerza"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Longevidad: músculo, fuerza y cardio zona 2. Para vivir mejor más años, protege tu masa muscular y tu capacidad aeróbica. Combina entrenamiento de fuerza con cardio de zona 2 (ritmo en el que aún puedes conversar) varias horas por semana, más algo de alta intensidad. La proteína y la fuerza son medicina para la vejez.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Comer bajo GLP-1 (Ozempic/semaglutida)','El GLP-1 baja el apetito, así que el riesgo no es comer de más sino comer demasiado poco y perder músculo. Asegura tu proteína (prioriza la proteína en cada comida aunque comas poco), mantén la fuerza, hidrátate y vigila náuseas. Si las náuseas o el vómito son fuertes, avisa al médico.','nutricion','Alexandra Sowa (The Ozempic Revolution)','["glp1", "proteina", "musculo", "seguridad"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Comer bajo GLP-1 (Ozempic/semaglutida). El GLP-1 baja el apetito, así que el riesgo no es comer de más sino comer demasiado poco y perder músculo. Asegura tu proteína (prioriza la proteína en cada comida aunque comas poco), mantén la fuerza, hidrátate y vigila náuseas. Si las náuseas o el vómito son fuertes, avisa al médico.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Suplementos: fuente neutral y prudencia','De los suplementos, los que más respaldo tienen para entrenar son la creatina monohidrato (3-5 g/día) y la proteína en polvo como complemento si no llegas con comida. La cafeína ayuda al rendimiento. Antes de empezar cualquier suplemento, consúltalo con tu médico, sobre todo si tomas medicación.','nutricion','Examine.com','["suplementos", "creatina", "seguridad"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Suplementos: fuente neutral y prudencia. De los suplementos, los que más respaldo tienen para entrenar son la creatina monohidrato (3-5 g/día) y la proteína en polvo como complemento si no llegas con comida. La cafeína ayuda al rendimiento. Antes de empezar cualquier suplemento, consúltalo con tu médico, sobre todo si tomas medicación.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Dosis de proteína por comida','Cada comida estimula la síntesis de músculo hasta cierto punto: unos 30-40 g de proteína de buena calidad por toma (rica en leucina, como huevo, carne, pescado o lácteos) cubren bien ese estímulo. Mejor repartir la proteína en el día que concentrarla toda en una comida.','nutricion','Stuart Phillips (muscle full)','["proteina", "comidas", "leucina"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Dosis de proteína por comida. Cada comida estimula la síntesis de músculo hasta cierto punto: unos 30-40 g de proteína de buena calidad por toma (rica en leucina, como huevo, carne, pescado o lácteos) cubren bien ese estímulo. Mejor repartir la proteína en el día que concentrarla toda en una comida.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Estimación por foto es aproximada: corrige sin culpa','Calcular calorías y porciones desde una foto es aproximado (margen de 20-30%). Por eso te mostramos un nivel de confianza y puedes corregir en un toque. Las decisiones del plan se toman por la tendencia de varios días, no por la exactitud de una sola comida.','producto','Cal AI / práctica de visión','["foto", "confianza", "macros"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Estimación por foto es aproximada: corrige sin culpa. Calcular calorías y porciones desde una foto es aproximado (margen de 20-30%). Por eso te mostramos un nivel de confianza y puedes corregir en un toque. Las decisiones del plan se toman por la tendencia de varios días, no por la exactitud de una sola comida.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Una próxima acción a la vez','No intentes cambiarlo todo de golpe. Cada día hay una próxima mejor acción: registrar tu peso, completar tu entreno, tomar tu agua. Cumple una y suma. Los hábitos pequeños y constantes superan a los planes perfectos que no se sostienen.','adherencia','Noom (psicología de adherencia)','["habito", "motivacion", "ux"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Una próxima acción a la vez. No intentes cambiarlo todo de golpe. Cada día hay una próxima mejor acción: registrar tu peso, completar tu entreno, tomar tu agua. Cumple una y suma. Los hábitos pequeños y constantes superan a los planes perfectos que no se sostienen.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Hidratación en días de gimnasio','En días de entrenamiento apunta a alrededor de 3 litros de agua, repartidos en el día. La hidratación sostiene el rendimiento, el control del apetito y, bajo GLP-1, ayuda con los efectos digestivos. Lleva tu botella y registra tus vasos.','habito','Práctica clínica Pulso','["agua", "hidratacion", "gym"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Hidratación en días de gimnasio. En días de entrenamiento apunta a alrededor de 3 litros de agua, repartidos en el día. La hidratación sostiene el rendimiento, el control del apetito y, bajo GLP-1, ayuda con los efectos digestivos. Lleva tu botella y registra tus vasos.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Front-loading: un resultado temprano que motiva','Las primeras 2-4 semanas el plan aprieta un poco más (más caminata y un déficit en el extremo alto seguro) para que veas un resultado temprano y te enganches. Después se afloja a un ritmo sostenible y se prioriza preservar músculo. Nunca cruzamos los pisos de seguridad de calorías o proteína.','adherencia','Alex Hormozi (front-loading) + seguridad clínica','["motivacion", "deficit", "inicio"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Front-loading: un resultado temprano que motiva. Las primeras 2-4 semanas el plan aprieta un poco más (más caminata y un déficit en el extremo alto seguro) para que veas un resultado temprano y te enganches. Después se afloja a un ritmo sostenible y se prioriza preservar músculo. Nunca cruzamos los pisos de seguridad de calorías o proteína.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Señal de alarma: pérdida demasiado rápida','Bajar de peso muy rápido (más de 1% por semana de forma sostenida) no es mejor: suele significar pérdida de músculo y agua, fatiga y más riesgo de rebote. Si tus datos muestran esto, el sistema no lo celebra: lo marca y lo deriva al médico para ajustar el plan.','seguridad','Pisos de seguridad Pulso','["seguridad", "alarma", "escalamiento"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Señal de alarma: pérdida demasiado rápida. Bajar de peso muy rápido (más de 1% por semana de forma sostenida) no es mejor: suele significar pérdida de músculo y agua, fatiga y más riesgo de rebote. Si tus datos muestran esto, el sistema no lo celebra: lo marca y lo deriva al médico para ajustar el plan.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Relación sana con la comida','Comer no es un examen que se aprueba o reprueba. Si aparece culpa intensa, restricción extrema, atracones o ejercicio como castigo, eso importa y lo conversamos con el médico. El objetivo es salud, no perfección. Nunca recomendamos ayunos extremos ni restringir grupos enteros de alimentos sin razón clínica.','seguridad','Pisos de seguridad Pulso','["seguridad", "salud-mental", "escalamiento"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Relación sana con la comida. Comer no es un examen que se aprueba o reprueba. Si aparece culpa intensa, restricción extrema, atracones o ejercicio como castigo, eso importa y lo conversamos con el médico. El objetivo es salud, no perfección. Nunca recomendamos ayunos extremos ni restringir grupos enteros de alimentos sin razón clínica.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Piso de calorías: nunca demasiado bajo','El plan nunca baja las calorías por debajo de un piso seguro (alrededor de 1500 kcal en hombres y 1200 en mujeres, y nunca por debajo del 80% de tu metabolismo basal) sin indicación médica explícita. Comer demasiado poco frena el metabolismo y quema músculo. Menos no es mejor.','seguridad','Pisos de seguridad Pulso (Helms; práctica clínica)','["seguridad", "calorias", "piso"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Piso de calorías: nunca demasiado bajo. El plan nunca baja las calorías por debajo de un piso seguro (alrededor de 1500 kcal en hombres y 1200 en mujeres, y nunca por debajo del 80% de tu metabolismo basal) sin indicación médica explícita. Comer demasiado poco frena el metabolismo y quema músculo. Menos no es mejor.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Cardio y caminata (zona 2) cuentan','Caminar a paso vivo, bailar o trotar suave en zona 2 (puedes hablar pero no cantar) suma a tu salud y a tu déficit sin estresar la recuperación. La caminata diaria es una de las herramientas más subestimadas para perder grasa y cuidar el corazón.','ejercicio','Attia; práctica Pulso','["cardio", "caminata", "zona2", "adherencia"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Cardio y caminata (zona 2) cuentan. Caminar a paso vivo, bailar o trotar suave en zona 2 (puedes hablar pero no cantar) suma a tu salud y a tu déficit sin estresar la recuperación. La caminata diaria es una de las herramientas más subestimadas para perder grasa y cuidar el corazón.');
  kid := uuid_generate_v4();
  insert into knowledge_base (id,namespace,titulo,contenido,categoria,fuente,tags) values (kid,'movimiento','Progresión: cómo saber si estás avanzando','Avanzas si con el tiempo mueves más volumen (más peso, más reps o más series con buena técnica) en el mismo ejercicio. No tiene que ser cada sesión; mira la tendencia de semanas. Registrar tus cargas y reps es lo que te permite ver el progreso real y detectar tus récords.','ejercicio','Jeff Nippard; sobrecarga progresiva','["progresion", "volumen", "pr"]'::jsonb);
  insert into knowledge_chunks (knowledge_id,chunk_index,contenido) values (kid,0,'Progresión: cómo saber si estás avanzando. Avanzas si con el tiempo mueves más volumen (más peso, más reps o más series con buena técnica) en el mismo ejercicio. No tiene que ser cada sesión; mira la tendencia de semanas. Registrar tus cargas y reps es lo que te permite ver el progreso real y detectar tus récords.');
end $$;
